COM-2268: refacto tests
sophiemoustard/compani-api pull request #1543
Opened 2021-08-06 15:21 UTC by ulysseferreira

REFACTO Tests d'intégration : 

- activities

- activityHistories

- administrativeDocument

- attendances

- attendanceSheets

- authentication

- balances

2021-08-06 16:26 UTC, cmolle commented on tests/integration/activities.test.js
> -    it('should return a 400 if missing template', async () => {
Pourquoi l'avoir enlevé ? ca fait partie de `les options du payload  sont respectés (required, valid, format)` non ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/activities.test.js
> -    it('should return a 400 if missing template', async () => {
Pourquoi l'avoir enlevé ? ca fait partie de `les options du payload  sont respectés (required, valid, format)` non ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/activities.test.js
> -    it('should return 401 if user is not authenticate', async () => {
Pourquoi avoir enlever ce test ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/activityHistories.test.js
> -  it('should return a 401 if user is not connected', async () => {
Idem pourquoi avoir enlever ce test ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/activityHistories.test.js
>        authToken = await getTokenByCredentials(noRoleNoCompany.local);
Est-ce que dans le premier test (ligne 41) il ne faudrait pas verifier que l'historique d'activité est effectivement créé ? (par rapport a `la base de donnée est cohérente avec l’action de la route` )

2021-08-06 16:26 UTC, cmolle commented on tests/integration/administrativeDocument.test.js
>      it('should return all administrative documents', async () => {
Je crois que sur les routes get des fichirs precdents, il n'y avait pas de test pour verifier le nombre d'element qui nous etait renvoyé. Est-ce quelque chose que l'on veut tester ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/administrativeDocument.test.js
>      roles.forEach((role) => {
Pour les other roles de post administrativeDocuments je crois que c'est planning_referent et pas auxiliary pour la 403

2021-08-06 16:26 UTC, cmolle commented on tests/integration/administrativeDocument.test.js
>        { name: 'auxiliary', expectedCode: 403 },
idem ici c'est planning_referent

2021-08-06 16:26 UTC, cmolle commented on tests/integration/authentication.test.js
>  describe('NODE ENV', () => {
Dansle premier test (ligne 20), je crois qu tu n'as pas besoin de tester le retour de la route, ca vient du service.

2021-08-06 16:26 UTC, cmolle commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
Est-ce qu'on en a besoin ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
idem ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/authentication.test.js
> -    sendVerificationCodeSms = sinon.stub(SmsHelper, 'sendVerificationCodeSms');
Pourquoi avoir enlever ces stubs ?

2021-08-06 16:26 UTC, cmolle commented on tests/integration/balances.test.js
>        expect(response.result.data.balances).toBeDefined();
idem ?

2021-08-09 08:07 UTC, ulysseferreira commented on tests/integration/activities.test.js
>        expect(activityUpdated).toEqual(expect.objectContaining({ _id: activityId, cards: payload.cards }));
done

2021-08-09 08:11 UTC, ulysseferreira commented on tests/integration/activities.test.js
>          method: 'PUT',
done

2021-08-09 08:12 UTC, ulysseferreira commented on tests/integration/activities.test.js
> -    it('should return a 400 if missing template', async () => {
done

2021-08-09 08:15 UTC, ulysseferreira commented on tests/integration/activities.test.js
> -    it('should return 401 if user is not authenticate', async () => {
je ne trouve pas ce test très utile dans le sens où  n'importe qui peut se créer un compte et n'importe qui de connecté peut accéder à cette route. Et puis faudrait créer des 401 partout du coup

2021-08-09 08:16 UTC, ulysseferreira commented on tests/integration/activityHistories.test.js
> -  it('should return a 401 if user is not connected', async () => {
idem

2021-08-09 08:20 UTC, ulysseferreira commented on tests/integration/activityHistories.test.js
>        authToken = await getTokenByCredentials(noRoleNoCompany.local);
done

2021-08-09 08:25 UTC, ulysseferreira commented on tests/integration/administrativeDocument.test.js
>      it('should return all administrative documents', async () => {
bonne question, c'est pas très coûteux c'est peut-être pas mal à tester non ?

2021-08-09 08:33 UTC, ulysseferreira commented on tests/integration/administrativeDocument.test.js
>      roles.forEach((role) => {
hum non là vu qu'on teste une 200 il faut prendre le plus bas scope, si ça marche pour auxiliaire ça marchera pour planning referent (mais l'inverse n'est pas forcément vrai)

2021-08-09 08:34 UTC, ulysseferreira commented on tests/integration/administrativeDocument.test.js
>        { name: 'auxiliary', expectedCode: 403 },
ici et ligne 120 je suis d'accord

2021-08-09 08:35 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
c'est pour s'assurer que ça renvoie bien quelque chose, tu penses que c'est pas nécessaire ?

2021-08-09 08:35 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
idem

2021-08-09 08:35 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> -    sendVerificationCodeSms = sinon.stub(SmsHelper, 'sendVerificationCodeSms');
remis

2021-08-09 08:35 UTC, ulysseferreira commented on tests/integration/balances.test.js
>        expect(response.result.data.balances).toBeDefined();
idem

2021-08-09 09:08 UTC, sophiemoustard requested changes

2021-08-09 09:08 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +      { name: 'auxiliary', expectedCode: 403 },
ici c'est planning_referent plutot

2021-08-09 09:08 UTC, sophiemoustard commented on tests/integration/authentication.test.js
> +    expect(response.result.data).toBeDefined();
a-t-on besoin de ca ?

2021-08-09 09:23 UTC, ulysseferreira commented on tests/integration/activities.test.js
> +      expect(response.result.data.activity).toEqual(expect.objectContaining({ _id: activityId }));
done

2021-08-09 09:25 UTC, ulysseferreira commented on tests/integration/activities.test.js
> +      const activityUpdated = await Activity.findById(activityId).lean();
done

2021-08-09 09:25 UTC, ulysseferreira commented on tests/integration/activities.test.js
> +      const activityUpdated = await Activity.findById(activitiesList[3]._id).lean();
done

2021-08-09 09:25 UTC, cmolle commented on tests/integration/administrativeDocument.test.js
>      it('should return all administrative documents', async () => {
Je suis d'accord :)

2021-08-09 09:26 UTC, ulysseferreira commented on tests/integration/activities.test.js
>      it('should update activity\'s name', async () => {
done

2021-08-09 09:26 UTC, cmolle commented on tests/integration/administrativeDocument.test.js
>      roles.forEach((role) => {
Autant pour moi, je n'ai pas vu que c'etait une 200 :)

2021-08-09 09:27 UTC, cmolle commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
C'est vrai que ca permet de tester que le controlleur renvoie bien quelque chose... Mais du coup il faudrait le mettre partout et l'ajouter à notre strategie de test non ? Ou cette route est particuliere ?

2021-08-09 09:28 UTC, ulysseferreira commented on tests/integration/attendanceSheets.test.js
> -    });
done

2021-08-09 09:28 UTC, ulysseferreira commented on tests/integration/attendanceSheets.test.js
> -    });
done

2021-08-09 09:29 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +      { name: 'auxiliary', expectedCode: 403 },
done

2021-08-09 09:30 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +    expect(response.result.data).toBeDefined();
done

2021-08-09 09:46 UTC, cmolle commented on tests/integration/activities.test.js
> +      expect(response.result.data.activity).toEqual(expect.objectContaining({ _id: activityId }));
Est-ce un test inclus dans `la base de donnée est cohérente avec l’action de la route` ?

2021-08-09 09:46 UTC, cmolle commented on tests/integration/activityHistories.test.js
> +      const activityHistoriesBefore = await ActivityHistory.find().lean();
Tu dois pouvoir faire un countDocument ici

2021-08-09 13:15 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +    expect(res.result.data).toBeDefined();
non c'est vrai qu'on peut le faire à chaque fois qu'on retour un data dans le controller

2021-08-09 13:17 UTC, ulysseferreira commented on tests/integration/activities.test.js
> +      expect(response.result.data.activity).toEqual(expect.objectContaining({ _id: activityId }));
oui on s'assure que l'objet renvoyé est bien celui qu'on a demandé

2021-08-09 13:18 UTC, ulysseferreira commented on tests/integration/activityHistories.test.js
> +      const activityHistoriesBefore = await ActivityHistory.find().lean();
done

2021-08-09 13:31 UTC, cmolle commented on tests/integration/activities.test.js
> +      expect(response.result.data.activity).toEqual(expect.objectContaining({ _id: activityId }));
Ok ! Est-ce que tu pourrais developper dans le slite ce que l'on verifie exactement pour chaque type de route ? (get/post/put/delete)

2021-08-09 13:51 UTC, CorentinMartinot commented on tests/integration/authentication.test.js
>        { name: 'training_organisation_manager', expectedCode: 200 },
tu tests pas trainer: 403 ?

2021-08-09 13:57 UTC, cmolle commented on tests/integration/activities.test.js
>      it('should get activity', async () => {
Je ne pense pas que ce soit a inclure dans cette pr, mais cette route ne gere pas la 404, est-ce genant ?

2021-08-09 13:57 UTC, cmolle commented on tests/integration/activityHistories.test.js
>      it('should return a list of activity histories', async () => {
Je crois qu'il me manque l'expect pour verifier le nombre d'historique d'activité

2021-08-09 14:04 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
>      it('should return a list of activity histories', async () => {
je crois qu'on s'est dit qu'on ne testait pas les retours de route, simplement les modif en bdd non ?

2021-08-09 15:14 UTC, ulysseferreira commented on tests/integration/authentication.test.js
>        { name: 'training_organisation_manager', expectedCode: 200 },
done

2021-08-09 15:18 UTC, ulysseferreira commented on tests/integration/activities.test.js
>      it('should get activity', async () => {
ça renvoie : `{ message: "Activité trouvée.", data: { activity: null } }` on pourrait faire un prehandler en effet. Tu fais un ticket ?

2021-08-09 15:49 UTC, ulysseferreira commented on tests/integration/activityHistories.test.js
>      it('should return a list of activity histories', async () => {
done

2021-08-09 15:58 UTC, ulysseferreira commented on tests/integration/activities.test.js
> +      expect(response.result.data.activity).toEqual(expect.objectContaining({ _id: activityId }));
done

2021-08-09 16:04 UTC, cmolle commented on tests/integration/activities.test.js
>      it('should get activity', async () => {
Ok !

2021-08-09 16:06 UTC, cmolle approved these changes

2021-08-10 08:36 UTC, CorentinMartinot approved these changes

2021-08-10 09:04 UTC, sophiemoustard approved these changes

2021-08-10 09:04 UTC, merged