Com 2296
sophiemoustard/compani-api pull request #1577
Opened 2021-08-31 14:47 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### ~~FONCTIONNALITÉS APPS MOBILES~~
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- J'ai ajouté un modèle spécifique à une structure:
  - [x] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### ~~CONSTANTES ET VARIABLE D'ENV~~
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : 
Dans la configuration bénéficiaire, je peux ajouter un article de facturation.

2021-08-31 15:01 UTC, sophiemoustard requested changes

2021-08-31 15:01 UTC, sophiemoustard commented on tests/integration/seed/billingItemsSeed.js
> +const billingItemList = [
peux tu en mettre un deuxieme relié a une autre structure pour valider que le find ne renvoie bien que ceux de la structure de l'utilisateur connecté ?

2021-08-31 15:28 UTC, ulysseferreira commented on tests/integration/billingItems.test.js
> +      const createdBillingItem = await BillingItem.countDocuments({ name: 'Billing Jean' });
peut-être faire le countDocuments sur la company également ?

2021-08-31 15:36 UTC, KennyCallegari commented on src/models/BillingItem.js
> +  type: { type: String, enum: BILLING_ITEM_TYPES, required: true },
done

2021-08-31 15:36 UTC, KennyCallegari commented on src/controllers/billingItemController.js
> +const BillingItemHelper = require('../helpers/billingItems');
done

2021-08-31 15:36 UTC, KennyCallegari commented on src/models/BillingItem.js
> +  company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true },
done

2021-08-31 15:38 UTC, KennyCallegari commented on src/models/BillingItem.js
> +BillingItemSchema.pre('find', validateQuery);
done, je pense aussi que c'est une bonne pratique effectivement

2021-08-31 15:41 UTC, KennyCallegari commented on tests/integration/billingItems.test.js
> +      it(`should return a 400 error if '${param}' payload is missing`, async () => {
done

2021-08-31 15:43 UTC, KennyCallegari commented on tests/integration/seed/billingItemsSeed.js
> +const billingItemList = [
bien vu, done

2021-08-31 15:46 UTC, KennyCallegari commented on tests/unit/helpers/billingItems.test.js
> +    const credentials = { company: { _id: new ObjectID() } };
done

2021-08-31 15:47 UTC, KennyCallegari commented on tests/unit/helpers/billingItems.test.js
> +  it('should every billing items from user\'s company', async () => {
done

2021-08-31 15:51 UTC, KennyCallegari commented on tests/integration/billingItems.test.js
> +      const createdBillingItem = await BillingItem.countDocuments({ name: 'Billing Jean' });
done

2021-08-31 16:32 UTC, sophiemoustard commented on src/controllers/billingItemController.js
> +const BillingItemHelper = require('../helpers/billingItems');
je ne vois pas la modification

2021-09-01 08:00 UTC, ulysseferreira approved these changes

2021-09-01 08:51 UTC, KennyCallegari commented on src/controllers/billingItemController.js
> +const BillingItemHelper = require('../helpers/billingItems');
effectivement, je ne sais pas comment ça s'est perdu
C'est bon

2021-09-01 09:06 UTC, sophiemoustard commented on src/routes/billingItems.js
> +            vat: Joi.number().allow('', null),
comme c'est un nombre, il vaut peut etre mieux mettre `required()` ici plutot que `.allow('', null)` - sinon on risaue d'avoir des souci en voulant multiplier plus tard. qu'en pense tu ?
tu peux aussi le mettre en requis en front et dans le modèle

2021-09-01 11:44 UTC, sophiemoustard approved these changes

2021-09-01 11:45 UTC, merged