Com 2306
sophiemoustard/compani-api pull request #1578
Opened 2021-09-02 10:04 UTC by ulysseferreira

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- Si mes changements impactent l'application formation :
  - [x] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [x] Affichage des pages explorer/mes formations/About/CourseProfile
    - [x] Inscription a une formation e-learning
    - [x] Possibilité de faire une activité

- ~~Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME
- [x] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [x] Je n'ai pas changé les droits dans le fichier rights.js
  - [x] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a: tout le monde à accès à get companies / les params de cette route n'étaient pas utilisés
- ~~J'ai supprimé une route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- ~~J'ai renommé une route :~~
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- ~~J'ai ajouté un champ possible dans la route :~~
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- ~~J'ai rendu obligatoire un champs de la route :~~
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- ~~J'ai retiré un champ possible dans la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- ~~J'ai supprimé un retour/un champs du retour de la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
- ~~J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : mobile formation

- Périmetre roles : tous

- Cas d'usage : 
TEST sur la page Profile
- avec mon compte : je vois le nom de ma structure
- avec un compte rattaché à aucun structure : 
  - je vois un bouton pour me rattacher à une structure
  - je peux faire une demande de rattachement à une structure
  - une fois la demande faite, celle-ci s'affiche sur mon profil

2021-09-02 14:31 UTC, sophiemoustard requested changes

2021-09-02 14:31 UTC, sophiemoustard commented on src/helpers/users.js
> +    .populate({
ca ne tient pas sur une ligne ?

2021-09-02 14:31 UTC, sophiemoustard commented on src/models/User.js
> +  {
sur une ligne ?

2021-09-02 14:31 UTC, sophiemoustard commented on src/routes/companyLinkRequests.js
> +        pre: [
sur une ligne

2021-09-02 14:31 UTC, sophiemoustard commented on tests/integration/companyLinkRequests.test.js
> +      authToken = await getTokenByCredentials(userWithAlreadyCompanyLinkRequest.local);
userWithCompanyLinkRequest non ?

2021-09-02 14:31 UTC, sophiemoustard commented on tests/integration/seed/companyLinkRequestsSeed.js
> +const companyLinkRequest = {
sur une ligne ?

2021-09-02 15:01 UTC, sophiemoustard commented on src/controllers/companyController.js
>        message: translate[language].companyCreated,
peux tu changer ce massage stp ?

2021-09-02 15:20 UTC, ulysseferreira commented on src/helpers/users.js
> +    .populate({
done

2021-09-02 15:20 UTC, ulysseferreira commented on src/models/User.js
> +  {
done

2021-09-02 15:21 UTC, ulysseferreira commented on src/routes/companyLinkRequests.js
> +        pre: [
done

2021-09-02 15:21 UTC, ulysseferreira commented on tests/integration/companyLinkRequests.test.js
> +      authToken = await getTokenByCredentials(userWithAlreadyCompanyLinkRequest.local);
done

2021-09-02 15:22 UTC, ulysseferreira commented on tests/integration/seed/companyLinkRequestsSeed.js
> +const companyLinkRequest = {
done

2021-09-02 15:25 UTC, ulysseferreira commented on src/controllers/companyController.js
>        message: translate[language].companyCreated,
done

2021-09-03 09:56 UTC, CorentinMartinot approved these changes

2021-09-03 10:29 UTC, sophiemoustard approved these changes

2021-09-03 13:34 UTC, merged