Com 2308
sophiemoustard/compani-api pull request #1586
Opened 2021-09-07 09:51 UTC by ulysseferreira

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- ~~Si mes changements impactent l'application formation :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- ~~Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME -np
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
-~~ J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : coach/admin

- Cas d'usage : je peux supprimer les demandes de rattachement à ma structure

2021-09-07 12:37 UTC, CorentinMartinot commented on src/routes/companyLinkRequests.js
> +      path: '/{_id}',
ici on recoit pas l'ID de la companyLinkRequest mais l'ID du user. Je mettrait donc userId

2021-09-07 13:34 UTC, ulysseferreira commented on src/routes/companyLinkRequests.js
> +      path: '/{_id}',
done

2021-09-07 13:37 UTC, CorentinMartinot approved these changes

2021-09-07 15:28 UTC, sophiemoustard requested changes

2021-09-07 15:28 UTC, sophiemoustard commented on src/helpers/companyLinkRequests.js
> +exports.removeCompanyLinkRequest = async _id => CompanyLinkRequest.deleteOne({ _id });
pas de _

2021-09-07 15:28 UTC, sophiemoustard commented on src/helpers/translate.js
> +    companyLinkRequestRemoved: 'Company link request removed.',
deleted ?

2021-09-07 15:28 UTC, sophiemoustard commented on src/routes/preHandlers/companyLinkRequests.js
> +  const companyId = get(req, 'auth.credentials.company._id', null);
pas besoin de null en 3eme parametre

2021-09-07 16:08 UTC, ulysseferreira commented on src/helpers/companyLinkRequests.js
> +exports.removeCompanyLinkRequest = async _id => CompanyLinkRequest.deleteOne({ _id });
done

2021-09-07 16:10 UTC, ulysseferreira commented on src/helpers/translate.js
> +    companyLinkRequestRemoved: 'Company link request removed.',
done

2021-09-08 08:33 UTC, sophiemoustard approved these changes

2021-09-08 08:34 UTC, merged