Com 2297
sophiemoustard/compani-api pull request #1591
Opened 2021-09-08 07:12 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### ~~FONCTIONNALITÉS APPS MOBILES~~
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### ~~CONSTANTES ET VARIABLE D'ENV~~
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : 
  Dans la config bénéficiaire, dans la modale d'édition, je peux lier un article avec un service.

 2 choses :
 - Le ticket fait mention d'une colonne à ajouter avec les tags des différents articles mais la stratégie technique n'en fait pas mention, est-ce que c'est un oubli ou bien il ne faut pas le faire dans ce sprint ?
- Est-ce qu'il faudrait supprimer la possibilité d'ajouter deux fois le même article ? Ce n'est pas mentionné dans le ticket

2021-09-08 08:49 UTC, sophiemoustard requested changes

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/preHandlers/services.js
> +  if (!service) throw Boom.forbidden();
pourquoi ce changement de 403 en 404 ? etant donné qu'on est sur une route de service pour moi c'est une 404

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/preHandlers/services.js
> +  if (req.payload && req.payload.billingItems) {
get de lodash ?

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/preHandlers/services.js
> +      .find({ _id: { $in: req.payload.billingItems }, company: companyId, type: PER_INTERVENTION })
je pense qu'il il faut que tu fasses `formatObjectIdsArray(req.payload.billingItems)`

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/preHandlers/services.js
> +    if (!billingItems) throw Boom.forbidden();
cette condition est etrange. tu fais la negation d'un tableau, c'est voulu ?

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/services.js
> +              billingItems: Joi.array().items(Joi.objectId()),
`objectIdOrArray` non pour gerer le cas ou tu n'en envoie qu'un seul

2021-09-08 08:49 UTC, sophiemoustard commented on tests/integration/seed/servicesSeed.js
> +  await BillingItem.create(billingItemList);
promise.all

2021-09-08 08:49 UTC, sophiemoustard commented on src/routes/preHandlers/services.js
> +  if (!service) throw Boom.forbidden();
apres je suis d'accord que pour l'archive c'est plus logique d'envoyer une 403 donc peut etre separer les 2 conditions ?

2021-09-08 08:49 UTC, sophiemoustard commented on tests/integration/services.test.js
> +    it('should return a 403 error if user is not from the same company', async () => {
`if service` non ?

2021-09-08 08:49 UTC, sophiemoustard commented on tests/integration/services.test.js
> +  it('should return a 403 error if user is not from the same company', async () => {
idem `if service` ?

2021-09-08 09:55 UTC, CorentinMartinot commented on src/routes/preHandlers/services.js
> +  if (!service) throw Boom.forbidden();
c'est bien de separer je trouve genre 
```
const service = await Service.findOne({ _id: serviceId, company: companyId}).lean();
  if (!service) throw Boom.notFound();
  if (service.isArchive) throw Boom.forbidden();

2021-09-08 09:56 UTC, CorentinMartinot commented on src/routes/preHandlers/services.js
> +      .find({ _id: { $in: req.payload.billingItems }, company: companyId, type: PER_INTERVENTION })
un countDocument suffit

2021-09-08 10:03 UTC, CorentinMartinot commented on tests/integration/services.test.js
> +    it('should return a 403 error if some billingItem doesn\'t exists in company', async () => {
if any billingItem doesn't exist (sans s)

2021-09-08 12:54 UTC, KennyCallegari commented on src/routes/preHandlers/services.js
> +  if (!service) throw Boom.forbidden();
Je suis d'accord, je l'avais mis pour le isArchived mais effectivement c'est logique d'avoir une 404 si le service n'existe pas tout court

2021-09-10 07:34 UTC, KennyCallegari commented on src/routes/preHandlers/services.js
> +  if (!service) throw Boom.forbidden();
done

2021-09-10 07:35 UTC, KennyCallegari commented on src/routes/preHandlers/services.js
> +  if (req.payload && req.payload.billingItems) {
done

2021-09-10 07:36 UTC, KennyCallegari commented on src/routes/preHandlers/services.js
> +    if (!billingItems) throw Boom.forbidden();
done

2021-09-10 08:06 UTC, KennyCallegari commented on tests/integration/seed/servicesSeed.js
> +  await BillingItem.create(billingItemList);
done

2021-09-10 08:07 UTC, KennyCallegari commented on tests/integration/services.test.js
> +    it('should return a 403 error if user is not from the same company', async () => {
done

2021-09-10 08:07 UTC, KennyCallegari commented on tests/integration/services.test.js
> +  it('should return a 403 error if user is not from the same company', async () => {
done

2021-09-10 08:08 UTC, KennyCallegari commented on src/routes/preHandlers/services.js
> +      .find({ _id: { $in: req.payload.billingItems }, company: companyId, type: PER_INTERVENTION })
done

2021-09-10 08:09 UTC, KennyCallegari commented on tests/integration/services.test.js
> +    it('should return a 403 error if some billingItem doesn\'t exists in company', async () => {
done

2021-09-10 10:03 UTC, CorentinMartinot commented on tests/integration/seed/servicesSeed.js
> +  Promise.all([
c'est sur le promise.all le await et pas sur les elements a l'interieur

2021-09-10 14:23 UTC, CorentinMartinot approved these changes

2021-09-10 16:06 UTC, sophiemoustard approved these changes

2021-09-10 16:20 UTC, merged