Com 2328
sophiemoustard/compani-api pull request #1609
Opened 2021-09-15 16:52 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### ~~FONCTIONNALITÉS APPS MOBILES~~
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### ~~MODIFICATIONS SUR LES MODÈLES~~
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### ~~CONSTANTES ET VARIABLE D'ENV~~
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : 
Sur la page 'A Facturer', je vois les articles de facturation lorsqu'une intervention est liée à un article de facturation.

Pour tester : 
  - ajouter 2 - 3 articles de facturation par intervention
  - lier ces facturations avec des services (penser à varier les dates d'effet, pour vérifier qu'elles sont bien prises en compte)
  - ajouter des interventions à un bénéficiaire en variant : le service, la date, ...
  - Regarder sur la page 'A facturer' que vous voyez bien les articles liés aux interventions avec le bon prix pour chaque intervention

2021-09-16 10:29 UTC, manonpalin commented on src/helpers/draftBills.js
>    for (const event of events) {
Que dis-tu de sauter une ligne ici pour aérer un peu?

2021-09-16 10:29 UTC, manonpalin commented on src/helpers/draftBills.js
>      const matchingFunding = fundings && fundings.length > 0
Ici on pourrait remplacer par : 
```
const matchingFunding = fundings && fundings.length ? exports.getMatchingFunding(event.startDate, fundings) : null;
```

2021-09-16 10:29 UTC, manonpalin commented on src/helpers/draftBills.js
> +    if (get(matchingService, 'billingItems.length')) {
Est-ce que ce if est nécessaire? Si billingItems est vide, normalement on ne rentrera pas dans la boucle for

2021-09-16 10:35 UTC, manonpalin commented on src/helpers/draftBills.js
> +      const existingbillingItemIndex = formattedBillingItems.findIndex(bi => bi.billingItem._id === billingItemId);
Que penses tu d'utiliser la methode `areObjectIdsEquals` du service utils? 
```
const existingbillingItemIndex = formattedBillingItems.findIndex(bi => UtilsHelper.areObjectIdsEquals(bi.billingItem._id, billingItemId);
```

2021-09-16 10:35 UTC, sophiemoustard requested changes

2021-09-16 10:35 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +exports.formatBillingItemsDraftBills = async (eventsGroupedByBillingItemList, startDate, endDate) => {
que penses tu de nommer cette fonction `formatBillingItems`

2021-09-16 10:35 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      const bddBillingItem = await BillingItem.findOne({ _id: billingItemId }).lean();
que penses tu de reutiliser la liste que tu recuperes dans la methode
`getDraftBIlls` -> `  const bddBillingItems = await BillingItem.find({ company: companyId }).lean();`

2021-09-16 10:35 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +  const bddBillingItems = await BillingItem.find({ company: companyId }).lean();
je trouverai ca plus logique de npmmer cette variable `billingItems` comme `surcharges` ou `thirdPartyPayersList`  qu'on pourrait renommer en `thirdPartyPayers` d'ailluers
et de renommer autrement la variable `billingItems` de la ligne 397 - `eventsByBillingItem` par exemple

2021-09-16 10:35 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      const unitExclTaxes = bddBillingItem.defaultUnitAmount / (1 + bddBillingItem.vat / 100);
tu peux utiliser `getExclTaxes` ici

2021-09-16 10:35 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +          * eventsList.length;
je ne comprends pas ce que tu essaies de faire ici

2021-09-16 10:39 UTC, manonpalin commented on src/helpers/draftBills.js
> +      const bddBillingItem = await BillingItem.findOne({ _id: billingItemId }).lean();
Que penses-tu de nommer cette variable `billingItem`? Je trouve que ca alourdi d'ajouter bdd

2021-09-16 10:45 UTC, manonpalin commented on tests/unit/helpers/draftbills.test.js
> +        { _id: new ObjectID('d00000000000000000000000'), name: 'skusku' },
pourquoi ajouter un argument? On n'est pas sur que nos id sont uniques?

2021-09-16 12:12 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      .sort((a, b) => new Date(b.startDate) - new Date(a.startDate)), // bug étrange temps de qualité de vie,
done

2021-09-16 12:19 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      .sort((a, b) => new Date(b.startDate) - new Date(a.startDate)), // bug étrange temps de qualité de vie,
done (il y en avait déjà une)

2021-09-16 12:22 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +          billingItems[`${billingItem._id}`] = [event._id];
done

2021-09-16 12:24 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +        if (Object.keys(billingItems).includes(billingItem._id.toHexString())) {
done

2021-09-16 12:25 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +exports.formatBillingItemsDraftBills = async (eventsGroupedByBillingItemList, startDate, endDate) => {
done

2021-09-16 12:44 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      const bddBillingItem = await BillingItem.findOne({ _id: billingItemId }).lean();
done

2021-09-16 12:47 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +  const bddBillingItems = await BillingItem.find({ company: companyId }).lean();
done

2021-09-16 12:56 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      const unitExclTaxes = bddBillingItem.defaultUnitAmount / (1 + bddBillingItem.vat / 100);
done

2021-09-16 13:00 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +        { _id: new ObjectID('d00000000000000000000000'), name: 'skusku' },
Je ne peux pas vraiment : ces id deviennent des champs d'un objet. Il faut donc que je connaisse à l'avance quel sera leur forme pour définir l'objet auquel au s'attend.

Si tu regardes l.773, :
l'objet billingItems à cette tête :  `billingItems: {  d00000000000000000000000: [events[0]._id.toHexString(), events[1]._id.toHexString()], }`

Il faut donc que je connaisse l'id des articles présents dans le service pour définir le champ de `billingItems` qu'on attends à la sortie de la fonction

2021-09-16 15:43 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +          * eventsList.length;
On a en entrée une array sous la forme : 
```
[
      { billingItemId1: ['eventId1', 'eventId2'], billingItemId2: ['eventId1, eventId2'] },
      { billingItemId1: ['eventId3'] },
]
```
Pour un bénéficiaire qui aurait 2 souscriptions :
- une sur 2 evenements : eventId1 et eventId2 lié à 2 articles billingItemId1 et billingItemId2
- une sur un evnement : eventId3 lié à un article billingItemId1

on souhaite avoir en sortie de la fonction la liste suivante : 
```
[
  {
        billingItem: { _id: 'billingItemId1', name: 'FI' },
        unitInclTaxes: 1,
        eventsList: ['eventId1', 'eventId2', 'eventId3'],
        inclTaxes: 3,
  },
  {
        billingItem: { _id: 'billingItemId2', name: 'FI' },
        unitInclTaxes: 2,
        eventsList: ['eventId1', 'eventId2'],
        inclTaxes: 4,
  },
]
```

Donc : 
- on boucle sur l'array d'entrée, on a cet array à la fin de la première boucle : 
```
[
  {
        billingItem: { _id: 'billingItemId1', name: 'FI' },
        unitInclTaxes: 1,
        eventsList: ['eventId1', 'eventId2'],
        inclTaxes: 2,
  },
  {
        billingItem: { _id: 'billingItemId2', name: 'FI' },
        unitInclTaxes: 2,
        eventsList: ['eventId1', 'eventId2'],
        inclTaxes: 4,
  },
]
```
- on boucle une seconde fois et là, il ne faut pas ajouter un objet à notre array
```
   {
        billingItem: { _id: 'billingItemId1', name: 'FI' },
        unitInclTaxes: 1,
        eventsList: ['eventId3'],
        inclTaxes: 1,
  },
```
- il faut ajouter l'eventId3 à eventList du 1er objet et augmenter inclTaxes.

C'est ce que j'avais voulu faire avec cette solution.


Ma nouvelle solution formate l'array d'entrée en : 
```
{
  billingItemId1: ['eventId1', 'eventId2', 'eventId3'],
  billingItemId2: ['eventId1, eventId2'],
},
```

Ce qui permet de ne boucler que sur cet objet, et formater directement pour avoir l'array de sortie souhaitée.


C'est plus clair ?

2021-09-16 16:56 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      eventsList,
Je suis entrain de travailler sur le ticket suivant et il semblerait qu'il ne faille pas un tableau d'id ici mais un tableau d'objet de cette forme : 
```
Joi.object({
  event: Joi.objectId().required(),
  startDate: Joi.date().required(),
  endDate: Joi.date().required(),
  auxiliary: Joi.objectId().required(),
  inclTaxesCustomer: Joi.number().required(),
  exclTaxesCustomer: Joi.number().required(),
  inclTaxesTpp: Joi.number(),
  exclTaxesTpp: Joi.number(),
  thirdPartyPayer: Joi.objectId(),
  surcharges: Joi.array().items(Joi.object({
    percentage: Joi.number().required(),
    name: Joi.string().required(),
    startHour: Joi.date(),
    endHour: Joi.date(),
  })),
}),
```

Ce qui est en accord avec la stratégie tech du prochain ticket d'ailleurs.
Après, je peux contourner ça et là où j'ai besoin d'avoir un tableau d'objet je peux populer mon tableau d'id. Mais ce n'est pas homogène avec les factures existantes

2021-09-16 16:59 UTC, sophiemoustard requested changes

2021-09-16 16:59 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +const populateSurchargeAndBillingItem = (arr, surcharges, billingItems) => arr.map(v => ({
je pense que le bon formattage est de mettre le `.map` a la ligne pour etre aligné avec le `.sort`

2021-09-16 16:59 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +    billingItems.find(bddBI => UtilsHelper.areObjectIdsEquals(bddBI._id, bi))),
je crois que ca tient sur une ligne

2021-09-16 16:59 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +          .concat(eventsList);
ca tient sur une ligne

2021-09-16 16:59 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +const formatEventsByBillingItem = (eventsByBillingItemBySubscriptions) => {
Corentin avait suggeré `mergeWith` en commentaire sur slack ou jira et j'ai oublié de le mettre dans le ticket
ca pourrait fonctionner ?

https://docs-lodash.com/v4/merge-with/

2021-09-16 16:59 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      fundings = fundings ? await exports.populateFundings(fundings, dates.endDate, thirdPartyPayers, companyId) : null;
que penses tu de mettre ?
```
const fundings = eventsBySubscriptions[k].fundings
        ? await exports.populateFundings(eventsBySubscriptions[k].fundings, dates.endDate, thirdPartyPayers, companyId)
        : null;
```

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +            startDate: new Date('2019-03-01T00:00:00.000Z'),
pourquoi ici as tu mis `T00:00:00.000Z` et pas au dessus ?

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
>    it('should populate surcharge and order versions', async () => {
que penses tu de renommer ce `it` ?

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
>      getMatchingVersion.returns(matchingService);
je trouverai ca bien que tu definisses des versions dans ton service et que `getMatchingVersion` ne retourne pas la meme version dans les 2 cas que le traitement soit different. par exemple dans un dex 2 cas, tu n'as qu'un seul billlingItem dans la version

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
dans la realité cette clé est dans `versions` non ?
si oui, je trouverai mieux d'avoir des objets plausibles dans les tests -> dans la logique : les tests nous servent un peu de documentation pour le code

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
>      sinon.assert.calledWithExactly(getMatchingVersion.getCall(1), events[1].startDate, service, 'startDate');
peux tu changer `events[0].startDate` pour mettre les chaines de caractères correspondantes stp ?

2021-09-16 16:59 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +      },
ca tient sur une ligne

2021-09-16 17:01 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +    // 1ère version est un string et pas une date
le bug est toujours present ? il faut peut etre allé changé le type en bdd directement non ?

2021-09-16 17:01 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +const populateSurchargeAndBillingItem = (arr, surcharges, billingItems) => arr.map(v => ({
done

2021-09-16 17:02 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +    billingItems.find(bddBI => UtilsHelper.areObjectIdsEquals(bddBI._id, bi))),
done

2021-09-16 17:03 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +          .concat(eventsList);
done

2021-09-16 17:03 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      if (existingbillingItemIndex !== -1) {
je ne comprends pas ton message ici

2021-09-16 17:04 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +          * eventsList.length;
je trouve ton nouveau code top !

2021-09-16 17:06 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      eventsList,
que penses tu de faire ca dans un seconde PR ?
il y a deja pas mal de choses a valider ici et ca nous permettrait d'y voir plus clair je pense

2021-09-16 17:16 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +const formatEventsByBillingItem = (eventsByBillingItemBySubscriptions) => {
done, mais la solution n'est pas très élégante 😄

2021-09-16 17:18 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      fundings = fundings ? await exports.populateFundings(fundings, dates.endDate, thirdPartyPayers, companyId) : null;
done

2021-09-16 17:19 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +            startDate: new Date('2019-03-01T00:00:00.000Z'),
oubli de ma part. Les T00:00:00.000Z sont inutiles car new Date() les ajoute automatiquement

2021-09-16 17:20 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +            startDate: new Date('2019-03-01T00:00:00.000Z'),
done

2021-09-16 17:21 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
>    it('should populate surcharge and order versions', async () => {
done

2021-09-17 06:48 UTC, manonpalin commented on src/helpers/draftBills.js
> +          * eventsList.length;
Oui je trouve aussi que c'est bien plus clair ! :)

2021-09-17 07:01 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +    // 1ère version est un string et pas une date
j'ai changé le format en bdd de prod. c'est mieux la ?

2021-09-17 07:12 UTC, manonpalin commented on src/helpers/draftBills.js
> +  const eventsByBillingItem = {};
C'est plutot un tableau non?

2021-09-17 07:25 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +    // 1ère version est un string et pas une date
Il faudrait le changer pour Forfait nuit aussi

2021-09-17 07:26 UTC, manonpalin commented on src/helpers/draftBills.js
> +    if (Object.values(tppBills).length > 0) {
`if (Object.values(tppBills).length)` devrait suffire

2021-09-17 07:28 UTC, manonpalin commented on src/helpers/historyExport.js
>  const getMatchingSector = (histories, event) => histories.filter(sh => moment(sh.startDate).isBefore(event.startDate))
Pour le formatage tu peux mettre `.filter(sh => moment(sh.startDate).isBefore(event.startDate))` a la ligne

2021-09-17 07:29 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      eventsList,
ça marche ! Je vais voir si je peux caser ça dans ma PR 2329

2021-09-17 07:39 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +  const eventsByBillingItem = {};
C'est une de nos conventions d'écriture car il fait référence au groupBy de lodash qui est une fonction très pratique qu'on utilise souvent.

Par exemple groupBy sur une array : 
```
[
  {
    _id: eventId1,
    billingItem: billingItemId
  }
  {
    _id: eventId2,
    billingItem: billingItemId
  }
]
```
Groupée avec groupBy selon les billingItem va renvoyer un objet comme ceci : 
` { billingItem: [ eventId1, event Id2 ] }`

Un objet de cette forme est typique de la forme des objets retournés par groupBy et donc le nom eventsGroupedByBillingItem fait référence à un objet avec une forme semblable.

La doc de Lodash sera surement plus claire que moi : https://lodash.com/docs/4.17.15#groupBy 😄 

ça te semble correct ?

2021-09-17 09:09 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
>      getMatchingVersion.returns(matchingService);
done

2021-09-17 09:11 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
oui ! c'est fait

2021-09-17 09:13 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +      },
done

2021-09-17 09:13 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +    if (Object.values(tppBills).length > 0) {
done

2021-09-17 09:14 UTC, KennyCallegari commented on src/helpers/historyExport.js
>  const getMatchingSector = (histories, event) => histories.filter(sh => moment(sh.startDate).isBefore(event.startDate))
done

2021-09-17 10:33 UTC, manonpalin commented on src/helpers/draftBills.js
> +  const eventsByBillingItem = {};
Merci pour l'explication ;)
Le nom me perturbait un peu mais apres réflexion et ton explication laissons comme ca!

2021-09-17 11:56 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
>      sinon.assert.calledWithExactly(getMatchingVersion.getCall(1), events[1].startDate, service, 'startDate');
done

2021-09-17 12:38 UTC, manonpalin approved these changes

2021-09-17 13:27 UTC, sophiemoustard requested changes

2021-09-17 13:27 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +  it('should populate surcharge and billing items and order versions', async () => {
sort plutot que order
order ca veut plutot dire commander

2021-09-17 13:27 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
je ne vois pas le changement

2021-09-17 14:32 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
matchingService porte mal son nom, ce serait plutôt matchingServiceVersion. L'objet renvoyé ne contient pas de champ version

2021-09-17 14:49 UTC, KennyCallegari commented on tests/unit/helpers/draftbills.test.js
> +  it('should populate surcharge and billing items and order versions', async () => {
done

2021-09-17 15:26 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
pourrais tu les renommer matchingVersion1 et matchingVersion2 stp ?

2021-09-17 15:29 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +const formatEventsByBillingItem = (eventsByBillingItemBySubscriptions) => {
j'ai essayé de comprendre le fonctionnement de cette methode en logguant `a` et `b` pour voir comment on pourrait respecter esling mais j'avoue que je ne suis pas trop...
du coup je me demande s'il ne vaiut pas mieux revenir au code d'avant qu'on maitrise.. qu'en penses tu ?

2021-09-17 15:44 UTC, sophiemoustard commented on tests/unit/helpers/draftbills.test.js
> +      billingItems: [
vu ensemble, ok

2021-09-17 15:45 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +          .concat(eventsList);
du coup non ^^

2021-09-17 15:47 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +          .concat(eventsList);
done

2021-09-17 15:49 UTC, sophiemoustard approved these changes

2021-09-17 16:10 UTC, merged