Com 2329
sophiemoustard/compani-api pull request #1614
Opened 2021-09-17 16:39 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### ~~FONCTIONNALITÉS APPS MOBILES~~
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### ~~MODIFICATIONS SUR LES MODÈLES~~
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### ~~CONSTANTES ET VARIABLE D'ENV~~
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : 
Je peux facturer un bénéficiaire qui a des articles à facturer.

Pour tester la PR : 
- Ajouter des évènements pour des services liés à des articles à un bénéficiaire.
- Sur la page A Facturer, ces articles apparaissent (⚠️ pensez à jouer avec les dates d'effet)
- Lorsque je facture un service avec des articles liés : 
  - une facture est créée en bdd
  - les événements associés sont marqués comme facturés

2021-09-20 08:37 UTC, KennyCallegari commented on src/helpers/bills.js
> +          exclTaxes: draftBill.exclTaxes,
Je ne suis pas sûr du calcul de ces deux champs

2021-09-20 13:21 UTC, manonpalin commented on src/helpers/bills.js
> +        const exclTaxesCustomer = draftBill.exclTaxes + (billedEvents[ev.event].exclTaxesCustomer || 0);
Que penses-tu d'ecrire ici: 
``` 
const exclTaxesCustomer = billedEvents[ev.event].exclTaxesCustomer ?  draftBill.exclTaxes +  billedEvents[ev.event].exclTaxesCustomer : draftBill.exclTaxes 
```

2021-09-20 13:22 UTC, manonpalin commented on src/helpers/bills.js
> +        const exclTaxesCustomer = draftBill.exclTaxes + (billedEvents[ev.event].exclTaxesCustomer || 0);
Idem pour inclTaxesCustomer

2021-09-20 13:53 UTC, manonpalin commented on tests/integration/seed/billsSeed.js
>        exclTaxes: 4,
C'est étrange d'avoir un `exclTaxes` supérieur au montant avec taxes `inclTaxes`

2021-09-20 13:54 UTC, manonpalin commented on tests/unit/helpers/bills.test.js
> +describe('formatBillingItemData #tag', () => {
T'as oublié le tag ;)

2021-09-20 14:15 UTC, manonpalin commented on tests/unit/helpers/bills.test.js
> +        inclTaxesTpp: 5,
Ici il faudrait retirer `inclTaxesTpp`,  `exclTaxesTPP` et `fundingTpp`, il n'y a que les champs : event,  auxiliary, startDate, endDate, inclTaxesCustomer et exclTaxesCustomer dans eventsList non?

2021-09-20 14:16 UTC, manonpalin commented on tests/unit/helpers/bills.test.js
> +          subscription: { _id: 'asd', service: { versions: [{ vat: 12, startDate: moment().toISOString() }] } },
Il me semble que dans les tests on met plutot les dates en dure, que penses tu de changer ici?

2021-09-20 14:16 UTC, manonpalin commented on tests/unit/helpers/bills.test.js
> +          startDate: moment().add(1, 'd').toISOString(),
Idem ici

2021-09-20 15:17 UTC, sophiemoustard commented on src/routes/bills.js
> +                  hours: Joi.number(),
que penses tu de laisser la condition `required` en conditionnel si `subscription` est present ?

2021-09-20 15:19 UTC, sophiemoustard commented on src/models/Event.js
> +        inclTaxes: Number,
idem type ? et que penses tu de les mettre en `required` ?

2021-09-20 15:22 UTC, KennyCallegari commented on src/helpers/bills.js
> +        const exclTaxesCustomer = draftBill.exclTaxes + (billedEvents[ev.event].exclTaxesCustomer || 0);
done

2021-09-20 15:29 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +      subscriptionsEvents.find(se => UtilsHelper.areObjectIdsEquals(se.event, eventId)));
je me demande si ce ne serait pas plus simple et plus exacte que tu ajoutes directement l'objet de l'evenement plutot que l'_id dans la methode `computeBillingInfoForEvents`
en plus ici tu ajoutes l'évenement avec les prix `inclTaxesCustomer` / `exclTaxesCustomer` qui correspondent a la souscription et non a l'article du coup

2021-09-20 15:30 UTC, KennyCallegari commented on tests/integration/seed/billsSeed.js
> +const billingItemList = [
Il me semble que notre convention c'est bien billingItemList, j'ai modifié les noms qui ne convenaient pas dans billsSeed

2021-09-20 15:31 UTC, KennyCallegari commented on tests/integration/seed/billsSeed.js
>        exclTaxes: 4,
done

2021-09-20 15:31 UTC, sophiemoustard commented on src/routes/preHandlers/bills.js
> +        ids.eventsIds.add(...customerBill.eventsList.map(ev => ev.event));
cette ligne est en commun pour les deux if, tu pourrais la sortir qu'en penses tu ?

2021-09-20 15:32 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +describe('formatBillingItemData #tag', () => {
done 😄

2021-09-20 15:32 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +        inclTaxesTpp: 5,
done

2021-09-20 15:35 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +          subscription: { _id: 'asd', service: { versions: [{ vat: 12, startDate: moment().toISOString() }] } },
done

2021-09-20 15:51 UTC, KennyCallegari commented on src/helpers/bills.js
> +        }].concat(get(billedEvents[ev.event], 'billingItems') || []);
Ah oui top !

2021-09-20 15:52 UTC, KennyCallegari commented on src/models/Event.js
> +        _id: { type: mongoose.Schema.Types.ObjectId, ref: 'BillingItem' },
done

2021-09-20 15:54 UTC, KennyCallegari commented on src/models/schemaDefinitions/billing.js
> +  events: Array,
done

2021-09-20 15:55 UTC, KennyCallegari commented on src/routes/bills.js
> +                  subscription: Joi.object(),
done

2021-09-20 15:56 UTC, KennyCallegari commented on src/routes/bills.js
> +                  }),
done

2021-09-20 15:59 UTC, KennyCallegari commented on src/routes/preHandlers/bills.js
> +    _id: { $in: [...ids.billingItemsIds] },
J'en ai besoin car ids.billingItemsIds n'est pas une array mais un Set()

2021-09-20 16:00 UTC, KennyCallegari commented on src/routes/bills.js
> +                  hours: Joi.number(),
done

2021-09-20 16:01 UTC, KennyCallegari commented on src/models/Event.js
> +        inclTaxes: Number,
done

2021-09-20 16:05 UTC, KennyCallegari commented on src/routes/preHandlers/bills.js
> +        ids.eventsIds.add(...customerBill.eventsList.map(ev => ev.event));
done

2021-09-20 16:38 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +      subscriptionsEvents.find(se => UtilsHelper.areObjectIdsEquals(se.event, eventId)));
bien vu, j'ai changé ça.
Du coup, le champ `inclTaxesCustomer` n'est plus requis dans la route

2021-09-21 07:17 UTC, manonpalin commented on src/helpers/bills.js
> +          exclTaxes: draftBill.unitInclTaxes / (1 + draftBill.vat / 100),
Ici au lieu de faire le calcul, tu pourrais utiliser le champ unitExclTaxes: 
```
exclTaxes: draftBill.unitExclTaxes
```

2021-09-21 07:25 UTC, manonpalin commented on src/helpers/bills.js
>          const eventBillingItems = [{
Que penses-tu d'ajouter ici : `const event = billedEvents[ev.event];` et de remplacer partout ou il faut ` billedEvents[ev.event]` par `event`, je trouve que ca allégerai un peu le code

2021-09-21 07:29 UTC, KennyCallegari commented on src/helpers/bills.js
> +          exclTaxes: draftBill.unitInclTaxes / (1 + draftBill.vat / 100),
done

2021-09-21 07:32 UTC, KennyCallegari commented on src/helpers/bills.js
>          const eventBillingItems = [{
done

2021-09-21 08:26 UTC, sophiemoustard requested changes
En base de donnée, j'ai 2 choses etranges : 
- quand un évènement est facturé je ne vois pas le champ `billingItems` dans la base
- coté facture, les champs `auxiliary` et `events` sont en format `string` dans `billingItemList.events`
<img width="967" alt="image" src="https://user-images.githubusercontent.com/24521863/134137736-32e3688c-2a58-40fa-a697-1a911c112773.png">

2021-09-21 08:26 UTC, sophiemoustard commented on src/routes/bills.js
> +                    exclTaxesCustomer: Joi.number(),
comme pour les autres, on pourrait mettre une condition sur le `required`

2021-09-21 08:35 UTC, sophiemoustard requested changes

2021-09-21 08:35 UTC, sophiemoustard commented on src/models/Event.js
> +        inclTaxes: { type: Number },
ces 3 champs sont en requis non ? si on a un article, il nous faut les 3 ?

2021-09-21 08:35 UTC, sophiemoustard commented on tests/integration/bills.test.js
> +      expect(billCount).toBe(1 + authBillList.length);
dans  ta verification, que penses tu de valider qu'on a bien une facture avec avec un champ billingItems ?

2021-09-21 08:35 UTC, sophiemoustard commented on tests/integration/bills.test.js
> +      expect(billCount).toBe(1 + authBillList.length);
et on pourrait verifier aussi que l'evenement a ete mis a jour avec bills.billingItems non ?

2021-09-21 08:37 UTC, sophiemoustard commented on src/models/schemaDefinitions/billing.js
> +  events: { type: Array },
il faudsrait preciser ce que tu as dans `events` non ?

2021-09-21 08:38 UTC, manonpalin approved these changes

2021-09-21 10:52 UTC, KennyCallegari commented on src/helpers/bills.js
> +exports.formatBillingItemData = bill => ({
Je ne vois pas trop l'intérêt de mutualiser le code sur les deux, j'ai l'impression qu'on ne peut que mutualiser très peu de logique entre les deux fonctions. Et même si leurs entrées / sorties respectives sont proches, la logique de la fonction est très différente.
Qu'en penses-tu ?

2021-09-21 10:53 UTC, KennyCallegari commented on src/routes/bills.js
> +                    exclTaxesCustomer: Joi.number(),
done

2021-09-21 10:55 UTC, KennyCallegari commented on src/models/Event.js
> +        inclTaxes: { type: Number },
done

2021-09-21 11:04 UTC, KennyCallegari commented on tests/integration/bills.test.js
> +      expect(billCount).toBe(1 + authBillList.length);
bien vu, done

2021-09-21 11:05 UTC, KennyCallegari commented on src/models/schemaDefinitions/billing.js
> +  events: { type: Array },
bien vu, le bug des champs `auxiliary` et `events` en format string dans `billingItemList.events` venait de là

2021-09-21 11:29 UTC, sophiemoustard commented on src/helpers/bills.js
> +exports.formatBillingItemData = bill => ({
l'intérêt était que si on fait un changement dans cette objet par la suite, on n'a qu'un seul endroit a changer et non deux 
je n'avais pas vraiment creusé pour valider la faisabilité, si c'est trop compliqué, tanpis

2021-09-21 11:54 UTC, sophiemoustard reviewed
pour preciser le 2eme bug : 
- quand je crée un facture avec un article relié a 18 interventions, seule une intervention a l'information bills.billingItem en base de données
- c'est un facture avec un financement donc 2 factures sont créées : une pour le bénéficiaire et une pour un tiers payeur

je pense que le bug vient d'un conflit entre les lignes 193 `eventsToUpdate = { ...eventsToUpdate, ...customerBillingInfo.billedEvents };` et 201 `eventsToUpdate = { ...eventsToUpdate, ...tppBillingInfo.billedEvents };`
-> les informations de la ligne 201 viennent ecraser les informations de l'évènement de la ligne 193

2021-09-21 12:40 UTC, KennyCallegari commented on src/helpers/bills.js
> +exports.formatBillingItemData = bill => ({
Ce n'est pas compliqué de regrouper les deux objets mais c'est moins compréhensible au niveau du code

2021-09-21 14:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +        }
que penses tu de revenir comme c'etait avant et changer plutot a la ligne 201 dnas la methode `formatAndCreateList` ?
```
for (const eventId of Object.keys(tppBillingInfo.billedEvents)) {
        if (!eventsToUpdate[eventId]) eventsToUpdate[eventId] = tppBillingInfo.billedEvents;
        else eventsToUpdate[eventId] = { ...eventsToUpdate[eventId], ...tppBillingInfo.billedEvents[eventId] };
}
```

2021-09-21 15:22 UTC, KennyCallegari commented on src/helpers/bills.js
> +        }
C'était bien : `if (!eventsToUpdate[eventId]) eventsToUpdate[eventId] = tppBillingInfo.billedEvents**[eventId]**;` dans ta solution que tu voulais marquer ?

2021-09-21 16:03 UTC, sophiemoustard approved these changes

2021-09-21 16:03 UTC, merged