COM-2362 dont save coursesmshitory if no sms sent
sophiemoustard/compani-api pull request #1618
Opened 2021-09-20 15:11 UTC by cmolle

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations : -np
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [ ] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES -np
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME -np
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES -np
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV -np
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : vendeur

- Périmetre roles : admin

- Cas d'usage : Lorsque j'envoie un sms j'ai l'historique seulement si au moins un sms s'est bien envoyé. 
Ex pour créer une erreur dans `helpers/sms send`: `await new Promise(setTimeout( { throw Boom.badRequest() }, 1000))`

2021-09-20 16:02 UTC, sophiemoustard requested changes
il faudrait peut etre renvoyer une erreur ou un message a l'utilisateur si aucun sms n'a ete evnoyé non ? parce que la c'est un peu perturbant : rien de s'envoie mais on a quand meme un message vert "tout est ok"... 🤔 

et il faut peut etre faire ca pour les autres endroits ou on peut envoyer des sms non ?

2021-09-20 16:49 UTC, cmolle commented
> il faudrait peut etre renvoyer une erreur ou un message a l'utilisateur si aucun sms n'a ete evnoyé non ? parce que la c'est un peu perturbant : rien de s'envoie mais on a quand meme un message vert "tout est ok"... 🤔
> 
> et il faut peut etre faire ca pour les autres endroits ou on peut envoyer des sms non ?

Que veux-tu dire par "il faut peut etre faire ca pour les autres endroits ou on peut envoyer des sms" ? 
Je crois qu'il n'y a qu'ici que l'on créé des historiques.

2021-09-21 14:46 UTC, sophiemoustard commented
> > il faudrait peut etre renvoyer une erreur ou un message a l'utilisateur si aucun sms n'a ete evnoyé non ? parce que la c'est un peu perturbant : rien de s'envoie mais on a quand meme un message vert "tout est ok"... 🤔
> > et il faut peut etre faire ca pour les autres endroits ou on peut envoyer des sms non ?
> 
> Que veux-tu dire par "il faut peut etre faire ca pour les autres endroits ou on peut envoyer des sms" ?
> Je crois qu'il n'y a qu'ici que l'on créé des historiques.

je me disais que si jamais il n'y a plus de credit, il ne faut peut etre pas dire a l'utilisateur que le SMS a ete envoyé et plutot lui afficher un message d'erreur
et donc faire ca aux autres endroits ou on envoie un sms

2021-09-22 14:52 UTC, ulysseferreira commented on src/helpers/courses.js
> +    throw Boom.badRequest(smsSentStatus[0].reason);
pourquoi smsSentStatus[0] ? c'est pas forcément le premier qui échoue ?

2021-09-22 14:55 UTC, cmolle commented on src/helpers/courses.js
> +    throw Boom.badRequest(smsSentStatus[0].reason);
Si on arrive ici, ils ont tous echoue. Du coup je me dis que si tous echoue il y a beaucoup de chance pour que ce soit pour une seule et meme raison. Tu en penses quoi ?

2021-09-22 15:31 UTC, ulysseferreira commented on src/helpers/courses.js
> +    throw Boom.badRequest(smsSentStatus[0].reason);
ah oui my bad

2021-09-22 15:55 UTC, sophiemoustard approved these changes

2021-09-22 15:55 UTC, sophiemoustard commented on src/helpers/courses.js
> +    throw Boom.badRequest(smsSentStatus[0].reason);
ca tient sur une ligne non ?

2021-09-22 16:09 UTC, merged