COM-2330 - Add TPP to bill pdf
sophiemoustard/compani-api pull request #1619
Opened 2021-09-21 08:48 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- ~~Tests intégrations~~:
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [ ] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### ~~FONCTIONNALITÉS APPS MOBILES~~
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### ~~MODIFICATIONS SUR LES MODÈLES~~
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### ~~CONSTANTES ET VARIABLE D'ENV~~
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : client

- Périmetre roles : admin / bénéficiaire

- Cas d'usage : 
Sur les factures où le tier payeur a payé une partie des frais, je vois une ligne décrivant le montant payé

Comment tester : 
- Tester sur un bénéficiaire sans tier payeur -> je ne vois pas la ligne
- Tester sur un bénéficiaire avec tier payeur -> je vois pas la ligne

2021-09-21 11:50 UTC, manonpalin commented on src/helpers/bills.js
> +    totalSubscription += volume * unitInclTaxes;
Que dis-tu de mettre cette ligne au dessus de `formattedDetails.push(....)` et d'utiliser la constante dans le champ total ?

2021-09-21 11:52 UTC, manonpalin commented on src/helpers/bills.js
> +  if (totalTPP) formattedDetails.push({ name: 'Participation du/des tier(s) payeur(s)', total: totalTPP });
Sophie suggérait plutot d'utiliser `Prise en charge du/des tiers(s) payeur(s)`

2021-09-21 12:16 UTC, manonpalin commented on src/helpers/bills.js
>    if (totalDiscount) formattedDetails.push({ name: 'Remises', total: -totalDiscount });
Je ne comprends pas ton calcul. Pour moi: 
- MontantBeneficiaire = MontantTTC - remises - montantTPP + majorations 
- Donc MontantTPP = MontantTTC - remises - montantBeneficiaire + majorations

Du coup ici on aurait plutot:  
```
const totalTPP = Number((bill.netInclTaxes - totalSubscription - totalBillingItem - totalDiscount + totalSurcharge)
     .toFixed(2));
```

2021-09-21 14:43 UTC, KennyCallegari commented on src/helpers/bills.js
> +    totalSubscription += volume * unitInclTaxes;
done

2021-09-21 14:43 UTC, KennyCallegari commented on src/helpers/bills.js
> +  if (totalTPP) formattedDetails.push({ name: 'Participation du/des tier(s) payeur(s)', total: totalTPP });
done

2021-09-21 15:41 UTC, cmolle commented on tests/unit/helpers/bills.test.js
> +      netInclTaxes: 440.46,
Pourquoi as-tu ajouté les champs netInclTaxes et discount ? Ic netInclTaxes devrait avoir la meme valeur que inclTaxes non ?

2021-09-21 15:41 UTC, cmolle commented on src/helpers/bills.js
> +  const totalTPP = Number((bill.netInclTaxes - totalSubscription - totalSurcharge - totalBillingItem + totalDiscount)
A-t-on besoin du Number ?

2021-09-21 15:41 UTC, cmolle commented on src/helpers/bills.js
> +  const totalTPP = Number((bill.netInclTaxes - totalSubscription - totalSurcharge - totalBillingItem + totalDiscount)
Est-ce qu'il ne faudrait pas plutot prendre la somme de ce qui doit etre payé par le tpp ? Ca devrait etre égale, mais si ca ne l'est pas, ca pourrait permetre de voir les erreurs, quen penses-tu ?

2021-09-22 07:34 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +      netInclTaxes: 440.46,
oui ! Je le défini car le calcul de `totalTPP` en a besoin

2021-09-22 07:35 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +      netInclTaxes: 440.46,
discount n'est pas utile mais je voulais le définir pour avoir des données cohérentes

2021-09-22 07:36 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const totalTPP = Number((bill.netInclTaxes - totalSubscription - totalSurcharge - totalBillingItem + totalDiscount)
la fonction toFixed(2) renvoie une string et les autres champs 'total' sont des nombres. Donc par soucis de cohérence je refais la conversion

2021-09-22 07:42 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const totalTPP = Number((bill.netInclTaxes - totalSubscription - totalSurcharge - totalBillingItem + totalDiscount)
On a envisagé cette solution avec Sophie mais pour récupérer cette somme, il n'y a pas de méthode simple car cette information n'est pas disponible immédiatement dans l'objet bill.
On avait envisagé de récupérer la facture du tier payeur associé mais il n'y a pas de façon 100% sûre pour la récupérer.
On s'est dit qu'on se pencherait sur cette solution plus tard et que pour l'instant on partait sur la solution que j'ai codé ici

2021-09-22 08:26 UTC, cmolle commented on tests/unit/helpers/bills.test.js
> +      netInclTaxes: 440.46,
Je pense que netInclTaxes et inclTaxes devrait avoir la meme valuer non ?

2021-09-22 08:30 UTC, KennyCallegari commented on tests/unit/helpers/bills.test.js
> +      netInclTaxes: 440.46,
oublie de push désolé !

2021-09-22 08:37 UTC, cmolle approved these changes

2021-09-22 09:22 UTC, sophiemoustard commented on src/helpers/bills.js
> +    .toFixed(2));
pourquoi as tu besoin du toFixed ?

2021-09-22 09:39 UTC, KennyCallegari commented on src/helpers/bills.js
> +    .toFixed(2));
A cause du problème sur les arrondis, lorsque totalTPP devrait valoir `0` il vaut en réalité `0.00000000004` et donc le `if()` ne fonctionne pas comme il devrait

2021-09-22 09:40 UTC, KennyCallegari commented on src/helpers/bills.js
> +    .toFixed(2));
`Number(0.00000000004.toFixed(2)) = 0.00`

2021-09-22 09:52 UTC, sophiemoustard requested changes

2021-09-22 09:52 UTC, sophiemoustard commented on src/helpers/bills.js
>    if (bill.billingItemList) {
pouquoi a-t-on besoin de ce if ?

2021-09-22 09:52 UTC, sophiemoustard commented on src/helpers/bills.js
>      }
ici il faut prendre en compte la remise des articles sinon le montant du tiers payeurs est faux
-> peut etre attendre la fusion de l'autre PR / rebase / puis corriger - je te laisse relancer Manon au besoin

2021-09-22 09:52 UTC, sophiemoustard commented on src/helpers/bills.js
> +    .toFixed(2));
que penses tu de faire comme suit ?
```
 const totalTPP = bill.netInclTaxes - totalSubscription - totalSurcharge - totalBillingItem + totalDiscount
if (Number(totalTPP).toFixed(2)) formattedDetails.push(
```

2021-09-22 14:12 UTC, KennyCallegari commented on src/helpers/bills.js
>    if (bill.billingItemList) {
oui car les factures tier payeurs n'ont pas ce champ

2021-09-22 14:55 UTC, manonpalin approved these changes

2021-09-22 15:47 UTC, sophiemoustard approved these changes

2021-09-22 15:47 UTC, merged