Com 2332
sophiemoustard/compani-api pull request #1623
Opened 2021-09-27 15:09 UTC by manonpalin

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations : -np
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [ ] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES -np
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME -np
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES -np
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV -np
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface :  client

- Périmetre roles : coach/aidant

- Cas d'usage :  Creation du service `numbers` et utilisation des méthodes de ce nouveau service dans le service `bill`

2021-09-27 15:43 UTC, sophiemoustard requested changes

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/bills.js
> +const NumberHelper = require('./numbers');
je pense que le standard c'est plutot Number**s**Helper

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/bills.js
> +  const unitExclTaxes = NumberHelper.dividedBy(bi.unitInclTaxes, addVat).toFixed(4);
pourquoi toFixed ? 
comme on l'utilise ensuite pour un calcul je pense qu'il vaut mieux ne pas modifier la "vraie" valeur

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/bills.js
> +  return subscription.unitInclTaxes;
tu peux passer une ligne avant le return

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/bills.js
> +  totalTPP = NumberHelper.add(totalTPP, totalSurchargeAndDiscount);
peux tu mettre ca sur une ligne pour pouvoir definir `totalTPP` en const et non let ?

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/bills.js
> +  const totalSurchargeAndDiscount = NumberHelper.substract(totalDiscount, totalSurcharge);
cette distinction me questionne dans le nommage : pour moi la partie totalSurcharge va dans la partie totalCustomer 🤔

2021-09-27 15:43 UTC, sophiemoustard commented on src/helpers/numbers.js
> +exports.dividedBy = (a, b) => Number(BigNumber(a).dividedBy(b));
pour suivre la logique de `multiply`, que penses tu de nommer cette fonction `divideBy` ?

2021-09-27 15:47 UTC, KennyCallegari commented on src/helpers/bills.js
> +      number.seq = NumberHelper.add(number.seq, 1);
ça n'est pas utile sur les entier non ?

2021-09-27 15:47 UTC, KennyCallegari commented on tests/unit/helpers/numbers.test.js
> +  });
`0.3*0.2` ne donne pas un resultat faux sur node, on pourrait faire le test avec `0.1*0.2` , qu'en penses-tu ?

2021-09-27 15:47 UTC, KennyCallegari commented on src/helpers/bills.js
>      formattedDetails.push({ name: 'Prise en charge du/des tiers(s) payeur(s)', total: totalTPP });
tu n'as plus besoin du `Number()` et du `toFixed(2)`, ici. C'était pour éviter un bug en attendant la correction bigNumber

2021-09-27 15:49 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const addVat = NumberHelper.add(1, vat);
Pareil : il n'y a pas de soucis pour ajouter un entier à un flottant, non ?

2021-09-27 17:00 UTC, manonpalin commented on src/helpers/bills.js
> +  const unitExclTaxes = NumberHelper.dividedBy(bi.unitInclTaxes, addVat).toFixed(4);
Pardon, je l'avais ajouté pour un test mais j'ai oublié de le retirer !

2021-09-28 06:52 UTC, manonpalin commented on src/helpers/bills.js
> +  const addVat = NumberHelper.add(1, vat);
Je me suis posee la question de changer ou non les additions lorsque c'est un entier. J'ai fait quelques recherches mais je ne trouve pas d'article dans lequel on parle de somme entre un entier et un flottant en javascript... 

Apres réflexion, je me dis que si il n'y a pas d'articles sur le sujet c'est qu'il n'y a pas de problème, du coup pour alléger un peu le code, que penses-tu si je repasse toutes les additions d'un entier en utilisant l'opérateur d'addition et d'affectation ?

2021-09-28 06:55 UTC, manonpalin commented on src/helpers/bills.js
> +  const totalSurchargeAndDiscount = NumberHelper.substract(totalDiscount, totalSurcharge);
Oui tu as raison 😃

2021-09-28 08:00 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const totalCustomer = NumbersHelper.add(NumbersHelper.add(totalSubscription, totalBillingItem), totalSurcharge);
Que penses-tu d'avoir une fonction avec des arguments infinis ?

```
(...nums) => {
  let result;
  for (const num of nums){
    Number(BigNumber(num).plus(result));
  }
  return result;
}
```

Ce qui permet de passer autant d'argument qu'on veut : `NumbersHelper.add(a, b)` ou `NumbersHelper.add(a, b, c, d, e, f)`

2021-09-28 08:01 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const totalCustomer = NumbersHelper.add(NumbersHelper.add(totalSubscription, totalBillingItem), totalSurcharge);
Même chose pour les autres fonctions

2021-09-28 08:05 UTC, sophiemoustard commented on src/helpers/bills.js
> +  const totalCustomer = NumbersHelper.add(NumbersHelper.add(totalSubscription, totalBillingItem), totalSurcharge);
tu peux meme mettre comme ca : 
`exports.add = (...nums) => nums.reduce((acc, n) => Number(BigNumber(acc).plus(n)), 0);`

2021-09-28 08:07 UTC, sophiemoustard commented on tests/unit/helpers/numbers.test.js
> +    const b = 1.2;
tu n'es pas obligé de definir les constantes ici tu peux mettre directement 
`const result = NumberHelper.add(0.6, 1.2);`
ce qui sera plus leger si tu changes le test pour accepter 4 ou 5 arguments (cf la proposition de Kenny pour accepter un nombre infini d'argument)

2021-09-28 08:12 UTC, KennyCallegari commented on src/helpers/bills.js
> +  const addVat = NumberHelper.add(1, vat);
Je n'ai pas trouvé d'article qui parlait de soucis de calcul entre un flottant et un entier non plus

2021-09-28 08:23 UTC, sophiemoustard commented on src/helpers/bills.js
> +  const totalCustomer = NumbersHelper.add(NumbersHelper.add(totalSubscription, totalBillingItem), totalSurcharge);
hum par rapport a ton "meme chose pour les autres fonctions" je pense que ca peut fonctionner pour la multiplication par contre je ne le ferai pas pour la soustraction et la division car l'ordre est important et je ne suis pas sure qu'il soit conservé

2021-09-28 08:24 UTC, sophiemoustard commented on src/helpers/bills.js
> +  const addVat = NumberHelper.add(1, vat);
pour les entiers je pense que tu peux garder la notation classique

2021-09-28 12:48 UTC, cmolle commented on src/helpers/numbers.js
> +exports.multiply = (a, b) => Number(BigNumber(a).multipliedBy(b));
Est-ce qu'il y a une difference entre `Number(BigNumber(...))` et `BigNumber(...).toNumber()` ? (J'ai l'impression que dans la doc ils parlent plutot de ToNumber)

2021-09-28 13:13 UTC, KennyCallegari commented on src/helpers/bills.js
> +      seq = NumbersHelper.add(seq, 1);
Pas besoin de `NumbersHelper.add` ici

2021-09-28 13:13 UTC, KennyCallegari commented on src/helpers/bills.js
> +      number.seq = NumbersHelper.add(number.seq, 1);
same

2021-09-28 13:13 UTC, KennyCallegari commented on src/helpers/bills.js
> +        if (bill.number) number.seq = NumbersHelper.add(number.seq, 1);
same

2021-09-28 13:13 UTC, KennyCallegari commented on src/helpers/bills.js
> +    { $set: { seq: NumbersHelper.add(billNumber.seq, 1) } }
same

2021-09-28 13:13 UTC, KennyCallegari commented on src/helpers/bills.js
> +    const tppParticipationRate = NumbersHelper.subtract(1, customerParticipationRate);
same ?

2021-09-28 13:25 UTC, manonpalin commented on src/helpers/numbers.js
> +exports.multiply = (a, b) => Number(BigNumber(a).multipliedBy(b));
Fondamentalement je ne sais pas vraiment quelle est la différence entre les deux. J'ai l'impression que la methode `.toNumber()` permet de ne convertir qu'un BigNumber en un Number tandis que Number() permet de convertir d'autres types, par ex des string en number. 
Tu as raison, comme on travaille avec des Big Number je pense que dans ce cas autant utiliser `.toNumber()`

2021-09-28 13:30 UTC, manonpalin commented on src/helpers/bills.js
> +    const tppParticipationRate = NumbersHelper.subtract(1, customerParticipationRate);
Dans ce cas il faut passer par la methode subtract car soustraire un flottant a 1 donne parfois un résultat inexacte. Par exemple 1 - 0.7 = 0.300000004

2021-09-28 13:45 UTC, sophiemoustard commented on tests/unit/helpers/numbers.test.js
> +describe('dividedBy', () => {
divide

2021-09-28 13:45 UTC, sophiemoustard commented on tests/unit/helpers/numbers.test.js
> +describe('subsdtract', () => {
oups

2021-09-28 13:45 UTC, cmolle commented on src/helpers/numbers.js
>  exports.divide = (a, b) => Number(BigNumber(a).dividedBy(b));
toNumber

2021-09-28 13:45 UTC, cmolle commented on src/helpers/numbers.js
>  exports.subtract = (a, b) => Number(BigNumber(a).minus(b));
idem

2021-09-28 13:47 UTC, sophiemoustard commented on src/helpers/bills.js
> +      );
je crois que tu peux simplifier en  :
```
const surchargePrice = NumbersHelper.multiply(
        duration,
        subscription.unitInclTaxes,
        NumbersHelper.divideBy(surcharge.percentage, 100)
      );
```

2021-09-28 14:06 UTC, sophiemoustard approved these changes

2021-09-28 14:09 UTC, KennyCallegari approved these changes

2021-09-28 14:16 UTC, cmolle approved these changes

2021-09-28 14:16 UTC, merged