COM-2357 docxtemplater new syntaxe
sophiemoustard/compani-api pull request #1634
Opened 2021-10-01 08:48 UTC by CorentinMartinot

nmp outdated :
<img width="439" alt="Capture d’écran 2021-10-01 à 10 33 46" src="https://user-images.githubusercontent.com/47056365/135591335-e4817d8f-d1b3-4585-8169-3203f11a4587.png">
 
On  attend d'être sûr.e de nous pour mettre a jour le driver mongo.
La maj de mongoose depend du driver.
La maj de mongoose-autopopulate depend de mongoose.

Rien a mettre a jour pour ce ticket donc.
---
Docxtemplater : 
en ajoutant des arguments au constructeur Docxtemplater, l'exectution du test bloque. Je n'ai pas reussi, a "stuber" l'instance de Docxtemplater (comme pour zippiz). J'ai l'impression que le constructeur de Docxtemplater n'est pas construit comme l'attend sinon.stub. jsp 😕 
J'ai donc séparé l'instanciation et le rendu de docxtemplater a part, pour pouvoir facilement mettre un stub. Qu'en pensez vous ?

2021-10-01 09:09 UTC, ulysseferreira reviewed
il faut pas mettre à jour qrcode ? je pense que tu peux quand même faire un rm -rf node_modules && rm package-lock.json && npm i

2021-10-01 10:25 UTC, ulysseferreira approved these changes

2021-10-01 10:55 UTC, ulysseferreira approved these changes

2021-10-04 12:44 UTC, sophiemoustard requested changes

2021-10-04 12:44 UTC, sophiemoustard commented on src/helpers/docx.js
>    const zip = new PizZip(file);
tu pourrais le mettre dans la methode `createDocxTemplater` qu'en penses tu ?

2021-10-04 12:57 UTC, sophiemoustard approved these changes

2021-10-04 14:50 UTC, ulysseferreira approved these changes

2021-10-04 14:54 UTC, merged