COM-2470 - Add virtual for mobile
sophiemoustard/compani-api pull request #1706
Opened 2021-11-12 11:45 UTC by KennyCallegari

Ajout des virtuals pour la requête mobile

2021-11-12 17:02 UTC, manonpalin approved these changes

2021-11-15 09:23 UTC, sophiemoustard requested changes

2021-11-15 10:37 UTC, KennyCallegari commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
C'est très étrange car il me semble que tu as raison et que c'est pour ça qu'on a fait une solution alternative sur outils. Mais en local / déployant la branche, je n'ai pas de soucis de performances 🤷‍♂️

2021-11-15 12:59 UTC, sophiemoustard commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
En fait cette methode n'est pas utilisé pour le planning. elle est utilisée dans les cas suivants : 
- agenda auxiliaire
- agenda bénéficiaire
- page des absences
- modale creation d'une absence
- onglet des contrats d'une auxiliaire

Je n'ai regardé que pour l'agenda auxiliaire mais on passe de 700ms a 5s ce qui me semble etre une grosse regression des performances qu'en penses tu ?

2021-11-15 14:14 UTC, KennyCallegari commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
Effectivement, j'ai le même comportement, j'ai changé ça.

Je me demande si on ne devrait pas mettre un commentaire car ce n'est pas la première fois qu'on ajoute les virtuals ici.
Et en codant j'avais en tête qu'on avait eu des problèmes avec ça mais je ne me suis pas souvenu du problème.
Qu'en penses-tu ?

2021-11-15 14:23 UTC, sophiemoustard commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
a quel niveau voudrais tu mettre les commentaires ?

2021-11-15 14:32 UTC, manonpalin commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
Est-ce que vous avez une idee de pourquoi est-ce que lorsque l'on ajoute ces deux virtuals dans la requête les performances se degradent ?  🤔 (sinon je me dis que ca pourrait être un sujet de veille )

2021-11-15 15:06 UTC, KennyCallegari commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
Mais ça pourrait être un bon sujet de veille : est-ce possible de créer des virtuals rapides (je pense au sujet d'indexation de Chloé qui peut être lié ?) ?

2021-11-15 15:24 UTC, sophiemoustard requested changes

2021-11-15 15:24 UTC, sophiemoustard commented on src/helpers/events.js
> +  // car celà créé des soucis de performances sur les plannings / agendas
pas de s a performance ni d'accents sur le a de cela

2021-11-15 15:25 UTC, sophiemoustard commented on src/repositories/EventRepository.js
> +  .populate({ path: 'endDateTimeStamp' })
en effet les index en bdd pourraient aider peut etre dans ce cas la

2021-11-15 16:02 UTC, sophiemoustard approved these changes

2021-11-15 16:02 UTC, merged