COM-2471 - Add isCancelled
sophiemoustard/compani-api pull request #1732
Opened 2021-11-30 16:10 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [x] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- ~~Si mes changements impactent l'application formation :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [x] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME
- [x] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [x] Je n'ai pas changé les droits de la route
  - [x] Je n'ai pas changé les droits dans le fichier rights.js
  - [x] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [x] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a: -np
- ~~J'ai supprimé une route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- ~~J'ai renommé une route :~~
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [x] J'ai géré le cas ou on ne l'envoie pas
- ~~J'ai rendu obligatoire un champs de la route :~~
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- ~~J'ai retiré un champ possible dans la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- ~~J'ai supprimé un retour/un champs du retour de la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### ~~MODIFICATIONS SUR LES MODÈLES~~
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - ~~[ ] J'ai ajouté le champ company ainsi que les preHooks associés~~
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - ~~J'ai ajouté un champ possible :~~
    - ~~[ ] J'ai géré le cas où l'application ne l'envoie pas~~
  - ~~J'ai rendu obligatoire un champs :~~
    - ~~[ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)~~
  - ~~J'ai retiré un champ possible :~~
    - ~~[ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas~~

### ~~CONSTANTES ET VARIABLE D'ENV~~
- ~~J'ai changé une constante :~~
  - ~~[ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)~~

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~

### POUR TESTER LA PR
- Périmetre interface : compani outils

- Périmetre roles : auxiliaire / admin / coach

- Cas d'usage : 
Ajout des champs dans la route de récupération des historiques d'un évènement.

2021-11-30 16:13 UTC, KennyCallegari commented on src/routes/eventHistories.js
> +            action: stringOrArray(EVENTS_HISTORY_ACTIONS),
J'ai corrigé un bug : on ne pouvait pas passer qu'une seule action dans ce champ et même si en front j'en passe 2, au moins c'est corrigé

2021-12-01 08:21 UTC, sophiemoustard requested changes

2021-12-01 08:21 UTC, sophiemoustard commented on src/helpers/eventHistories.js
> +      ...(query.isCancelled !== undefined && { isCancelled: false }),
tu pourrais mettre `...(get(query, 'isCancelled') && { isCancelled: false }),` qu'en penses tu ?

2021-12-01 08:21 UTC, sophiemoustard commented on src/routes/validations/utils.js
> +  valid
tu peux le mettre sur la ligne du dessus non ?

2021-12-01 08:21 UTC, sophiemoustard commented on tests/integration/eventHistories.test.js
> +  it('should return a list of event histories for one event', async () => {
ce titre est a changer non ?

2021-12-02 14:29 UTC, cmolle approved these changes

2021-12-02 15:40 UTC, cmolle approved these changes

2021-12-02 15:52 UTC, manonpalin approved these changes

2021-12-02 16:20 UTC, merged