COM-2516: send notification for new elearning course
sophiemoustard/compani-api pull request #1741
Opened 2021-12-08 14:46 UTC by ulysseferreira

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations : -np
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [ ] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- Si mes changements impactent l'application formation :
  - [x] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [x] Affichage des pages explorer/mes formations/About/CourseProfile
    - [x] Inscription a une formation e-learning
    - [x] Possibilité de faire une activité

- ~~Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME
- [x] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [x] Je n'ai pas changé les droits de la route
  - [x] Je n'ai pas changé les droits dans le fichier rights.js
  - [x] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [x] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - ~~Justification des breaking changes s'il y en a:~~
- ~~J'ai supprimé une route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- ~~J'ai renommé une route :~~
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
-~~ J'ai ajouté un champ possible dans la route :~~
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- ~~J'ai rendu obligatoire un champs de la route :~~
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- ~~J'ai retiré un champ possible dans la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- ~~J'ai supprimé un retour/un champs du retour de la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
- ~~J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : mobile formation

- Périmetre roles : tous

- Cas d'usage : quand une formation strictement elearning sans règle d'accès est ajouté, je reçois une notif sur l'appli mobile. 
⚠️ dans cette PR je ne peux que recevoir la notif, pas accéder à la formation en cliquant dessus ⚠️

2021-12-08 17:50 UTC, CorentinMartinot approved these changes

2021-12-09 07:55 UTC, sophiemoustard commented on src/helpers/notifications.js
> +  const trainees = await User.find({ formationExpoTokenList: { $exists: true } }).lean();
je crois que ici, tu peux requetes comme suit pour ne pas avoir a verifier `if (!get(trainee, 'formationExpoTokenList.length')) continue;`
```
{ formationExpoTokenList: { $exists: true }, $where: "this.formationExpoTokenList.length > 5" }
```

2021-12-09 08:03 UTC, sophiemoustard requested changes

2021-12-09 08:03 UTC, sophiemoustard commented on src/helpers/notifications.js
> +    .lean({ virtuals: true });
pourquoi as tu besoin du `virtuals: true` ?

2021-12-09 08:03 UTC, sophiemoustard commented on src/helpers/notifications.js
> +    .lean({ virtuals: true });
et j'ai l'impression qu'on peut se poser la meme question pour la methode d'au dessus

2021-12-09 09:19 UTC, ulysseferreira commented on src/helpers/notifications.js
> +  const trainees = await User.find({ formationExpoTokenList: { $exists: true } }).lean();
done

2021-12-09 09:24 UTC, ulysseferreira commented on src/helpers/programs.js
>      .find({ format: STRICTLY_E_LEARNING, $or: [{ accessRules: [] }, { accessRules: get(credentials, 'company._id') }] })
done

2021-12-09 09:24 UTC, ulysseferreira commented on src/helpers/subPrograms.js
> +    if (!payload.accessCompany) NotificationHelper.sendNewElearningCourseNotification(course._id);
done

2021-12-09 09:34 UTC, ulysseferreira commented on src/helpers/notifications.js
> +    .lean({ virtuals: true });
done

2021-12-09 09:34 UTC, ulysseferreira commented on src/helpers/notifications.js
> +  const trainees = await User.find({ formationExpoTokenList: { $exists: true } }).lean();
0 plutôt, non ? done sinon

2021-12-09 10:02 UTC, sophiemoustard commented on src/helpers/notifications.js
> +  const trainees = await User.find({ formationExpoTokenList: { $exists: true } }).lean();
ahah oui 0, j'avais fait le test en dbb avec 5 pour etre sur que ca fonctionnait

2021-12-09 10:10 UTC, sophiemoustard requested changes

2021-12-09 10:10 UTC, sophiemoustard commented on src/helpers/notifications.js
> +          body: `Rendez-vous dans l'onglet Explorer pour découvrir la nouvelle formation ${courseName}.`,
le texte n'est pas le meme que celui du ticket ; as tu validé ce changement avec Romain ?

2021-12-09 10:10 UTC, sophiemoustard commented on tests/unit/helpers/notifications.test.js
> +  it('should do nothing if trainee has no formationExpoTokenList', async () => {
il faudrait du coup changer le titre de ce describe du coup (et peut être un peu le contenu) car tu as enlevé le if du coup la on veut tester que si user.find nous rnvoie une liste vide, on ne fait rien. car avec le changement de requete que je t'ai proposé on a forcement des expoToken dans nos utilisateurs

2021-12-09 10:24 UTC, ulysseferreira commented on src/helpers/notifications.js
> +          body: `Rendez-vous dans l'onglet Explorer pour découvrir la nouvelle formation ${courseName}.`,
corrigé

2021-12-09 10:27 UTC, ulysseferreira commented on tests/unit/helpers/notifications.test.js
> +  it('should do nothing if trainee has no formationExpoTokenList', async () => {
done

2021-12-09 10:33 UTC, sophiemoustard approved these changes

2021-12-09 12:04 UTC, merged