COM-255ç: add issameorbefore luxon
sophiemoustard/compani-api pull request #1747
Opened 2021-12-10 15:42 UTC by ulysseferreira

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- ~~Si mes changements impactent l'application formation :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- ~~Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME -np
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
-~~ J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : vendeur/client

- Périmetre roles : coach/admin/rof/formateur

- Cas d'usage : remplacement de isSameOrBefore de moment par luxon : 
- Création de la fonction isSameOrBefore de luxon 
- modification de _formatMiscToCompaniDate (ajout de conditions)
 - dans moment, pour isSame et isSameOrBefore si les arguments sont undefined (c'est le cas dans les créneaux à planifier par exemple), moment considère que cela équivaut à la date à l'instant T. J'ai donc rajouter une condition si l'argument est undefined dans _formatMiscToCompaniDate pour que cela renvoie la date du moment. J'ai également modifier la condition sur les strings pour que cela renvoie un format invalid si la string est vide. En effet, dans moment, une string vide ou un null est considéré (à l'inverse de undefined) comme un argument non valide). Est-ce-que cela vous convient ?
- ajout de tests pour _formatMiscToCompaniDate et isSame
  - dans la continuité du point précédent j'ai rajouté un test pour _formatMiscToCompaniDate dans le cas où l'argument est undefined et j'ai fait de même pour la fonction isSame et isSameOrBefore en me basant sur le comportement de moment => dans moment cela renvoie false
  - Si vous validez ces changements, il faudra les mettre en place sur mobile

2021-12-13 09:28 UTC, CorentinMartinot commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return false if wrong argument', () => {
J'ai l'impression que ce test n'est pas propre a "isSame" mais a "formatMisc..." du coup je ne le mettrai pas ici, sinon on va tres vite tous melanger

2021-12-13 09:32 UTC, CorentinMartinot commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return false if wrong argument', () => {
meme remarque que plus haut

2021-12-13 10:01 UTC, ulysseferreira commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return false if wrong argument', () => {
il y a un test pour _formMisc si on a reçoit un mauvais argument mais là pour moi c'est un cas de figure un peu différent : si on reçoit un argument invalid, qu'est-ce-qu'on veut que ça renvoie ? false ? null ? une erreur ? c'est ça que ça vérifie

2021-12-13 10:02 UTC, ulysseferreira commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return false if wrong argument', () => {
cf réponse d'au-dessus

2021-12-14 13:19 UTC, CorentinMartinot commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return dateTime if arg is empty string', () => {
invalid

2021-12-14 13:32 UTC, ulysseferreira commented on tests/unit/helpers/dates/companiDates.test.js
> +  it('should return dateTime if arg is empty string', () => {
done

2021-12-14 15:51 UTC, CorentinMartinot commented on src/helpers/dates/companiDates.js
> +  isSameOrBefore(miscTypeOtherDate) {
tu peux rajouter cette methode dans les tests ligne 22

2021-12-14 16:18 UTC, ulysseferreira commented on src/helpers/dates/companiDates.js
> +  isSameOrBefore(miscTypeOtherDate) {
done

2021-12-15 11:02 UTC, sophiemoustard requested changes

2021-12-15 11:07 UTC, ulysseferreira commented on tests/unit/helpers/dates/companiDates.test.js
> +describe('MANIPULATE', () => {
done

2021-12-15 11:19 UTC, sophiemoustard commented on src/routes/preHandlers/courseSlot.js
>  const checkPayload = async (courseId, payload) => {
en fait en relisant le code, je me demande pourquoi on fais les verifications sur les dates ici et pas dans le route directement ? 🤔

2021-12-15 12:42 UTC, ulysseferreira commented on src/helpers/dates/companiDates.js
> +  isSameOrBefore(miscTypeOtherDate) {
done

2021-12-15 15:16 UTC, sophiemoustard approved these changes

2021-12-15 15:16 UTC, merged

2021-12-15 15:16 UTC, sophiemoustard commented on src/routes/preHandlers/courseSlot.js
>  const checkPayload = async (courseId, payload) => {
vue  ensemble, pas possible de faire le sameday sur la route