Com 2553
sophiemoustard/compani-api pull request #1753
Opened 2021-12-15 15:12 UTC by manonpalin

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [ ] J'ai bien fait les tests
  - C'est une ancienne route utilisée par une des apps mobiles
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- Si mes changements impactent l'application formation :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
    - [ ] Inscription a une formation e-learning
    - [ ] Possibilité de faire une activité

- Si mes changements impactent l'application erp :
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME
- [ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [ ] Je n'ai pas changé les droits de la route
  - [ ] Je n'ai pas changé les droits dans le fichier rights.js
  - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - Justification des breaking changes s'il y en a:
- J'ai supprimé une route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- J'ai renommé une route :
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- J'ai ajouté un champ possible dans la route :
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- J'ai rendu obligatoire un champs de la route :
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- J'ai retiré un champ possible dans la route :
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- J'ai supprimé un retour/un champs du retour de la route :
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES
- J'ai ajouté un modèle spécifique à une structure:
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- J'ai changé un modèle utilisé par l'app mobile:
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
- J'ai changé une constante :
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
-  Périmetre interface :  client 

- Périmetre roles : Auxiliaire/Coach/Admin

- Cas d'usage : Je peux supprimer une absence beneficiaire.

2021-12-15 16:54 UTC, KennyCallegari commented on src/routes/preHandlers/customerAbsences.js
> +  const customerAbsence = await CustomerAbsence.countDocuments({ _id: req.params._id, company: companyId }).lean();
pas besoin de `lean()`

2021-12-16 07:44 UTC, sophiemoustard requested changes

2021-12-16 07:44 UTC, sophiemoustard commented on tests/integration/customerAbsences.test.js
> +        url: `/customerabsences/${new ObjectID()}`,
ici tu pourrais faire le test en utilisant l'id d'une absence d'une autre structure plutot :)
dans la realité : 
- si jamais on casse le code et qu'on oublie de verifier que l'absence existe bien en BDD (_id: params._id), qu'elle n'existe pas et qu'on tente de la supprimer, au pire ce n'est pas grave car il n'y a pas d'impact
- par contre si on casse le code et qu'on oublie de verifier la structure (company: companyId), que quelqu'un s'une autre structure tente de supprimer cette absence et qu'il y arrive, c'est vraiment génant

donc si tu ne veux faire qu'un test, il vaut mieux faire l'autre :)

2021-12-16 08:18 UTC, manonpalin commented on tests/integration/customerAbsences.test.js
> +        url: `/customerabsences/${new ObjectID()}`,
C'est rectifié :)

2021-12-16 08:40 UTC, sophiemoustard approved these changes

2021-12-16 09:42 UTC, KennyCallegari approved these changes

2021-12-16 09:42 UTC, merged