Com 2580
sophiemoustard/compani-api pull request #1763
Opened 2021-12-21 16:25 UTC by ulysseferreira

|  |  | TESTS  :computer: | |
|----------|----------|----------|----------|
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>

---

|  |  | POINTS D'ATTENTION POUR CETTE PR  :warning:  | |
|----------|----------|----------|----------|
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai fait des modifications sur une route utilisée sur plusieurs plateformes | [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai modifié un modèle utilisé en mobile | [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai ajouté un modèle spécifique à une structure | <ul><li>[ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile |  <ul><li>[ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai ajouté une variable d'environnement | <ul><li>[ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites</li></ul>

---

|  |  |  FONCTIONNALITÉS APPS MOBILES  :iphone: | |
|----------|----------|----------|----------|
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | Mes changements impactent l'application formation | <ul><li>[ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | Mes changements impactent l'application erp | <ul><li>[ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours</li></ul>

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : tous

- Cas d'usage : mise à jour de mongDB et mongoose

- Comment tester ? : 
- s'assurer que la webapp fonctionne (en priorité planning, facturation, paie, interface auxiliaire, interface aidant, tableau des formations)
- s'assurer que les app mobiles fonctionnent

Si tu as lu cette description, pense a réagir avec un :eye:

2021-12-23 08:15 UTC, sophiemoustard requested changes

2021-12-23 08:15 UTC, sophiemoustard commented on tests/integration/seed/eventsSeed.js
> +    startDate: '2019-01-16T17:58:15.519Z',
pourquoi cet ajout ?

2021-12-23 08:34 UTC, cmolle commented on src/repositories/EventRepository.js
> +    { $sort: { 'events.startDate': 1 } },
Parce que dans `getPaidTransportStatsBySector` on suppose que les evenements sont tries, ce qui n'etait pas toujours le cas. Je n'ai pas l'impression que mongo ait changé ca facon de trier (dans les changelogs, ils parlent de la facon de valider les parametres du tri mais pas le tri j'ai l'impression) mais les tests cassaient une fois de temps en temps.

2021-12-23 08:35 UTC, cmolle commented on tests/integration/seed/eventsSeed.js
> +    startDate: '2019-01-16T17:58:15.519Z',
Ca faisait partie de mes tests pour comprendre prouquoi les tests cassaient. un moment je pensais que ca pouvait venir d'une mauvaise timezone. Finalement non mais je me suis dit que c'etait plutot une bonne pratique d'indiquer la timezone dans les heures des seeds pour eviter des incoherences. Qu'en penses-tu ?

2021-12-23 11:00 UTC, CorentinMartinot approved these changes

2021-12-23 13:38 UTC, cmolle commented on src/repositories/EventRepository.js
> +    { $sort: { 'events.startDate': 1 } },
Vu ensemble au daily : j'ai modifié le tri pour qu'il soit plutot hors de l'aggregation

2021-12-23 17:16 UTC, CorentinMartinot commented on tests/integration/seed/activitiesSeed.js
> -  { _id: new ObjectId(), name: 'fumer', type: 'video', cards: [cardsList[0]._id, cardsList[6]._id, cardsList[7]._id] },
pk tu as supprimé cette carte ?

2021-12-23 17:28 UTC, CorentinMartinot commented on tests/unit/helpers/dates.test.js
> +    const result = DatesHelper.descendingSort('date')({ date: '2020-12-01' }, { date: '2021-01-01' });
une date ISO c mieux non ?

2021-12-24 10:07 UTC, CorentinMartinot commented on tests/unit/helpers/dates.test.js
> +    const result = DatesHelper.descendingSort('date')({ date: '2020-12-01' }, { date: '2021-01-01' });
done

2021-12-24 15:24 UTC, sophiemoustard approved these changes

2021-12-24 15:24 UTC, merged