Com 2613
sophiemoustard/compani-api pull request #1779
Opened 2022-01-14 11:09 UTC by ulysseferreira

|  |  | TESTS  :computer: | |
|----------|----------|----------|----------|
| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>

---

|  |  | POINTS D'ATTENTION POUR CETTE PR  :warning:  | |
|----------|----------|----------|----------|
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai fait des modifications sur une route utilisée sur plusieurs plateformes | [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai modifié un modèle utilisé en mobile | [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai ajouté un modèle spécifique à une structure | <ul><li>[ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile |  <ul><li>[ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai ajouté une variable d'environnement | <ul><li>[ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites</li></ul>

---

|  |  |  FONCTIONNALITÉS APPS MOBILES  :iphone: | |
|----------|----------|----------|----------|
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | Mes changements impactent l'application formation | <ul><li>[ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours</li></ul>
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | Mes changements impactent l'application erp | <ul><li>[ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours</li></ul>

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur/client

- Cas d'usage : rof/coach/client-admin/vendor-admin

- Comment tester ? : dans le suivi d'une formation, j'affiche les émargements non prévus dans d'autres formations
TESTS : 
FORMATION INTER_B2B
- prendre 2 apprenant (un alenvi, un d'une autre structure) et les émarger dans une autre formation ayant le même sous-programme
- je vois ces émargements côté vendeur
- côté client je ne vois que les émargements de l'apprenant alenvi

FORMATION INTRA
- émarger un des apprenant dans une autre formation ayant le même sous-programme
- je vois ces émargements côté vendeur et côté client

en tant que formateur de la formation je vois ces émargements non prévus

Si tu as lu cette description, pense a réagir avec un :eye:

2022-01-14 15:23 UTC, manonpalin commented on src/helpers/attendances.js
> +      const { attendances } = s;
Que penses-tu de renommer a en attendante eeew s en slot? Je trouve que ca rend l'ensemble plus lisible

2022-01-14 16:40 UTC, ulysseferreira commented on src/helpers/attendances.js
> +      const { attendances } = s;
corrigé pour slot, j'ai laissé a pour attendance sinon ça fait des lignes trop longues et c'est encore moins lisible

2022-01-17 08:27 UTC, manonpalin commented on tests/integration/seed/attendancesSeed.js
> +  { // 6 trainer is authTrainer
Petite coquille: //7

2022-01-17 09:23 UTC, ulysseferreira commented on tests/integration/seed/attendancesSeed.js
> +  { // 6 trainer is authTrainer
j'ai l'impression qu'il est même pas utile ce seed

2022-01-17 09:42 UTC, sophiemoustard requested changes

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +    .populate({
pour le format, je pense que c'est plus comme suit 
```
await Course
    .find({ format: BLENDED, subProgram: { $in: get(course, 'subProgram.program.subPrograms') } })
    .populate({
```

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +    })
sur une ligne

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +  const courseWithSameSubProgramList = await Course.find({
on ne sait pas trop a quoi fait reference le `list` dans ce nom... et il me semble que c'est plutot la liste des formations avec le même programme non ?
que penses tu de `coursesWithSameProgram` ?

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +const formatCourseWithAttendances = (courseWithSameSubProgram, course, companyId) => {
idem ici c'est plus courseWithSameProgram ?

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +    const { attendances } = slot;
et que penses tu de formater comme suit ?
```
const formatCourseWithAttendances = (course, trainees, companyId) => course.slots.map((slot) => {
  const { attendances } = slot;
  if (!attendances) return {};

  return attendances.filter((a) => {
```

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +    return attendances.filter((a) => {
pour plus de lisibilité tu pourrais mettre le `filter` a la ligne

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +const formatCourseWithAttendances = (courseWithSameSubProgram, course, companyId) => {
et comme tu n'as besoin que des apprenants de ton `course`, que penses tu de ne passer que `course.trainees` a cette methode pour avoir comem argument : `course` (tu peux renommer `courseWithSameSubProgram` en `course` si tu changes le 2nd argument), `trainees` et `companyId` ?

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +      const traineeSubscribedOnlyToSpecificCourse = UtilsHelper.doesArrayIncludeId(course.trainees, a.trainee._id) &&
je ne comprends pas bien ce nom.. que penses tu de `attendanceInOtherCourse` ?

2022-01-17 09:42 UTC, sophiemoustard commented on src/helpers/attendances.js
> +      const traineeIsInSpecificCompany = (!companyId || UtilsHelper.areObjectIdsEquals(a.trainee.company, companyId));
idem je ne comprends pas ton specific...

2022-01-17 09:42 UTC, sophiemoustard commented on src/models/CourseSlot.js
> +});
sur une ligne

2022-01-17 09:59 UTC, ulysseferreira commented on src/helpers/attendances.js
> +    .populate({
done

2022-01-17 10:00 UTC, ulysseferreira commented on src/helpers/attendances.js
> +    })
done

2022-01-17 10:00 UTC, ulysseferreira commented on src/helpers/attendances.js
> +  const courseWithSameSubProgramList = await Course.find({
done

2022-01-17 10:03 UTC, ulysseferreira commented on src/helpers/attendances.js
> +const formatCourseWithAttendances = (courseWithSameSubProgram, course, companyId) => {
done

2022-01-17 10:04 UTC, ulysseferreira commented on src/helpers/attendances.js
> +    const { attendances } = slot;
done

2022-01-17 10:05 UTC, ulysseferreira commented on src/helpers/attendances.js
> +    return attendances.filter((a) => {
done

2022-01-17 10:31 UTC, ulysseferreira commented on src/helpers/attendances.js
> +      const traineeSubscribedOnlyToSpecificCourse = UtilsHelper.doesArrayIncludeId(course.trainees, a.trainee._id) &&
c'est un booléen ici, on a pas trop cette info dans attendanceInOtherCourse et il faut aussi qu'on ait l'info comme quoi l'apprenant n'est pas inscrit dans les autres formations dans lesquelles il émarge

2022-01-17 10:33 UTC, ulysseferreira commented on src/helpers/attendances.js
> +      const traineeIsInSpecificCompany = (!companyId || UtilsHelper.areObjectIdsEquals(a.trainee.company, companyId));
l'apprenant appartient à la company de la course dans laquelle on se trouve (s'il y en a une)

2022-01-17 10:34 UTC, ulysseferreira commented on src/models/CourseSlot.js
> +});
done

2022-01-17 13:56 UTC, sophiemoustard commented on src/helpers/attendances.js
> +      const traineeIsInSpecificCompany = (!companyId || UtilsHelper.areObjectIdsEquals(a.trainee.company, companyId));
en fait c'est le `specific` que je ne comprends pas, comme dans ton autre nommage

2022-01-17 14:28 UTC, manonpalin approved these changes

2022-01-17 15:46 UTC, sophiemoustard requested changes

2022-01-17 15:46 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance', () => {
pourquoi ce changement ?

2022-01-17 15:46 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance/unsubscribed', () => {
il manque un s a la route

2022-01-17 15:46 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance/unsubscribed', () => {
c;est normal qu'il n'y ait pas la section other role ?

2022-01-17 15:54 UTC, sophiemoustard commented on src/helpers/attendances.js
> +      const traineeSubscribedOnlyToSpecificCourse = UtilsHelper.doesArrayIncludeId(course.trainees, a.trainee._id) &&
hum je me suis un peu pris la tete sur ces nommages... peut etre que pour etre clair, il faut renommer `trainees` en `specificCourseTrainees` non ?

2022-01-17 15:54 UTC, sophiemoustard commented on src/helpers/attendances.js
> +      const traineeIsInSpecificCompany = (!companyId || UtilsHelper.areObjectIdsEquals(a.trainee.company, companyId));
idem Ici, `specificCourseCompany`?

2022-01-17 16:21 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance', () => {
oups erreur

2022-01-17 16:22 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance/unsubscribed', () => {
done

2022-01-17 16:24 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +describe('ATTENDANCES ROUTES - GET /attendance/unsubscribed', () => {
corrigé

2022-01-18 10:07 UTC, ulysseferreira commented on src/helpers/attendances.js
> +      const traineeSubscribedOnlyToSpecificCourse = UtilsHelper.doesArrayIncludeId(course.trainees, a.trainee._id) &&
done

2022-01-18 10:07 UTC, ulysseferreira commented on src/helpers/attendances.js
> +      const traineeIsInSpecificCompany = (!companyId || UtilsHelper.areObjectIdsEquals(a.trainee.company, companyId));
done

2022-01-18 11:24 UTC, sophiemoustard approved these changes

2022-01-18 11:24 UTC, merged