COM-2615: return presence progress
sophiemoustard/compani-api pull request #1801
Opened 2022-01-27 15:10 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration -np
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [x] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [x] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] ~~J'ai modifié un modèle utilisé en mobile [Slite de détail]~~(https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] ~~J'ai ajouté un modèle spécifique à une structure~~
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] ~~J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile~~
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] ~~Mes changements impactent l'application formation~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] ~~Mes changements impactent l'application erp~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur/client admin_vendeur/admin_client/coach/rof

- Cas d'usage : je peux visualiser les présences dans les formations suivies sur le profil d'un apprenant

- Comment tester ? : voir webapp + s'assurer qu'on a rien casser : sur les progression de l'app mobile + sur le profil d'une formation mixte/elearning

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-01-27 17:31 UTC, CorentinMartinot commented on src/helpers/steps.js
> +  let attendanceDuration = 0;
pq ne pas utiliser un reducer ?
tu peux faire quasiment comme `UtilsHelper.getTotalDurationForExport()`

2022-01-27 17:35 UTC, CorentinMartinot commented on tests/unit/helpers/courses.test.js
> +      type: E_LEARNING,
pourquoi tu as changé ici ?

2022-01-27 17:43 UTC, CorentinMartinot commented on src/helpers/steps.js
>      : liveProgress;
comme on va tester derriere, on pourrait remplacer moment.js (ligne 32) par companiDate, qu'en pense tu ?

2022-01-27 17:51 UTC, CorentinMartinot commented on tests/unit/helpers/courses.test.js
> +      progress: { live: 1, presence: { attendanceDuration: 120, maxDuration: 180 } },
pourquoi modifier ce test ?
tu rajouter la meme chose que dans le test d'avant, du coup je vois pas ce que tu testes en plus. 
Si tu testes rien en plus, il vaut mieux ne pas encombrer le code. T'en dis quoi ?

2022-01-27 18:02 UTC, CorentinMartinot commented on src/helpers/steps.js
> +  return { attendanceDuration, maxDuration };
tu as choisis de retourner un nombre de minutes. 
On a eu une discussion une fois sur les durées exprimées en entier (c t en milisecondes mais le pb est le meme) et je crois qu'on avait tranché  pour une utilisation des "ObjectDuration" genre { minutes: xxx }.

Cependant, c'est pas si claire ici : 
  => en front, on a pas luxon et moment n'a pas de parseur pour les "objectDurations" (c'est pas bien compliquer de bricoler qqc non plus)
  
du coup on a le choix entre 2 formats:
   - objectduration (et on bidouille en front en attendant luxon)
   - format ISO pour les durées

que pense tu de ma remaque ? si tu est d'accord pour abondonner les entiers, quel format verrais tu a la place ?

Ca implique de modifier aussi

2022-01-28 09:37 UTC, ulysseferreira commented on src/helpers/steps.js
> +  return { attendanceDuration, maxDuration };
les objectduration ça me semble bien, ça modifie pas trop trop le code (un peu relou au niveau de l'accumulateur mais ça va et ça sera plus proche de ce qu'on aura ensuite pour luxon

2022-01-28 10:28 UTC, ulysseferreira commented on src/helpers/steps.js
> +  let attendanceDuration = 0;
done

2022-01-28 10:28 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +      type: E_LEARNING,
pour être cohérent avec le nom du test car quand on est sur un créneau présentiel y a forcément 2 progression : live et  presence

2022-01-28 10:57 UTC, ulysseferreira commented on src/helpers/steps.js
>      : liveProgress;
done

2022-01-28 10:58 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +      progress: { live: 1, presence: { attendanceDuration: 120, maxDuration: 180 } },
c'est juste pour être consistant et coller à la réalité vu que dans les faits t'auras pas de live sans presence

2022-01-28 13:58 UTC, CorentinMartinot commented on src/helpers/courses.js
> +    .reduce((acc, value) => ({
pq ne pas utiliser la factory  ? Alors, comme il faut sortir un format "objet" a la fin, je verrai deux reducer :

```
const combinedPresenceProgress = {
     attendanceDuration: presenceProgressSteps
        .reduce((acc, step) => acc.add(step.progress.presence.attendanceDuration), companiDuration()).toObject(),
     maxDuration: presenceProgressSteps
        .reduce((acc, step) => acc.add(step.progress.presence.maxDuration), companiDuration()).toObject()
}

Je trouve que meme si on parcours deux fois la boucle, c plus facile a lire que le ruducer unique

Et il faut ajouter .toObject() a companiDuration.

2022-01-28 13:59 UTC, CorentinMartinot commented on src/helpers/steps.js
> +    .reduce((acc, value) => ({
same, je verrai bien une utilisation de companiDuration ici

2022-01-28 14:03 UTC, CorentinMartinot commented on tests/unit/helpers/courses.test.js
> +      progress: { live: 1, presence: { attendanceDuration: 120, maxDuration: 180 } },
ok

2022-01-28 14:41 UTC, ulysseferreira commented on src/helpers/courses.js
> +    .reduce((acc, value) => ({
done

2022-01-28 15:04 UTC, ulysseferreira commented on src/helpers/steps.js
> +    .reduce((acc, value) => ({
done

2022-01-28 15:19 UTC, CorentinMartinot commented on src/helpers/steps.js
> +          : acc.add({ minutes: 0 })),
pq pas juste `: acc,` a quoi ca sert d'ajouter 0 ?

2022-01-28 16:56 UTC, ulysseferreira commented on src/helpers/steps.js
> +          : acc.add({ minutes: 0 })),
si jamais il n'y a aucun créneaux émargés ça ne renvoie pas {minutes: 0} mais {}

2022-01-31 14:20 UTC, sophiemoustard requested changes

2022-01-31 14:20 UTC, sophiemoustard commented on src/helpers/courses.js
> +        .reduce((acc, step) => acc.add(step.progress.presence.attendanceDuration), CompaniDuration()).toObject(),
tu pourrais avoir un methode `computeDuration` pour faire ce calcul qu'en penses tu ?

2022-01-31 14:20 UTC, sophiemoustard commented on src/helpers/steps.js
> +      CompaniDuration({ minutes: 0 }))
au niveau du format, je pense que c'est plutot comme ca : 
```
.reduce(
        (acc, slot) => (slot.attendances.length
          ? acc.add(CompaniDate(slot.endDate).diff(slot.startDate, 'minutes'))
          : acc),
        CompaniDuration({ minutes: 0 })
)
```

2022-01-31 15:16 UTC, ulysseferreira commented on src/helpers/steps.js
> +      .getPresenceStepProgress(slots.filter(slot => UtilsHelper.areObjectIdsEquals(slot.step._id, step._id))),
done

2022-01-31 15:23 UTC, ulysseferreira commented on src/helpers/courses.js
> +        .reduce((acc, step) => acc.add(step.progress.presence.attendanceDuration), CompaniDuration()).toObject(),
done

2022-01-31 15:36 UTC, ulysseferreira commented on src/helpers/steps.js
> +      CompaniDuration({ minutes: 0 }))
done

2022-01-31 17:15 UTC, sophiemoustard commented on src/helpers/steps.js
> +        .getPresenceStepProgress(stepSlotList),
sur une ligne a chaque fois

2022-02-01 08:57 UTC, merged