Com 2646
sophiemoustard/compani-api pull request #1809
Opened 2022-02-02 17:57 UTC by CorentinMartinot

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur / rof

- Cas d'usage : je peux supprimer les financeur

- Comment tester ? : voir webapp

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-02-03 09:54 UTC, ulysseferreira commented on src/helpers/translate.js
> +    courseFundingOrganisationDelected: 'Course funding organisation deleted.',
*deleted

2022-02-03 09:54 UTC, ulysseferreira commented on src/helpers/translate.js
> +    courseFundingOrganisationDelected: 'Financeur supprimé.',
idem

2022-02-03 09:54 UTC, ulysseferreira commented on tests/integration/courseFundingOrganisations.test.js
> +describe('COURSE FUNDING ORGANISATION ROUTES - DELETE /coursefundingorganisation #tag', () => {
#tag

2022-02-03 10:06 UTC, ulysseferreira commented on src/routes/preHandlers/courseFundingOrganisation.js
>    const nameAlreadyExists = await CourseFundingOrganisation.countDocuments({ name }, { limit: 1 });
pour gérer la case tu peux faire 
```
await CourseFundingOrganisation.countDocuments({ name: new RegExp(`^${name}$`, 'i') });
```

2022-02-03 10:58 UTC, CorentinMartinot commented on src/routes/preHandlers/courseFundingOrganisation.js
>    const nameAlreadyExists = await CourseFundingOrganisation.countDocuments({ name }, { limit: 1 });
oui mais c lourd en calcul

2022-02-03 11:00 UTC, CorentinMartinot commented on src/helpers/translate.js
> +    courseFundingOrganisationDelected: 'Course funding organisation deleted.',
doen

2022-02-03 11:00 UTC, CorentinMartinot commented on src/helpers/translate.js
> +    courseFundingOrganisationDelected: 'Financeur supprimé.',
done

2022-02-03 11:01 UTC, CorentinMartinot commented on tests/integration/courseFundingOrganisations.test.js
> +describe('COURSE FUNDING ORGANISATION ROUTES - DELETE /coursefundingorganisation #tag', () => {
done

2022-02-03 11:44 UTC, ulysseferreira approved these changes

2022-02-03 16:08 UTC, sophiemoustard requested changes

2022-02-03 16:08 UTC, sophiemoustard commented on src/routes/courseFundingOrganisations.js
> +        pre: [{ method: authorizeCourseFundingOrganisationDelete }],
Deletion* sinon ce n'est pas tres anglais

2022-02-03 16:08 UTC, sophiemoustard commented on tests/integration/courseFundingOrganisations.test.js
> +describe('COURSE FUNDING ORGANISATION ROUTES - DELETE /coursefundingorganisation', () => {
il manque un *s* a `/coursefundingorganisations`

2022-02-04 09:34 UTC, sophiemoustard approved these changes

2022-02-04 09:42 UTC, merged