COM-2665: create and list billing item
sophiemoustard/compani-api pull request #1813
Opened 2022-02-08 17:09 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] ~~J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)~~
- [ ] ~~J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)~~
- [ ] ~~J'ai ajouté un modèle spécifique à une structure~~
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] ~~J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile~~
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] ~~Mes changements impactent l'application formation~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] ~~Mes changements impactent l'application erp~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur admin/rof

- Cas d'usage : je peux ajouter un article de facturation

- Comment tester ? :
  - ajouter un article de facturation
  - essayer de le réajouter => 409 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-02-09 10:43 UTC, CorentinMartinot commented on src/models/CourseFundingOrganisation.js
> +formatQueryMiddlewareList().map(middleware => CourseFundingOrganisationSchema.pre(middleware, formatQuery));
C'est pour eviter les injections de code c'est ca ?

2022-02-09 10:57 UTC, CorentinMartinot commented on src/models/CourseBillingItem.js
> +const CourseBillingItemSchema = mongoose.Schema({
il y a pas un truc ajouter des le script de dump ?

2022-02-09 11:16 UTC, ulysseferreira commented on src/models/CourseFundingOrganisation.js
> +formatQueryMiddlewareList().map(middleware => CourseFundingOrganisationSchema.pre(middleware, formatQuery));
non c'est suite à la MAJ Mongo pour transformer les `field: {subField: value}` en `field.subField: value` parce que dans la nouvelle version de mongo quand tu écrit sous forme objet faut respecter l'ordre des champs et tous les mettre alors qu'en string tu peux faire comme avant

2022-02-09 11:19 UTC, ulysseferreira commented on src/models/CourseBillingItem.js
> +const CourseBillingItemSchema = mongoose.Schema({
bien vu j'ouvre une PR script

2022-02-09 14:22 UTC, CorentinMartinot approved these changes

2022-02-09 14:22 UTC, CorentinMartinot commented on src/models/CourseFundingOrganisation.js
> +formatQueryMiddlewareList().map(middleware => CourseFundingOrganisationSchema.pre(middleware, formatQuery));
ah ok ! merci bcp

2022-02-09 14:23 UTC, CorentinMartinot commented on src/models/CourseBillingItem.js
> +const CourseBillingItemSchema = mongoose.Schema({
ok merci !

2022-02-10 08:16 UTC, sophiemoustard requested changes

2022-02-10 08:16 UTC, sophiemoustard commented on src/helpers/translate.js
> +    courseBillingItemExists: 'Course billing item exists',
il manque un .

2022-02-10 08:16 UTC, sophiemoustard commented on src/models/CourseFundingOrganisation.js
> +formatQueryMiddlewareList().map(middleware => CourseFundingOrganisationSchema.pre(middleware, formatQuery));
bien vu !

2022-02-10 08:16 UTC, sophiemoustard commented on tests/integration/helpers/authentication.js
> +const CourseBillingItem = require('../../../src/models/CourseBillingItem');
tu peux les mettre plus haut par ordre alphabétique avec les autres pour qu'on y voit plus clair

2022-02-10 09:29 UTC, ulysseferreira commented on src/helpers/translate.js
> +    courseBillingItemExists: 'Course billing item exists',
done

2022-02-10 09:30 UTC, ulysseferreira commented on tests/integration/helpers/authentication.js
> +const CourseBillingItem = require('../../../src/models/CourseBillingItem');
done

2022-02-10 11:29 UTC, sophiemoustard approved these changes

2022-02-10 11:29 UTC, merged