Com 2652
sophiemoustard/compani-api pull request #1823
Opened 2022-02-15 11:57 UTC by CorentinMartinot

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : coach coté outils

- Cas d'usage : j'ai retiré momentJS sur les routes 
   -` /paid-intervention-stats`
   - `/internal-billed-hours`
   - `/customer-duration/sector`
 Il dans le service stat.js il n'y a plus moment

- Comment tester ? :
   - dans la tableau de bord > detail sur un.e auxiliaire / planning auxiliaire :  " X bénéficiaires accompagnés, X h en moyenne "
   - dans le tableau de bord > données par equipe : " X beneficiaire" et "X heures par beneficiaire"
   - dans le tableau de bord > en dessous du compteur d'heure: "Heures internes XXh"

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-02-15 15:49 UTC, ulysseferreira commented on src/helpers/stats.js
> +    const startOfMonth = CompaniDate(query.month, 'MM-yyyy').startOf('month').toISO();
le format sans tiret n'existe pas sous luxon ?

2022-02-15 17:10 UTC, CorentinMartinot commented on src/helpers/stats.js
> +    const startOfMonth = CompaniDate(query.month, 'MM-yyyy').startOf('month').toISO();
Oui  pardon, j'ai oublié de preciser ca dans le descriptif.

Le format demandé par la route est avec tiret '12-2021' ('122021' est refusé).

Comportement de moment.format :  momentJS ignore les caracteres qui ne sont pas des flags
```
The parser ignores non-alphanumeric characters by default, so both of the following will return the same thing.

moment("12-25-1995", "MM-DD-YYYY");
moment("12/25/1995", "MM-DD-YYYY");

https://momentjs.com/docs/#/parsing/string-format/
```

Comportement de luxon : je n'ai pas trouver de doc, mais d'experience luxon demande de specifier les caracteres qui ne sont pas des flags. 
=> faite le test

2022-02-16 08:50 UTC, ulysseferreira approved these changes

2022-02-16 10:55 UTC, sophiemoustard requested changes

2022-02-16 10:55 UTC, sophiemoustard commented on src/repositories/SectorHistoryRepository.js
> +  const maxDate = CompaniDate(month, 'MM-yyyy').endOf('month').toDate();
pour etre sure de bien comprendre le fonctionnement de CompaniDate : 
- dans le service `stats`, tu crées les dates en `toISO` puis tu utilises `new Date` dans l'aggregation
- ici tu crées les dates en `toDate` puis tu les utilises telles quelles dans l'aggregation
pourquoi ?

2022-02-16 11:06 UTC, CorentinMartinot commented on src/repositories/SectorHistoryRepository.js
> +  const maxDate = CompaniDate(month, 'MM-yyyy').endOf('month').toDate();
c'est un oublie, j'ai changé

2022-02-16 12:23 UTC, merged