COM-2738: refacto to change item in purchase
sophiemoustard/compani-api pull request #1847
Opened 2022-03-09 16:09 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : renommage de billingitemList => billingPurchase et conséquences

- Comment tester ? :
  - créer une facture avec des articles et la valider : tout marche 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-03-09 16:36 UTC, CorentinMartinot commented on src/routes/preHandlers/courseBills.js
> +    courseBill.billingPurchaseList.find(item => UtilsHelper.areObjectIdsEquals(item.billingItem, billingItem))) {
dans le find : `purchase => ...` au lieu de `item => ...`

2022-03-09 16:36 UTC, CorentinMartinot commented on src/helpers/courseBills.js
>          .map(item => NumbersHelper.multiply(item.price, item.count))
dans le .map : `puchase => ...` au lieu de `item => ...`

2022-03-09 16:50 UTC, ulysseferreira commented on src/routes/preHandlers/courseBills.js
> +    courseBill.billingPurchaseList.find(item => UtilsHelper.areObjectIdsEquals(item.billingItem, billingItem))) {
done

2022-03-09 16:50 UTC, ulysseferreira commented on src/helpers/courseBills.js
>          .map(item => NumbersHelper.multiply(item.price, item.count))
done

2022-03-10 08:08 UTC, sophiemoustard requested changes

2022-03-10 08:08 UTC, sophiemoustard commented on src/helpers/courseBills.js
>      };
sur une ligne ?

2022-03-10 08:08 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +  await CourseBill.updateOne({ _id: courseBillId }, { $push: { billingPurchaseList: payload } });
tu peux faire directement `exports.addBillingPurchase = async (courseBillId, payload) => CourseBill.updateOne({ _id: courseBillId }, { $push: { billingPurchaseList: payload } });` non ?

2022-03-10 08:08 UTC, sophiemoustard commented on src/routes/preHandlers/courseBills.js
> +    .find(purchase => UtilsHelper.areObjectIdsEquals(purchase.billingItem, billingItem))) {
si tu mets `p` au lieu de `purchase` dans ta méthode `find` ça tient sur une ligne non ? je trouve que les condition `if` sur une ligne sont plus lisible

2022-03-10 09:09 UTC, ulysseferreira commented on src/helpers/courseBills.js
>      };
done

2022-03-10 09:09 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +  await CourseBill.updateOne({ _id: courseBillId }, { $push: { billingPurchaseList: payload } });
done

2022-03-10 09:10 UTC, ulysseferreira commented on src/routes/preHandlers/courseBills.js
> +    .find(purchase => UtilsHelper.areObjectIdsEquals(purchase.billingItem, billingItem))) {
done

2022-03-10 09:28 UTC, CorentinMartinot approved these changes

2022-03-10 09:48 UTC, sophiemoustard approved these changes

2022-03-10 09:49 UTC, merged