Com 2755
sophiemoustard/compani-api pull request #1882
Opened 2022-04-06 09:01 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : je peux ajouter des règlements à une facture

- Comment tester ? :
  - sur une facture sur la fiche d'une structure ajouter un paiement et un remboursement
  - dérouler le détail de la facture avec les différents règlements affichés

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-06 10:39 UTC, CorentinMartinot commented on src/helpers/courseBills.js
> +    .populate('company')
De plus, je trouve ca dommage de populer la structure sur les resultat, alors que la query comporte une seule facture...

2022-04-06 12:28 UTC, ulysseferreira commented on src/routes/coursePayments.js
> +'use-strict';
je ne suis pas sûr de comprendre ton retour

2022-04-06 12:29 UTC, ulysseferreira commented on src/routes/coursePayments.js
> +            date: Joi.date().required(),
done

2022-04-06 12:30 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +    .populate('company')
done

2022-04-06 15:46 UTC, CorentinMartinot commented on src/routes/coursePayments.js
> +'use-strict';
pour executer en mode strict c sans tiret au milieu : "use strict"
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Strict_mode

2022-04-06 16:23 UTC, CorentinMartinot approved these changes

2022-04-07 09:08 UTC, sophiemoustard requested changes

2022-04-07 09:08 UTC, sophiemoustard commented on src/helpers/coursePayments.js
> +    .findOneAndUpdate({}, { $inc: { seq: 1 } }, { new: true, upsert: true, setDefaultsOnInsert: true })
il faut que tu filtres sur la nature du paiement la non ?

2022-04-07 09:08 UTC, sophiemoustard commented on src/routes/preHandlers/coursePayments.js
> +    const courseBill = await CourseBill.findOne({ _id: courseBillId }).lean();
tu peux projeter pour ne recuperer que les 2 champs voulus non ?

2022-04-07 09:08 UTC, sophiemoustard commented on tests/integration/coursePayments.test.js
> +    it('should create a payment', async () => {
suite au retour que je t'ai fait sur la requete de `CoursePaymentNumber` je me demande si le teste suivant ne sereait pas interessant : 
- appel a la route pour la creation d'un paiement
- validation du numero
- appel a la route pour la creation d'un remboursement
- validation du numero et du coup validation qu'on n'est sur une incrementation differente du paiement)

2022-04-07 09:28 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +    .populate({ path: 'coursePayments', options: { isVendorUser: has(credentials, 'role.vendor') } })
done

2022-04-07 09:29 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +    .populate({ path: 'coursePayments', options: { isVendorUser: has(credentials, 'role.vendor') } })
on utilise has partout ailleurs c'est une erreur ?

2022-04-07 09:30 UTC, ulysseferreira commented on src/models/CourseBill.js
> +CourseBillSchema.virtual('coursePayments', {
done

2022-04-07 09:30 UTC, ulysseferreira commented on src/models/CoursePayment.js
> +
done

2022-04-07 09:32 UTC, ulysseferreira commented on src/models/CoursePayment.js
> +  nature: { type: String, enum: PAYMENT_NATURES },
done

2022-04-07 09:53 UTC, ulysseferreira commented on src/helpers/coursePayments.js
> +    .findOneAndUpdate({}, { $inc: { seq: 1 } }, { new: true, upsert: true, setDefaultsOnInsert: true })
done

2022-04-07 10:08 UTC, ulysseferreira commented on tests/integration/coursePayments.test.js
> +    it('should create a payment', async () => {
done

2022-04-07 12:41 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +    .populate({ path: 'coursePayments', options: { isVendorUser: has(credentials, 'role.vendor') } })
a mon avis oui, `has` veirfie uniquement la presence de la clé et non ca valeur donc je pense qu'ici c'est important de virer les `null`

2022-04-07 12:43 UTC, sophiemoustard approved these changes

2022-04-08 07:29 UTC, merged