Com 2776
sophiemoustard/compani-api pull request #1885
Opened 2022-04-07 11:35 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles :

- Cas d'usage :

- Comment tester ? :

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-07 14:52 UTC, ulysseferreira commented on src/helpers/repetitions.js
> +    ...omit(payload, FIELDS_NOT_APPLICABLE_TO_REPETITION),
il faut garder repetition dans payload ? on a l'information a 2 endroits

2022-04-07 15:51 UTC, ulysseferreira commented on src/helpers/repetitions.js
> +    ...omit(payload, FIELDS_NOT_APPLICABLE_TO_REPETITION),
ah oui pardon je dis de la d

2022-04-07 16:11 UTC, ulysseferreira approved these changes

2022-04-08 08:21 UTC, sophiemoustard requested changes

2022-04-08 08:21 UTC, sophiemoustard commented on src/helpers/repetitions.js
> +  const repetition = { ...payload.repetition, parentId: event._id };
tu pourrais mettre ca directement dans le return quand penses tu ?

2022-04-08 08:48 UTC, manonpalin commented on src/helpers/repetitions.js
> +  const repetition = { ...payload.repetition, parentId: event._id };
Oui, cette constante n'est pas indispensable. Autant tout definir dans le return

2022-04-08 09:03 UTC, sophiemoustard approved these changes

2022-04-08 09:03 UTC, merged