Com 2777
sophiemoustard/compani-api pull request #1893
Opened 2022-04-12 14:05 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [x] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail] - np (https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure -np
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile -np
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement -np
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation -np
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [x] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : auxiliaire / coach / admin

Cas d'usage : résolution de bugs liés a notre nouvelle gestion des répétitions
- l'edition de l'adresse est applicable a la repetition
- si l'utilisateur modifie des champs liés à la repetition (horaires, service, addresse) et d'autres liés a l'évènement seul (note, déplacement vehiculé avec le beneficiaire et mode de transport), toutes le modifications sont bien appliquées

Comment tester ? :

- édition d'une intervention appartenant a une repetition en appliquant les modifs a la repetition
      - si il y a conflit avec un autre evenement --> l'evennement est sorti de la repetition et passé en A affecter
      - si pas de conflit:
            - editer l'horaire + le champ note + le champ déplacement vehiculé + le champ mode de transport
                  - vérifier que les modifs sur les champs note, déplacement vehiculé et mode de transport ne s'applique que sur le 1er évenement de la repetition
                  - vérifier que toutes les autres modifications se sont appliquées a la repetition
- édition d'une intervention appartenant a une repetition en appliquant les modifs a l'evenemnet seul
      - verifier que les modifs sont bien appliquées et que l'évènement est sorti de la repetition
- edition d'une intervention n'appartenant pas a une repetition
- édition d'une heure interne ou d'une indisponibilité appartenant a une repetititon
      - verifier que l'édition d'un evenemnt seul fonctionne
      - verifier que l'édition de tous les evenements de la repetition fonctionne
      - 
_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-13 12:27 UTC, cmolle commented on tests/unit/helpers/eventsRepetition.test.js
> +  it('should update repetition', async () => {
Que penses-tu dans ce test de : 
- ajouter des champs qui doivent etre enlever par le omit FIELDS_NOT_APPLICABLE_TO_REPETITION
- Faire en sorte qu'un des appels a updateEventBelongingToRepetition ne renvoie rien et donc que la promesse ne soit pas ajoute au tableau

Je suis un peu tiraillé aussi sur le fait qu'on test plusieurs evenements de type differents. En meme temps je trouve ca cool mais d'un autre cote, je trouve ca etrange que ce soit dans le meme test vu que normalement une repetition n'a qu'un type 🤔 Qu'en penses-tu ? Que penses-tu d'ajouter un test pour type indispo egalement ?

2022-04-13 13:30 UTC, manonpalin commented on tests/unit/helpers/events.test.js
> +      [
Oui bien vu ! c'st ajouté

2022-04-13 13:39 UTC, manonpalin commented on tests/unit/helpers/eventsRepetition.test.js
> +  it('should delete internal hours in conflicts', async () => {
pour une absence aussi ? 
Les absences ne peuvent pas appartenir a une repetition

2022-04-13 13:51 UTC, manonpalin commented on tests/unit/helpers/eventsRepetition.test.js
> +  it('should update repetition', async () => {
- J'avais ajouté le champ `misc` mais tu as raison autant ajouter les autres aussi, c'est fait.
- On a viré le cas ou updateBelongingToRepetition ne renvoie rien ;) 
- Tu as raison, je vais faire un test par type d'événement

2022-04-14 10:28 UTC, ulysseferreira commented on src/helpers/events.js
> +        .populate({ path: 'sector', select: '_id sector', match: { company: companyId } })
il n'y a pas de champ sector dans le modèle sector

2022-04-14 11:57 UTC, sophiemoustard commented on src/helpers/events.js
> +        .populate({ path: 'sector', select: '_id sector', match: { company: companyId } })
@ulysseferreira le champ `sector` (`path: 'sector'`) est un virtuel du modele `User` qui recupère la collection `SectorHIstory` qui contient lui un champ `sector`
On utilise ensuite un postHook `UserSchema.post('findOne', populateSector);` pour transformer `user.sector.sector` en `user.sector`

2022-04-14 12:09 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
> +  }
et tu pourrais changer le `set` en faisant comme ca qu'en penses tu ?
`{ ...omit(repetitionPayload, 'auxiliary'), sector: sectorId }`

2022-04-14 12:14 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
>    await Promise.all([
apres si tu trouves ca mieux de bien identifier concaténation du tableau puis execution des promesses, tu peux faire comme suit
```
promises.push(RepetitionsHelper.updateRepetitions(eventPayload, eventFromDb.repetition.parentId));
await Promise.all(promises);
```

2022-04-14 12:16 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
>        endDate,
ici tu pourrais mettre directement : 
```
startDate: CompaniDate(events[i].startDate).set(payloadStartHour).toISO(),
endDate: CompaniDate(events[i].endDate).set(payloadEndHour).toISO(),
```
qu'en penses tu ?

2022-04-14 12:18 UTC, sophiemoustard commented on src/helpers/events.js
> +    }
je trouve que ce bout de code tombe un peu comme un cheveu sur la soupe et on ne comprends pas trop pourquoi tu fais ca la... je suis allée voir les utilisation dans `updateRepetition` et `updateEventBelongingToRepetition` pour comprendre et je pense qu'on pourrait rendre plus explicite du coup...

que penses tu d'extraire ce bout de code dans une methode `getEventSector` ?

2022-04-14 12:22 UTC, sophiemoustard commented on src/helpers/events.js
> +    await EventsRepetitionHelper.updateEventBelongingToRepetition(eventToSet, eventPayload, event, companyId, sectorId);
quelle est la différence entre `eventToSet`, `eventPayload` et `event` ?

2022-04-14 12:40 UTC, ulysseferreira commented on src/helpers/eventsRepetition.js
> +  }
d'ailleurs le detachFromRepetition || !eventPayload.auxiliary il peut être simplifié en `!eventPayload.auxiliary || hasConflicts`, non ? parce qu'en l'état ça vaut `!!eventPayload.auxiliary && hasConflicts || !eventPayload.auxiliary` et c'est un peu redondant

2022-04-14 13:03 UTC, manonpalin commented on src/helpers/eventsRepetition.js
>        endDate,
Oui ca me va !

2022-04-14 13:10 UTC, manonpalin commented on src/helpers/eventsRepetition.js
>    await Promise.all([
done

2022-04-14 13:31 UTC, manonpalin commented on src/helpers/events.js
> +    }
Oui tu as raisons, on peut le définir dans une methode a part. On l'a deplcé ici pour éviter de le definir 2 fois: une fois dans updateRepetition et dans `updateBelongingToRepetition` mais en effet, c'est plus clair de le definir en dehors

2022-04-14 14:29 UTC, manonpalin commented on src/helpers/eventsRepetition.js
> +  }
Hmm tu as raison, les deux sont tjs liés. Il faudrait modifier hasConflicts pour renvoyer false si auxiliary n'existe pas

2022-04-14 14:30 UTC, manonpalin commented on src/helpers/eventsRepetition.js
> +exports.updateEventBelongingToRepetition = async (repetitionPayload, eventPayload, event, companyId, sectorId) => {
Non tu as raison un seul suffit, j'ai mutualisé et on peut utiliser seulement eventPayload

2022-04-14 15:16 UTC, manonpalin commented on src/helpers/events.js
> +    await EventsRepetitionHelper.updateEventBelongingToRepetition(eventToSet, eventPayload, event, companyId, sectorId);
J'ai retravaillé le code pour ne garder que eventPayload

2022-04-15 07:45 UTC, ulysseferreira approved these changes

2022-04-15 13:24 UTC, sophiemoustard requested changes

2022-04-15 13:24 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
> +    ...pick(event, ['_id', 'type']),
ah il est deja dans le `eventPayload` c'est ca ?

2022-04-15 13:27 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
> +  }
En fait ce que veut dire Ulysse c'est : 
- quand tu fais `if (detachFromRepetition || !eventPayload.auxiliary)`
- tu fais `(!!eventPayload.auxiliary && hasConflicts) || !eventPayload.auxiliary`
- ce qui est equivalent logiquement à `!eventPayload.auxiliary || hasConflcits` car : 
    - si !eventPayload.auxiliary est vrai alors ton `if` est vrai
    - si !eventPayload.auxiliary est faut alors `!!eventPayload.auxiliary` et donc ton `if` prend la valeur de `hasConflicts`

2022-04-15 15:23 UTC, sophiemoustard approved these changes

2022-04-15 15:28 UTC, merged