Com 2773
sophiemoustard/compani-api pull request #1897
Opened 2022-04-14 11:02 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur /rof/admin

- Cas d'usage : sur le profil d'une structure je peux visualiser ses factures avec leur détail + boyscout bloquer date d'avoir antérieure à facturation

- Comment tester ? :
  - facturer une formation
  - sur le profil de la structure associée la facture apparait bien (aucun règlement)
  - lui ajouter des règlements/remboursements => ils apparaissent dans le détail et les colonnes solde et réglé/crédité sont mises à jour
  - faire un avoir sur la facture => je ne peux pas mettre une date d'avoir antérieur à la date de facturation + il apparait bien dans le détail et les colonnes solde et réglé/crédité sont mises à jour
  - facturer une autre formation de la même structure
  - refaire les étapes précédentes
  - le solde total est le bon

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-14 14:54 UTC, sophiemoustard requested changes

2022-04-14 14:54 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +      .reduce((acc, val) => acc + val, 0);
ou meme pour calculer `payments - refunds` tu pourrais utiliser la methode `computePayments` du service balance, qu'en penses tu ?
a bouger dans le service `payments` peut etre du coup

2022-04-14 14:54 UTC, sophiemoustard commented on tests/unit/helpers/courseBills.test.js
> +      slots: [
sur une ligne ?

2022-04-14 14:54 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +      .reduce((acc, val) => acc + val, 0);
d'ailleurs comme en front tu peux simplifier directement avec un seul reduce sur `val.netInclTaxes`

2022-04-14 15:18 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +  return courseBills.map((bill) => {
done

2022-04-14 15:19 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +      .reduce((acc, val) => acc + val, 0);
done

2022-04-14 15:20 UTC, ulysseferreira commented on tests/unit/helpers/courseBills.test.js
> +      slots: [
done

2022-04-14 15:33 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +      .reduce((acc, val) => acc + val, 0);
done. Par contre je sais pas si c'est pertinent de le bouger dans payments. Y a-t-il une bonne raison pour qu'il soit dans payments plutôt que balance ? à la limite dans utils ?

2022-04-15 11:55 UTC, cmolle approved these changes

2022-04-15 13:04 UTC, sophiemoustard approved these changes

2022-04-15 15:20 UTC, merged