COM-2792: new field estimatedstartdate on model and export
sophiemoustard/compani-api pull request #1902
Opened 2022-04-22 13:27 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : je peux ajouter une date de démarrage souhaitée pour une formation

- Comment tester ? :
  - sur la branche dev exporter les formations pour une période donnée
  - faire de même sur cette branche et s'assurer qu'on a bien la même chose (à l'exception de certains champs de "comptage" ou le vide a été remplacé par 0
  - créer une formation avec une date de démarrage dans la période précédemment utilisée et exporter les formations => j'ai bien ma formation dans l'export
  - ajouter un créneau à la formation, en dehors de la période donnée => la date de démarrage ne s'affiche plus sur le profile de la formation + la formation n'est plus dans l'export 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-22 14:16 UTC, cmolle commented on src/helpers/historyExport.js
> -      'Nombre d\'inscrits': get(course, 'trainees.length') || '',
Qu'est-ce qui a motive ce changement ?

2022-04-22 14:20 UTC, cmolle commented
Dans les exports, quand j'export une formation avec plusieurs factures j'ai deux fois le payeur et le oui de facturée (sur la meme ligne).

2022-04-22 14:25 UTC, ulysseferreira commented on src/helpers/historyExport.js
> -      'Nombre d\'inscrits': get(course, 'trainees.length') || '',
c'est juste que ça m'a semblé plus logique quand la valeur est 0 de mettre 0 plutôt que de laisser vide

2022-04-22 14:44 UTC, ulysseferreira commented
> Dans les exports, quand j'export une formation avec plusieurs factures j'ai deux fois le payeur et le oui de facturée (sur la meme ligne).

oui ce sont les payeurs des deux factures et la validation des deux factures. Quel est le problème ?

2022-04-22 15:08 UTC, cmolle commented on src/routes/preHandlers/courses.js
> +    const hasVendorRole = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN].includes(userVendorRole);
Que penses-tu de l'appeler plutot isRofOrAdmin ?

2022-04-22 15:08 UTC, cmolle commented on tests/integration/courses.test.js
> +    it('should return 403 as user is client_admin and try to update estimated start date', async () => {
Que penses-tu de tester aussi pour les formateurs ?

2022-04-25 07:39 UTC, sophiemoustard requested changes

2022-04-25 08:19 UTC, ulysseferreira commented
> > Dans les exports, quand j'export une formation avec plusieurs factures j'ai deux fois le payeur et le oui de facturée (sur la meme ligne).
> 
> oui ce sont les payeurs des deux factures et la validation des deux factures. Quel est le problème ?
> 
> Chloe : je me demandais si c'etait voulu, mais si c'est le cas parfait (on pourrait vouloir uniquement la derniere facture vu que les autres sont annulés)

je l'avais pas vu sous cet angle, tu as raison j'ai demandé à Romain et on veut juste la facture active, c'est corrigé

2022-04-25 08:20 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +    const hasVendorRole = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN].includes(userVendorRole);
done

2022-04-25 08:21 UTC, ulysseferreira commented on tests/integration/courses.test.js
> +    it('should return 403 as user is client_admin and try to update estimated start date', async () => {
done

2022-04-25 08:31 UTC, ulysseferreira commented on src/helpers/historyExport.js
> +        { $and: [{ estimatedStartDate: { $lte: endDate, $gte: startDate } }, { archivedAt: { $exists: false } }] },
ce find nous retourne beaucoup de formation dont certaines qu'on veut pas (celles qui ont une estimatedStartDate dans le filtre et des créneaux pas dans le filtre). Le filtre sur l'archive c'est pour limiter un peu le nombre de formations non voulues : si elles sont archivées, c'est qu'elles ont des créneaux et que donc l'estimatedStartDate n'est plus pertinente

2022-04-25 08:32 UTC, ulysseferreira commented on src/helpers/historyExport.js
> +};
done

2022-04-25 12:26 UTC, cmolle commented on src/helpers/historyExport.js
> +      .filter(bill => !bill.courseCreditNote)
Tu pourrais creer une constante `courseBillsWithoutCreditNote` pour eviter de faire le filtre deux fois. Qu'en penses-tu ?

2022-04-25 12:51 UTC, cmolle approved these changes

2022-04-26 08:09 UTC, sophiemoustard approved these changes

2022-04-26 09:24 UTC, merged