Com 2829
sophiemoustard/compani-api pull request #1925
Opened 2022-05-05 07:21 UTC by cmolle

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles :

- Cas d'usage :

- Comment tester ? :

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-05 07:23 UTC, cmolle commented on src/helpers/creditNotes.js
> +const { HOURLY, COMPANI } = require('./constants');
meme import

2022-05-06 12:11 UTC, ulysseferreira commented on tests/integration/seed/creditNotesSeed.js
>      exclTaxesTpp: 5,
il ne faut pas mettre en string exclTaxesTpp et exclTaxesCustomer ?

2022-05-06 12:11 UTC, ulysseferreira commented on tests/integration/exports.test.js
> +  describe(`EXPORTS ROUTES - GET /exports/${exportType}/history #tag`, () => {
tag à retirer

2022-05-06 13:42 UTC, sophiemoustard requested changes

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +    netInclTaxes: customerBills.total,
pourquoi tu enleves le `getFixedNumber` ?

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +      netInclTaxes: tpp.total,
idem

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +  let netInclTaxes = NumbersHelper.toString('0');
on veut plutot le `netInclTaxes` en nombre non ?

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +  if (!bill.thirdPartyPayer) return NumbersHelper.toString(subscription.unitInclTaxes);
on ne le veut pas en nombre celui la ? 
cf mes questions coté webapp, j'ai l'impression qu'il y a un melange pour ce champ 🤔

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +  if (!matchingVersion) return NumbersHelper.toString(0);
selon la reponse pour le retour precedent, a changer ou non

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/bills.js
> +  return NumbersHelper.toString(subscription.unitInclTaxes);
idem

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +  const mainFeeTotal = NumbersHelper.oldMultiply(bill.mainFee.price, bill.mainFee.count);
pourquoi ce retour a l'ancienne ?

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +    ? bill.billingPurchaseList.map(p => NumbersHelper.oldMultiply(p.price, p.count)).reduce((acc, val) => acc + val, 0)
idem

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +  return NumbersHelper.oldAdd(mainFeeTotal, billingPurchaseTotal);
idem

2022-05-06 13:42 UTC, sophiemoustard commented on src/helpers/courses.js
> +  ? course.subProgram.steps.reduce((acc, value) => NumbersHelper.oldAdd(acc, value.theoreticalHours || 0), 0)
idem

2022-05-06 14:37 UTC, manonpalin commented on src/helpers/billSlips.js
> +    total = NumbersHelper.oldAdd(total, bill.netInclTaxes.toFixed(2));
Je pense que c'est pendant le rebase car je n'ai pas touché a ce fichier

2022-05-06 14:52 UTC, manonpalin commented on src/helpers/billSlips.js
> +    total = NumbersHelper.oldAdd(total, bill.netInclTaxes.toFixed(2));
Pendant le rebase

2022-05-06 16:17 UTC, manonpalin commented on tests/integration/seed/creditNotesSeed.js
>      exclTaxesTpp: 5,
Si bien vu !

2022-05-06 16:17 UTC, manonpalin commented on src/helpers/bills.js
> +    netInclTaxes: customerBills.total,
avant rebase

2022-05-06 16:17 UTC, manonpalin commented on src/helpers/bills.js
> +      netInclTaxes: tpp.total,
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/bills.js
> +  let netInclTaxes = NumbersHelper.toString('0');
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/bills.js
> +  if (!bill.thirdPartyPayer) return NumbersHelper.toString(subscription.unitInclTaxes);
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/bills.js
> +  if (!matchingVersion) return NumbersHelper.toString(0);
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/bills.js
> +  return NumbersHelper.toString(subscription.unitInclTaxes);
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/courseBills.js
> +  const mainFeeTotal = NumbersHelper.oldMultiply(bill.mainFee.price, bill.mainFee.count);
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/courseBills.js
> +    ? bill.billingPurchaseList.map(p => NumbersHelper.oldMultiply(p.price, p.count)).reduce((acc, val) => acc + val, 0)
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/courseBills.js
> +  return NumbersHelper.oldAdd(mainFeeTotal, billingPurchaseTotal);
idem

2022-05-06 16:18 UTC, manonpalin commented on src/helpers/courses.js
> +  ? course.subProgram.steps.reduce((acc, value) => NumbersHelper.oldAdd(acc, value.theoreticalHours || 0), 0)
idem

2022-05-09 10:29 UTC, ulysseferreira commented on tests/integration/exports.test.js
>          expect(rows.length).toBe(expectedRows.length);
c'est volontaire la suppression de cette ligne ?

2022-05-09 10:29 UTC, ulysseferreira commented on tests/integration/creditNotes.test.js
> +// describe('CREDIT NOTES ROUTES - PUT /creditNotes/:id', () => {
c'est normal que ça soit commenté ?

2022-05-09 13:06 UTC, manonpalin commented on tests/integration/creditNotes.test.js
> +// describe('CREDIT NOTES ROUTES - PUT /creditNotes/:id', () => {
Oui j'aurais du dire pourquoi pardon ! 
En fait, la creation casse l'édition (au niveau des types qu'on envoie dans la route, il y a une incohérence tant qu'on ne fait pas l'édition), j'ai donc commenté les tests pour les réparer dans le ticket sur l'édition des avoirs

2022-05-09 13:08 UTC, manonpalin commented on tests/integration/exports.test.js
>          expect(rows.length).toBe(expectedRows.length);
Non bien vu

2022-05-09 14:06 UTC, ulysseferreira approved these changes

2022-05-09 14:41 UTC, sophiemoustard requested changes

2022-05-09 14:41 UTC, sophiemoustard commented on src/helpers/creditNotes.js
> -      if (event.bills.nature !== HOURLY) {
pourquoi ce changement ?

2022-05-09 14:41 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +    const tppParticipationPrice = eventPrice.thirdPartyPayerPrice &&
hasTppPrice ? pour qu'on comprenne que c;est un booleen

2022-05-09 14:41 UTC, sophiemoustard commented on src/models/FundingHistory.js
> -  nature: String,
pourquoi as tu enlever nature ?

2022-05-09 16:17 UTC, manonpalin commented on src/models/FundingHistory.js
> -  nature: String,
Car c'est un champ qui n'est utilisé nul part, on a regardé en base il n'existe pas et on ne l'utilise pas dans le code non plus donc on l'a retiré

2022-05-09 16:26 UTC, manonpalin commented on src/helpers/creditNotes.js
> -      if (event.bills.nature !== HOURLY) {
On trouvait plus simple de raisonner dans ce sens la, on a retravaillé la logique pour d'abord regarder si la fréquence du financement est mensuelle ou en une seul fois, avant de regarder si, dans le cas de la fréquence en une seule fois, le financement est horaire ou forfaitaire pour incrémenter amountTTC ou careHours

2022-05-10 10:29 UTC, sophiemoustard approved these changes

2022-05-10 10:29 UTC, merged