COM-2817: refacto slot creation
sophiemoustard/compani-api pull request #1929
Opened 2022-05-09 10:00 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : client/vendeur coach/rof/formateur

- Cas d'usage : je ne peux créer que des créneaux à planifier en tant que rof

- Comment tester ? : 
- rof : créer un créneau à planifier et le modifier
- coach/formateur : modifier un créneau à planifier + je ne peux pas créer de créneau 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-09 14:47 UTC, ulysseferreira commented on src/routes/preHandlers/courseSlot.js
>      const courseId = get(req, 'payload.course') || '';
done

2022-05-10 08:10 UTC, manonpalin commented
J'ai un comportement bizarre sur la suppression:
- j'ai ajouté une date a planifier
- cliquer sur le créneau a planifier
- essayé de le supprimer (sans le relier a une étape)
- le message `seul créneau de l'étape: impossible de le supprimer` apparait 

Normalement je devrais pouvoir le supprimer non?

2022-05-10 08:51 UTC, ulysseferreira commented
> J'ai un comportement bizarre sur la suppression:
> 
> * j'ai ajouté une date a planifier
> * cliquer sur le créneau a planifier
> * essayé de le supprimer (sans le relier a une étape)
> * le message `seul créneau de l'étape: impossible de le supprimer` apparait
> 
> Normalement je devrais pouvoir le supprimer non?

en effet, mais c'est transitoire, les créneaux à planifier relier à aucune étape ce n'est plus censé exister après le prochain ticket donc je suis pas sûr que ça soit pertinent de faire un fix pour ça qui sera supprimer juste après

2022-05-10 11:59 UTC, sophiemoustard commented on src/routes/preHandlers/courseSlot.js
> +      if (!course.subProgram.steps.map(s => s.toHexString()).includes(stepId)) throw Boom.badRequest();
tu as la methode `doesArrayIncludeId`

2022-05-10 11:59 UTC, sophiemoustard requested changes

2022-05-10 11:59 UTC, sophiemoustard commented on src/routes/preHandlers/courseSlot.js
> +      const course = await Course.findById(courseId).populate({ path: 'subProgram', select: 'steps' }).lean();
tu peux ajouter un select

2022-05-10 12:32 UTC, ulysseferreira commented on src/routes/preHandlers/courseSlot.js
> +      const course = await Course.findById(courseId).populate({ path: 'subProgram', select: 'steps' }).lean();
je ne suis pas sûr de comprendre ton retour, il y a déjà un select

2022-05-10 13:41 UTC, sophiemoustard commented on src/routes/preHandlers/courseSlot.js
> +      const course = await Course.findById(courseId).populate({ path: 'subProgram', select: 'steps' }).lean();
dans la findById je voulais dire pardon

2022-05-10 14:04 UTC, merged