Com 2809-2
sophiemoustard/compani-api pull request #1931
Opened 2022-05-11 13:05 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : admin client

- Cas d'usage : 

- Comment tester ? :
    - 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-11 16:18 UTC, sophiemoustard requested changes

2022-05-12 09:54 UTC, manonpalin commented on src/helpers/bills.js
> +    ? { eventId: ev.event, ...pick(ev, pickedFields), careHours: NumbersHelper.toString(ev.history.careHours) }
Je me suis posé la question et il me semble qu'on c'était dit qu'on ne changeait pas dans draftBills car on fait des modifications par référence sur les champs `careHours` et `amountTTC` dans les methodes `getHourlyFundingSplit` et `getFixedFundingSplit`.
Mais d'un cote je me demande si on ne devrait pas faire le changement quand meme car la on se retrouve avec careHours qui est un string dans les factures et qui est un nombre dans la collection fundinghistories, ce qui ne me semble pas tres cohérent. D'autant plus que `careHours` est un champ sur lequel on effectue des calculs a chaque facture, donc je pense qu'il faut le passer en string.

Qu'n penses-tu ? 
(du coup il faudrait aussi modifier les champ `amountTTC` pour le passer en string et faire les modifs sur la collection fundinghistories)

2022-05-13 06:16 UTC, manonpalin commented on src/helpers/bills.js
> +    ? { eventId: ev.event, ...pick(ev, pickedFields), careHours: NumbersHelper.toString(ev.history.careHours) }
C'est modifié

2022-05-13 06:16 UTC, manonpalin commented on src/helpers/bills.js
> +          ...(has(ev, 'careHours') && { careHours: NumbersHelper.toString(ev.careHours) }),
done

2022-05-13 06:16 UTC, manonpalin commented on src/helpers/bills.js
> +          billedEvents[ev.event] = { ...ev, careHours: NumbersHelper.toString(ev.history.careHours) };
done

2022-05-13 06:16 UTC, manonpalin commented on src/helpers/bills.js
> +        } else billedEvents[ev.event] = { ...ev };
done

2022-05-13 06:57 UTC, sophiemoustard approved these changes

2022-05-13 10:27 UTC, manonpalin commented on src/helpers/bills.js
> +      !NumbersHelper.isEqualTo(ev.history.careHours, '0')
Oui car `!isEqualTo(undefined, '0')` retourne true, donc si ev.history.careHours n'est pas définie on entrerai dans la boucle or ce n'est pas ce qu'on veut

2022-05-13 10:50 UTC, manonpalin commented on src/helpers/bills.js
> +        }
Oups c'est pcq je l'ai modifié a plusieurs reprises est que ca tenait pas sur une seule ligne . Je remets comme c'était

2022-05-13 10:50 UTC, manonpalin commented on src/helpers/bills.js
> +        { $set: flat({ amountTTC: newAmountTTC }) },
Non tu as riions dans ce cas le flat renvoie { amountTTC: newAmountTTC }

2022-05-13 11:31 UTC, cmolle approved these changes

2022-05-13 11:43 UTC, merged