COM-2848: remove dates on slot
sophiemoustard/compani-api pull request #1943
Opened 2022-05-19 13:34 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : client/vendeur coach/admin.rof

- Cas d'usage : je peux supprimer la date d'un créneau

- Comment tester ? :
 - créer un créneau à planifier
 - ouvrir la modale d'édition => pas de bouton de suppression
 - lui ajouter une date et une adresse
 - rouvrir la modale d'édition => bouton de suppression
 - supprimer la date : 
   - le créneau repasse en créneau à planifier  + l'adresse est supprimée
   - en base il y a un historique de suppression avec les heures du créneau supprimées et l'adresse supprimée

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-20 07:18 UTC, cmolle commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
Comment as-tu choisi de supprimer le creneau par rapport a ces deux champs ? 🤔 Je me pose pas mal de question sur cette route ^^ Que penses-tu sinon de creer des actions ? `unplanning` et `planning` par exemple.

2022-05-20 10:18 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +      .updateOne({ _id: slotFromDb._id }, { $unset: { startDate: '', endDate: '', meetingLink: '', address: '' } });
done

2022-05-20 10:19 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
je ne suis pas sûr de comprendre ton questionnement

2022-05-20 11:56 UTC, cmolle commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
Je me questionne sur deux sujets : 
- Cette route me perturbe un peu car on dit que c'est pour supprimer un creneau mais en fait c'est plutot pour "deplannifié" du coup l'appel a une creation d'historique pour suppression me perturbe un peu. 
- Aussi, je me demande si il faut se baser sur le fait qu'il n'y ait pas de date dans la payload pour savoir sil faut deplanifier le creneau ou non : je me demande s'il ne faudrait pas plutot des actions a mettre dnas la route et du coup quand on veut deplanifie un creneau on envoie uniquement cette action et pas le reste (pas de date vide notamment)

Qu'en penses-tu ?

2022-05-20 12:20 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
il ne s'agit pas de supprimer un créneau, le ticket s'intitule "retirer les dates, sans supprimer le créneau", c'est une route d'update au même titre que si l'on supprimait l'adresse du créneau. Pour ce qui est de créer un historique, c'est ce que le ticket spécifiait, tu peux en discuter avec Romain si ça te semble illogique, mais on est plus dans le technique, c'est plus une question de conception. 
Vu que le but est de supprimer les dates, ça me semble tout à fait logique de se baser sur le fait qu'on ait vidé les dates pour supprimer les dates.

2022-05-20 15:11 UTC, cmolle commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
Oui je suis d'accord pour la partie route d'update, j'avais fini par me dire que c'etait effectivement le plus logique. Mon retour concernait plutot le nom de la fonction qu'on appelle pour creer l'historique. 

Oui mais comme on supprime egalement les adresses ca me perturbe un peu. L'idee est de faire passer un creneau planifie a un creneau non planifié.

2022-05-20 16:24 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
la fonction pour créer l'historique est une fonction déjà existante, on va pas en recréer une identique juste pour le nom, non ?

je sais pas, je suis pas fan de faire un paramètre juste pour ça, surtout que la date vide c'est pas juste que ça coïncide avec ce qu'on veut faire et du coup c'est pratique de l'utiliser, en front le bouton s'appelle supprimer la date, pas déplanifier le créneau, pour moi ça reste cohérent de faire comme ça. Mais on peut demander aux autres ce qu'elles en pensent

2022-05-23 09:06 UTC, cmolle commented on src/helpers/courseSlots.js
> +  if (hasEmptyDates) {
Vu ensemble :  
- Ok pour les actions
- A voir avec Romain pour le renommage de la methode par rapport a suppression vs deplannifier
- Faire les changements dans `removeCourseSlot`

2022-05-23 12:11 UTC, cmolle approved these changes

2022-05-23 13:08 UTC, sophiemoustard requested changes

2022-05-23 13:08 UTC, sophiemoustard commented on src/helpers/courseSlots.js
> +  const hasEmptyDates = !payload.endDate && !payload.startDate;
que penses tu de `shouldEmptyDates` plutot ?
avec le `has` j'ai cru qu'on parlait du créneau en question (les données en base de donnée) et non le payload

2022-05-23 13:08 UTC, sophiemoustard commented on src/helpers/courseSlots.js
> +    await CourseSlot.updateOne(
comme en dessous, tu pourrais faire un promise.all qu'en penses tu ?

2022-05-23 13:08 UTC, sophiemoustard commented on tests/unit/helpers/courseHistories.test.js
> -describe('createHistoryOnSlotDeletion', () => {
pourquoi l'avoir supprimé ?

2022-05-23 13:25 UTC, ulysseferreira commented on tests/unit/helpers/courseHistories.test.js
> -describe('createHistoryOnSlotDeletion', () => {
parce qu'il y a déjà un groupe de test pour createHistoryOnSlotDeletion un peu plus haut

2022-05-23 13:27 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +  const hasEmptyDates = !payload.endDate && !payload.startDate;
done

2022-05-23 13:28 UTC, ulysseferreira commented on src/helpers/courseSlots.js
> +    await CourseSlot.updateOne(
done

2022-05-24 09:30 UTC, sophiemoustard approved these changes

2022-05-25 06:29 UTC, merged