COM-2311 refacto tests
sophiemoustard/compani-api pull request #2011
Opened 2022-08-23 10:10 UTC by CorentinMartinot

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
- [ ] J'ai modifié un modèle utilisé en mobile [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [slite de MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : coach

- Cas d'usage : 
   - refacto des tests d'inté sur les routes : 
      - drive
      - taxCertificat
      - thirdPartyPayers
   - sur le prehandler de `TaxCertificat` : 
       - modification du code de status HTTP lors d'un appel sur un objet d'une autre structure (anciennement 403 => 404). Ce changement n'a pas d'incidence sur le front

- Comment tester ? :
   - bien regarder les changements
   - lancer les tests d'inté 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-08-23 10:37 UTC, sophiemoustard requested changes
SOPHIE: Finalement tu n'as pas ajouté `mode: required` sur les routes du drive ?

--
CORENTIN : done

--
Sophie : tu ne l'as pas mis sur la requete /list c'est voulu ?

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/drive.test.js
> +  describe('NO_ROLE_NO_COMPANY', () => {
pour cette route, a-t-on besoin du `type` dans le payload ? j'ai l'impression que non, peux tu regarder et si c'est le cas, le supprimer ?

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/drive.test.js
>      const userFileId = auxiliary.administrative.passport.driveId;
tu peux le mettre directement dans le `it`

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/taxCertificates.test.js
>      it('should not create a new tax certificate if year is invalid', async () => {
ici et dans celui d'aprs, souvent on met le code d'erreur retourné par l'api

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/taxCertificates.test.js
> +      { name: 'helper', expectedCode: 403, erp: true },
je crois qu'on ne fait pas de test pour `erp` 🤔

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/taxCertificates.test.js
>      it('should not create a new tax certificate if year is invalid', async () => {
idem pour ceux de DELETE
je te laisse relire le fichier pour voir s'il y en a d'autre

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/thirdPartyPayers.test.js
>      it('should return a 404 error if user is not from the same company', async () => {
tpp et non user

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/thirdPartyPayers.test.js
>      it('should get company third party payers', async () => {
il manque le test 404 si structure differente

2022-08-23 10:37 UTC, sophiemoustard commented on tests/integration/thirdPartyPayers.test.js
>      it('should return a 404 error if user is not from the same company', async () => {
idem

2022-08-23 14:03 UTC, CorentinMartinot commented on tests/integration/thirdPartyPayers.test.js
>      it('should get company third party payers', async () => {
On ne peux pas specifier de structure dans la requete. Le code prend la structure dans `req.auth.credentials`.
Du coup on n'a pas a faire de test 404. Qu'en penses-tu ?

2022-08-23 14:03 UTC, CorentinMartinot commented on tests/integration/taxCertificates.test.js
>      it('should not create a new tax certificate if year is invalid', async () => {
done

2022-08-23 14:03 UTC, CorentinMartinot commented on tests/integration/taxCertificates.test.js
> +      { name: 'helper', expectedCode: 403, erp: true },
done

2022-08-23 14:03 UTC, CorentinMartinot commented on tests/integration/thirdPartyPayers.test.js
>      it('should return a 404 error if user is not from the same company', async () => {
done

2022-08-23 14:03 UTC, CorentinMartinot commented on tests/integration/thirdPartyPayers.test.js
>      it('should return a 404 error if user is not from the same company', async () => {
done

2022-08-23 14:45 UTC, CorentinMartinot commented on tests/integration/drive.test.js
> +  describe('NO_ROLE_NO_COMPANY', () => {
En testant avec le file-uploader de la modale de creation d'absence (ex: "accident du travail). 
La requête a l'air de contenir le champ `type`. Du coup si je supprime le champ en entrée de route, ça casse la fonctionnalité d'upload. 

J'ai l'impression qu'il faut laisser comme ça du coup. QU'en penses-tu ?

2022-08-23 15:30 UTC, sophiemoustard commented on tests/integration/drive.test.js
> +  describe('NO_ROLE_NO_COMPANY', () => {
dac !

2022-08-23 15:30 UTC, sophiemoustard commented on tests/integration/thirdPartyPayers.test.js
>      it('should get company third party payers', async () => {
ah oui bien vu !

2022-08-23 15:39 UTC, sophiemoustard commented on tests/integration/drive.test.js
> +  describe('NO_ROLE_NO_COMPANY', () => {
dans ce cas tu peux le rajouter dans les cas de test requis peut etre ? c'est en ne le voyant pas que je suis allée creuser son utilisation
```
const missingParams = ['file', 'fileName'];
    missingParams.forEach((param) => {
```

2022-08-23 15:44 UTC, sophiemoustard requested changes

2022-08-23 16:40 UTC, CorentinMartinot commented on tests/integration/thirdPartyPayers.test.js
>        const thirdPartyPayerCount = await ThirdPartyPayer.countDocuments({ company: authCompany._id }).lean();
done

2022-08-23 16:40 UTC, CorentinMartinot commented on tests/integration/taxCertificates.test.js
>  describe('TAX CERTIFICATES - DELETE /', () => {
done

2022-08-23 16:40 UTC, CorentinMartinot commented on tests/integration/thirdPartyPayers.test.js
> +describe('GET /thirdpartypayers', () => {
done

2022-08-23 16:40 UTC, CorentinMartinot commented on tests/integration/taxCertificates.test.js
> +      { name: 'vendor_admin', expectedCode: 403, erp: false },
done

2022-08-23 16:40 UTC, CorentinMartinot commented on tests/integration/drive.test.js
> +  describe('NO_ROLE_NO_COMPANY', () => {
done

2022-08-24 07:21 UTC, sophiemoustard approved these changes

2022-08-24 07:21 UTC, merged