Com 2989
sophiemoustard/compani-api pull request #2025
Opened 2022-09-14 11:39 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [x] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [x] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] ~~J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)~~
- [ ] ~~J'ai ajouté un modèle spécifique à une structure ~~
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] ~~J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile~~
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours => il faudra forcer la MAJ
- [ ] ~~Mes changements impactent l'application erp~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : mobile/vendeur/client rof/coach/admin/formateur

- Cas d'usage : je peux accéder à une formation dont je suis le formateur + je peux toujours accéder aux autres formations

- Comment tester ? :
MOBILE
- je peux accéder au profil d'une formation dont je suis le stagiaire (interface apprenant) et :
  - je peux faire les activités => je suis redirigé vers le profile de la formation (apprenant)
  - je peux accéder à la page à propos => je suis redirigé vers le profile de la formation (apprenant)
- je peux accéder au profil d'une formation dont je suis le formateur (interface formateur) et :
  - je peux faire les activités => je suis redirigé vers le profil de la formation (formateur)
  - je peux accéder à la page à propos => je suis redirigé vers le profil de la formation (formateur)
  - les historiques d'activités ne s'affichent pas
WEBAPP
- je peux accéder au profile d'une formation blended et elearning côté vendeur et client

_Si tu as lu cette description, pense à réagir avec un :eye:_

2022-09-14 11:46 UTC, sophiemoustard commented
As tu mis dans le doc de MEP qu'il faut forcer la MAJ
S'il faut forcer la maj il faudra aussi fusionner la branche dev de l'api dans master avant la MEP mobile non ? l'as tu noté sur le doc de deploiement mobile ?

2022-09-14 12:00 UTC, sophiemoustard commented on src/helpers/courses.js
> +  if (query.action === OPERATIONS) {
tu peux faire une ternaire non ?

2022-09-14 12:00 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
pour quoi a-t-on besoin de la progression ?

2022-09-14 12:00 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +  let getCourseForPedagogy;
si on suit la logique de la PR de Corentin, il ne faudrait pas mocker cette methode ici et se dire que ce test sur `getCourse` permet de tester les 2 methodes `getCourseForOperations` et `getCourseForPedagogy`

2022-09-14 12:00 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +  let getCourseForPedagogy;
a moins que tu voyais la fusion des tests dans le prochain ticket ?

2022-09-14 12:43 UTC, ulysseferreira commented on src/helpers/courses.js
> +  if (query.action === OPERATIONS) {
done

2022-09-14 12:45 UTC, ulysseferreira commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
pour la progression presentielle, ça casse dans LiveCelle côté mobile si on l'a pas et je me suis dit qu'en soit ça pouvait être pas mal de voir quelles étapes sont passées même en tant que formateurs

2022-09-14 12:47 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
on n'affiche pas la progression coté formateur donc je pense qu'on n'en a pas besoin ... 🤔

2022-09-14 12:51 UTC, sophiemoustard requested changes

2022-09-14 12:51 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
et du coup plus haut, tu peux conditionner le `{ path: 'activityHistories', match: { user: credentials._id } },` au cas apprenant uniquement, ca ne sert a rien de le faire pour le formateur

2022-09-14 12:52 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
et du coup plus haut, tu peux conditionner le { path: 'activityHistories', match: { user: credentials._id } }, au cas apprenant uniquement, ca ne sert a rien de le faire pour le formateur

2022-09-14 12:53 UTC, ulysseferreira commented on src/helpers/courses.js
> +    return exports.formatCourseWithProgress({
ok donc faut faire une refacto de livecell et calendaricon du coup

2022-09-14 13:14 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +  let getCourseForPedagogy;
c'était en prévision de quand on allait rapatrier courses/{id}/user dans courses/{id} ça me paraissait chargé d'avoir tout dans getCourse. C'est corrigé

2022-09-14 13:14 UTC, ulysseferreira commented on src/helpers/courses.js
>    if (!course.subProgram.isStrictlyELearning) {
done

2022-09-15 13:32 UTC, sophiemoustard approved these changes

2022-09-15 15:44 UTC, sophiemoustard approved these changes

2022-09-15 16:34 UTC, CorentinMartinot approved these changes

2022-09-15 16:43 UTC, merged