Com 3203
sophiemoustard/compani-api pull request #2033
Opened 2022-09-26 12:06 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles. -np
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

---

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : ETQ ROF/ Admin 

- Cas d'usage : Je peux creer une formation INTRA

- Comment tester ? : 
   - passer par Postman - envoyer la requete suivante : `POST /{{API_LINK}}/courses` avec les champs suivants définis dans le payload: 
        - type
        - company
        - subProgram
        - salesRepresentative
        - maxTrainees 
  - verifier  que l'objet a bien ete créé en bdd

_Si tu as lu cette description, pense à réagir avec un :eye:_

2022-09-26 15:53 UTC, manonpalin commented on src/repositories/CourseRepository.js
> +    { path: 'companies', select: 'name' },
Tu as raison, comme on ne peut pas tester cette modif, je la retire. On la fera au moment ou on travaillera sur la route de recuperation des formations

2022-09-26 15:59 UTC, manonpalin commented on src/routes/courses.js
> +        pre: [{ method: authorizeCourseCreation }],
Pour les formations inter, le champ companies sera vide a la creation de la formation et c'est au moment ou on ajoutera de stagiaires que le champ se remplira petit a petit. 
On s'est posé la question avec Sophie, et on trouvait plus logique de passer le champ company ici - comme on fait lors de l'ajout d'un stagiaire, on passe `trainee` dans le payload et on l'ajoute au tableau `trainees` en bdd

2022-09-26 16:27 UTC, cmolle commented on src/routes/courses.js
> +        pre: [{ method: authorizeCourseCreation }],
Vu ensemble : il est prévu de rattacher directement les structures aux formations (sans passer par les stagiaires). Comme pour l'instant c'est plutot prévu à l'édition qu'à la création, et que du coup pour l'instant le champs n'est autorisé (et requis) que pour l'intra, il est plus logique que le champs s'appelle `company`

2022-09-26 16:28 UTC, cmolle approved these changes

2022-09-27 09:08 UTC, sophiemoustard requested changes

2022-09-27 09:29 UTC, manonpalin commented on src/routes/preHandlers/courses.js
> +    if (!companyExists) throw Boom.notFound();
c'est corrigé

2022-09-27 09:29 UTC, manonpalin commented on src/helpers/courses.js
> +  const course = await (new Course(coursePayload)).save();
C'est corrigé

2022-09-27 12:55 UTC, sophiemoustard approved these changes

2022-09-27 12:55 UTC, merged