COM-3368-2 fix company problem ?
sophiemoustard/compani-api pull request #2157
Opened 2023-01-16 15:05 UTC by cmolle

<details><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [x] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours TODO chloe
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-01-16 15:39 UTC, sophiemoustard requested changes

2023-01-16 15:39 UTC, sophiemoustard commented on src/helpers/users.js
> +    .populate({ path: 'company', populate: { path: 'company' }, select: 'name startDate endDate' })
car le premier `populate` sur le champ `company` récupère en fait un `userCompany` et c'est le second qui récupère véritablement la structure et donc le nom qui va avec

2023-01-16 15:39 UTC, sophiemoustard commented on src/helpers/users.js
> +    .populate({ path: 'company', populate: { path: 'company' }, select: 'name startDate endDate' })
et du coup on pourrait le simplifier en `{ path: 'company', populate: { path: 'company', select: 'name' } }`

2023-01-16 15:39 UTC, sophiemoustard commented on src/helpers/users.js
> +    .populate({ path: 'company', select: 'company startDate endDate' })
ici je ne pense pas que le `select: company` soit necessaire non plus car le posthook le transforme a posteriori donc en partique on ne garde que l'id de la structure avec ou sans select

2023-01-16 15:39 UTC, sophiemoustard commented on src/models/User.js
> +    if (currentUserCompany) doc.company = currentUserCompany.company;
ici si on ne trouve pas de structure dans la liste, le champ `company` va rester une liste de `userCompany` non ?
que pense tu de mettre un `else` ici pour mettre a `null` ou `undefined` ou supprimer le champ `company` de l'objet ?

2023-01-16 15:39 UTC, sophiemoustard commented on src/models/User.js
> +      if (currentUserCompany) doc.company = currentUserCompany;
idem

2023-01-16 15:43 UTC, cmolle commented on src/helpers/users.js
> +    .populate({ path: 'company', populate: { path: 'company' }, select: 'name startDate endDate' })
Bien vu !

2023-01-16 15:45 UTC, cmolle commented on src/models/User.js
> +    if (currentUserCompany) doc.company = currentUserCompany.company;
Ha mais oui bien vu ! C'etait l'idee derriere ce if d'avoir null sinon mais je n'avais pas pense au fait qu'il fallait le forcer ^^

2023-01-17 09:33 UTC, ulysseferreira commented on tests/integration/seed/usersSeed.js
> +    endDate: '2022-12-30T22:59:59.999Z',
il y a une incohérence de seed sur cet utilisateur, il a un userCompany depuis le 2019-01-01T08:00:00.000Z sur authCompany un peu plus haut et ici il a un deuxième userCompany, aussi sur authCompany, avec une endDate alors que le précédent n'a pas de endDate

2023-01-17 09:33 UTC, ulysseferreira commented on tests/integration/seed/usersSeed.js
> +    endDate: '2022-12-29T22:59:59.999Z',
idem, il a même 3 usercompanies imbriqués

2023-01-17 09:33 UTC, ulysseferreira commented on tests/integration/seed/eventsSeed.js
> +  { _id: new ObjectId(), user: auxiliariesIds[0], company: authCompany._id, startDate: '2019-01-01T23:00:00.000Z' },
ce seed est imbriqué dans le précédent

2023-01-17 09:33 UTC, ulysseferreira commented on tests/seed/authUsersSeed.js
>    // old inactive user companies
cette mention ne sert plus, elle peut être mise au-dessus des userCompany avec une endDate en revanche (ils peuvent être regroupés ensemble pour plus de lisibilité)

2023-01-17 09:33 UTC, ulysseferreira commented on src/models/User.js
> +  if (currentUserCompany) doc.company = currentUserCompany.company;
est-ce-qu'on peut simplifier ça en doc.company = currentUserCompany .company || null ou ça ne fonctionne pas ?

2023-01-17 10:37 UTC, CorentinMartinot approved these changes

2023-01-17 13:19 UTC, ulysseferreira approved these changes

2023-01-17 13:19 UTC, merged