Com 3384
sophiemoustard/compani-api pull request #2173
Opened 2023-01-30 13:02 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires -np
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-01-30 15:13 UTC, cmolle reviewed
Que penses-tu d'ajouter une action dans le `package.json` `test:seeds` pour pouvoir lancer plus facilement cette verif ? 

Je n'ai pas de super solutions, mais je me dis que ca risque d'etre un peu complique de suivre quels modeles on a fait 🤔 Je me demande s'il ne faudrait pas creer une page notion ou ajouter des commentaires. Qu'en penses-tu ?

2023-01-30 15:13 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        it('should return false if user already has a company', () => {
A voir d'ailleurs en y re-reflechissant si on veut garder le "should" ou si ici comme ce sont des tests assez different on met pas plutot "all users should have now or in the future a company`

2023-01-30 15:19 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +const { CompaniDate } = require('../../../src/helpers/dates/companiDates');
done

2023-01-30 15:20 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +const { descendingSortBy, ascendingSortBy } = require('../../../src/helpers/dates/utils');
done

2023-01-30 15:21 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +      });
done

2023-01-30 15:21 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              CompaniDate(contract.startDate).isAfter(uc.startDate)
done

2023-01-30 15:22 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              CompaniDate(contract.startDate).isAfter(uc.startDate)
done

2023-01-30 15:22 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          [COACH, ADMIN_CLIENT].includes(get(c.companyRepresentative, 'role.client.name')));
done

2023-01-30 15:23 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should return true if companyRepresentative is well defined', () => {
done

2023-01-30 15:23 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                    CompaniDate(ch.createdAt).isAfter(uc.startDate)
done

2023-01-30 15:24 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                .every((ch, i) => {
je teste aussi que les DELETION soient après la startDate, il n'y a pas de raison que l'ajout ou la supression à la formation soit avant l'ajout à la structure, non ?

2023-01-30 15:26 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              const isTraineeInCompanyBeforeAction = traineeCourseHistories.sort(ascendingSortBy('createdAt'))
c'est pas par rapport au détachement, c'est par rapport au rattachement, dans tous les cas il faut que le rattachement à la structure ait été fait avant l'ajout/suppression de la formation

2023-01-30 15:26 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                  (!uc.endDate || CompaniDate(lastHistory.createdAt).isBefore(uc.endDate))
done

2023-01-30 15:26 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            })
done

2023-01-30 15:27 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should return true if every helper has a matching user and company', () => {
done

2023-01-30 15:27 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              UtilsHelper.areObjectIdsEquals(uc.user, helper.user._id)
done

2023-01-30 15:27 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const doAuxiliariesAreInCompanyAtSectorHistoryStartDate = sectorHistoryList
done

2023-01-30 15:28 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              CompaniDate(sh.startDate).isAfter(uc.startDate)
done

2023-01-30 15:29 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          await seeds.populateDB();
c'est un oubli

2023-01-30 15:29 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          await seeds.populateDB();
idem

2023-01-30 15:34 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should return false if user already has a company', () => {
done

2023-01-30 15:41 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .populate({ path: 'user', select: '_id', populate: { path: 'company' } })
done

2023-01-30 15:43 UTC, ulysseferreira commented on tests/integration/seed/usersSeed.js
> +    createdAt: '2018-10-10T10:00:00.000Z',
done

2023-01-30 16:55 UTC, cmolle commented on src/helpers/userCompanies.js
> +exports.getCurrentAndFutureCompanies = userCompanyList => compact(userCompanyList
Il faudra rebase feature-detachment suite a la fusion de cette pr et faire bien attention car on a fait la modif aussi sur feature-detachmnet

2023-01-30 16:55 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +              UserCompaniesHelper.getCurrentAndFutureCompanies(get(request.user, 'userCompanyList')).length
Ici si l'utilisateur n'a pas de `userCompanyList` ca risque de casser `getCurrentAndFutureCompanies` non ? J'ai l'impression qu'on n'y verifie pas que le tableau est bien defini. Que penses-tu de soit le verifier dans `getCurrentAndFutureCompanies` soit de renvoyer ici `get(request.user, 'userCompanyList') || []` ?

2023-01-30 16:55 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            UtilsHelper.areObjectIdsEquals(c.companyRepresentative.company, c.companies[0]));
indentation

2023-01-30 16:55 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +                .every((ch, i) => {
Ha oui bien vu ! 
Pour rendre le test un peu plus clair que penses-tu de: 
- verifier que les deletions sont toujours apres une addition 
- que les additions sont bien faites seulement apres le rattachement d'un stagiaire a une structure
?

2023-01-30 16:56 UTC, cmolle commented
> Je n'ai pas de super solutions, mais je me dis que ca risque d'etre un peu complique de suivre quels modeles on a fait 🤔 Je me demande s'il ne faudrait pas creer une page notion ou ajouter des commentaires. Qu'en penses-tu ?

up sur ce questionnement

2023-01-30 17:10 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            UtilsHelper.areObjectIdsEquals(c.companyRepresentative.company, c.companies[0]));
done

2023-01-30 17:10 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +                .every((ch, i) => {
Vu ensemble : a voir si je trouve vraiment une facon d'ecrire plus lisible demain, sinon on garde comme ca et on ajoute juste que ceux %1 doivent etre des deletions

2023-01-31 08:36 UTC, sophiemoustard commented
quand on en avait parlé, il me semble q'on c'etait dit qu'on pourrait valider les seeds au debut de chaque fichier de tests comme on fait pour verifier qu'on est bien en environnement de test. qu'est ce qui vous a fait changer de stratégie ?

2023-01-31 08:38 UTC, sophiemoustard requested changes

2023-01-31 08:38 UTC, sophiemoustard commented on tests/integration/userCompanies.test.js
> +      const userCompanyId = userCompanies[6]._id.toHexString();
pourquoi tu les as tous decaler d'un ?

2023-02-01 13:48 UTC, ulysseferreira commented on tests/integration/userCompanies.test.js
> +      const userCompanyId = userCompanies[6]._id.toHexString();
parce qu'on a supprimé un userCompany des seeds

2023-02-01 17:45 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            .setOptions({ allCompanies: true })
Il faudrait se noter quelque part de revenir sur ca une fois qu'on aura fusionner la branche de fonctionnalité et donc qu'on aura modifié `userCompanyList`

2023-02-01 17:45 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            .every(course => !course.companies || course.trainees
Je me demande si ce `!course.companies` est utile, j'ai l'impression que par defaut en bdd on a `[]` pour le champs `companies. Je pense qu'on peut ne rien mettre car j'ai l'impression que le `every` renvoie `true` si il n'y a pas d'element dans el tableau

2023-02-01 17:45 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +                .every((ch, i) => {
Finalement ca me va de garder la meme logique. Que dis-tu de changer legerement le formattage pour avoir 

```
                .every((ch, i) => {
                  if (i % 2 === 0) {
                      return ch.action === TRAINEE_ADDITION && ch.trainee.userCompanyList
                        .some(uc => UtilsHelper.areObjectIdsEquals(uc.company, ch.company) &&
                          CompaniDate(ch.createdAt).isAfter(uc.startDate)
                    );
                  } else { 
                      return ch.action === TRAINEE_DELETION;
                  }
                });
```

2023-02-02 09:20 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .setOptions({ allCompanies: true })
on n'en aura plus besoin ?

2023-02-02 09:24 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .every(course => !course.companies || course.trainees
non pas pour les formations elearning

2023-02-02 09:27 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                );
done

2023-02-02 09:28 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +                UtilsHelper.areObjectIdsEquals(uc.user, helper.user._id)
est ce que cette ligne est utile ?
tu regardes deja les `userCompanyList` dans `helper.user` donc a priori ces `uc.user` sont tous egaux entre eux et valent `helper.user._id` sinon le problème n'est pas tant dans les seed mais dans le virtual

2023-02-02 09:28 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +                      CompaniDate(ch.createdAt).isAfter(uc.startDate)
pou verifier que l
apprenant est bien dans la structure il faut que tu regardes aussi par rapport a la `endDate` non ?

2023-02-02 09:46 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                { path: 'company', select: 'user company startDate' },
done

2023-02-02 09:48 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                UtilsHelper.areObjectIdsEquals(uc.user, helper.user._id)
done

2023-02-02 09:50 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +                      CompaniDate(ch.createdAt).isAfter(uc.startDate)
non parce que tu peux avoir désinscrit le stagiaire de la formation puis détaché le stagiaire à une date antérieure aux historiques sur la formation

2023-02-02 09:55 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +                CompaniDate(sh.startDate).isAfter(uc.startDate)
et ici il ne faut pas verifier par rapport a la endDate aussi ?

2023-02-02 09:55 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +              ],
tu peux mettre sur une ligne du coup

2023-02-02 10:50 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            .setOptions({ allCompanies: true })
@sophiemoustard ha oui bien vu je peux l'ajouter en point particulier de cette branche :)
 
 @ulysseferreira  Non, on a modifié `userCompanyList` qui renvoie toujours toutes les infos

2023-02-02 10:54 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            .every(course => !course.companies || course.trainees
Que penses-tu de filtrer du coup `courseList` pour ne conserver que les formations mixtes ? ce test ne verifie rien dans tous les cas pour les formations eLearning si ? 
On pourrait aussi ajouter un test d'ailleurs pour verifier que tous les stagiaires inscrits a une formation eLearning specifique a une entreprise a un `userCompany` pour cette entreprise (passe ou courant), qu'en penses-tu ?

2023-02-02 10:58 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +                .every((ch, i) => {
@ulysseferreira pense a mettre ton nom quand tu modifes commentaire plutot que de repondre avec un nouveau ^^ J'ai pris du temps a comprendre qui disait quoi sur ce commentaire ^^ 

J'ai l'impression que cette condition `UtilsHelper.areObjectIdsEquals(uc.company, ch.company) &&
                          CompaniDate(ch.createdAt).isAfter(uc.startDate)` est suffisante pour verifier que la date de creation de l'historique est bien apres la date d'attachement non  ?

2023-02-02 13:00 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .every(course => !course.companies || course.trainees
ah oui bien vu

2023-02-02 14:06 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              ],
done

2023-02-02 14:17 UTC, cmolle approved these changes

2023-02-03 07:49 UTC, sophiemoustard approved these changes

2023-02-03 07:49 UTC, merged