Com 3354
sophiemoustard/compani-api pull request #2179
Opened 2023-02-08 09:30 UTC by cmolle

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration -np
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens - mise a jour des tests cote webapp
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [x] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-02-09 13:29 UTC, ulysseferreira commented on tests/integration/users.test.js
> +        ...pick(usersSeedList[0], fieldsToPick),
y a pas company dans fieldsToPick dans ce cas là ?

2023-02-09 13:29 UTC, ulysseferreira commented on tests/integration/users.test.js
>    describe('Other roles', () => {
on n'a pas de test pour vérifier ce qu'on reçoit pour un apprenant avec une endDate dans le futur ?

2023-02-09 15:00 UTC, cmolle commented on tests/integration/users.test.js
> +        ...pick(usersSeedList[0], fieldsToPick),
Si il est juste en dessous :)

2023-02-09 15:03 UTC, cmolle commented on tests/integration/users.test.js
>    describe('Other roles', () => {
Je me suis posee la question de faire des tests exhaustifs dans les tests d'integratino mais ca me semblait en doublon par rapport aux tests unitaires 🤔 Qu'en penses-tu ?

2023-02-10 10:06 UTC, ulysseferreira approved these changes

2023-02-10 16:42 UTC, sophiemoustard commented on src/helpers/users.js
> +        .filter(uc => (loggedUserHasVendorRole ? true : UtilsHelper.areObjectIdsEquals(companyId, uc.company)))
ici tu peux simplifier en
```filter(uc => (loggedUserHasVendorRole || UtilsHelper.areObjectIdsEquals(companyId,uc.company)))```

2023-02-13 08:24 UTC, sophiemoustard requested changes

2023-02-13 08:24 UTC, sophiemoustard commented on src/helpers/users.js
> +        pick(targetUser.userCompanyList.sort(descendingSortBy('startDate'))[0], commonFieldsToPick.userCompany),
attention ton `sort` ici modifie en reference l'objet `targetUser`

2023-02-13 08:24 UTC, sophiemoustard commented on src/helpers/users.js
> +        pick(targetUser.userCompanyList.sort(descendingSortBy('startDate'))[0], commonFieldsToPick.userCompany),
et tu peux utiliser `getFirstVersion` d'ailleurs

2023-02-13 08:24 UTC, sophiemoustard commented on src/helpers/users.js
> +    };
globalement je trouve la methode `exists` un peu longue et plus compliquée à lire..
J'ai essayé de changer un peu ces lignes, qu'en penses tu ?

```
const doesEveryUserCompanyHasEndDate = targetUser.userCompanyList.every(uc => uc.endDate);
const canReadInfo = loggedUserHasVendorRole || coachCanReadAllUserInfo ||
  (loggedUserHasCoachRights && doesEveryUserCompanyHasEndDate);

if (canReadInfo) {
  const canReadAllCompanies = loggedUserHasVendorRole || coachCanReadAllUserInfo;
  const userCompanyList = canReadAllCompanies
    ? targetUser.userCompanyList
      .filter(uc => (loggedUserHasVendorRole || UtilsHelper.areObjectIdsEquals(companyId, uc.company)))
    : [UtilsHelper.getFirstVersion(targetUser.userCompanyList)];
  const userFieldsToPick = ['_id', 'local.email', 'identity.firstname', 'identity.lastname', 'contact.phone', 'role'];

  const formattedUser = {
    ...pick(targetUser, [...userFieldsToPick, canReadAllCompanies && 'company']),
    userCompanyList: userCompanyList.map(uc => (pick(uc, ['company', 'startDate', 'endDate']))),
  };

  return { exists: true, user: formattedUser };
}
```

2023-02-13 08:24 UTC, sophiemoustard commented on src/helpers/users.js
> +    };
ou meme 
```
return {
    exists: true,
    user: {
      ...pick(targetUser, [...userFieldsToPick, canReadAllCompanies && 'company']),
      userCompanyList: userCompanyList.map(uc => (pick(uc, ['company', 'startDate', 'endDate']))),
    },
  };
```
pour la fin

2023-02-13 09:42 UTC, cmolle commented on src/helpers/users.js
> +    };
Je suis d'accord que cette methode est complique a lire :/ J'ai fait les modifications que tu proposais j'ai juste modifié la partie sur "canReadAllCompanies" car un le "coachCanReadAllInfo" ne peut pas avoir toutes les infos sur les anciennes enteprises, uniquement sur la sienne. Qu'en penses-tu ?

2023-02-13 10:44 UTC, sophiemoustard commented on src/helpers/users.js
> +    };
tu as raison

2023-02-13 10:45 UTC, sophiemoustard approved these changes

2023-02-13 11:28 UTC, merged