Com 3387
sophiemoustard/compani-api pull request #2182
Opened 2023-02-08 16:39 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [x] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [x] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-02-09 15:28 UTC, cmolle commented on tests/integration/questionnaireHistories.test.js
>        await QuestionnaireHistory.create(payload);
Qu'est-ce qui fait que tu as prefere faire ca plutot que d'ajouter un tel historique dans les seeds ?

2023-02-09 15:59 UTC, cmolle approved these changes

2023-02-09 16:43 UTC, ulysseferreira commented on tests/integration/questionnaireHistories.test.js
>        await QuestionnaireHistory.create(payload);
si je créé cet historique dans le seeds mes tests 200 ne passent plus

2023-02-10 07:15 UTC, cmolle commented on tests/integration/questionnaireHistories.test.js
>        await QuestionnaireHistory.create(payload);
Que penses-tu d'ajouter un historique similaire dans les seeds mais en changeant de trainee ? Il me semble qu'on s'etait dit qu'on adoptait plutot en bonne pratique de tout mettre dans les seeds plutot que d'en créer à la volée. Ici en plus, les seeds de questionnairehistory sont encore relativement courts.

2023-02-10 10:14 UTC, cmolle approved these changes

2023-02-13 09:14 UTC, sophiemoustard requested changes

2023-02-13 09:14 UTC, sophiemoustard commented on src/helpers/questionnaires.js
> +  const isVendorUser = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN].includes(get(credentials, 'role.vendor.name'));
isRofOrAdmin plutot ? car on ne prend pas en compte le role formateur ici

2023-02-13 09:31 UTC, ulysseferreira commented on src/helpers/questionnaireHistories.js
> +  const traineeCompanyAtCourseRegistration = traineesCompanyAtCourseRegistrationList[0].company;
done

2023-02-13 09:31 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +  const isVendorUser = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN].includes(get(credentials, 'role.vendor.name'));
done

2023-02-13 09:36 UTC, sophiemoustard approved these changes

2023-02-13 09:48 UTC, merged