COM-3358: display blended/elearning courses count from company
sophiemoustard/compani-api pull request #2197
Opened 2023-02-27 15:45 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration -np
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-02-28 09:21 UTC, manonpalin commented on src/helpers/users.js
> +        blendedCourseRegistrations[learner._id] = uniqBy(blendedCourseRegistrations[learner._id], 'course._id');
Que penses-tu de creer une constante pour eviter de réecrire deux fois `blendedCourseRegistrations[learner._id]`

2023-02-28 09:26 UTC, manonpalin commented on tests/unit/helpers/users.test.js
>      const usersWithVirtuals = [
Que penses-tu de renommer cette constante en learnerList ?

2023-02-28 09:27 UTC, manonpalin commented on tests/unit/helpers/users.test.js
> +    const query = { companies: [new ObjectId()] };
Pourquoi ce changement ?

2023-02-28 09:37 UTC, ulysseferreira commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
ce n'est pas une question d'interface, on veut aussi rentrer dans ce if pour le répertoire apprenants côté vendeur

2023-02-28 09:40 UTC, ulysseferreira commented on src/helpers/users.js
> +        blendedCourseRegistrations[learner._id] = uniqBy(blendedCourseRegistrations[learner._id], 'course._id');
tu verrais un truc comme ça ? 
```
const learnerRegistration = blendedCourseRegistrations[learner._id];
if (learnerRegistration) {
        blendedCourseRegistrations[learner._id] = learnerRegistration
          .sort(DatesUtilsHelper.descendingSortBy('createdAt'));
        blendedCourseRegistrations[learner._id] = uniqBy(learnerRegistration, 'course._id');
      } else {
        blendedCourseRegistrations[learner._id] = [];
      }
```
est-ce-que ça ne risque pas de prêter à confusion ?

2023-02-28 09:41 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
>      const usersWithVirtuals = [
done

2023-02-28 09:42 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +    const query = { companies: [new ObjectId()] };
parce que sinon je dois rajouter les éléments de test qui correspondent au `if (!Array.isArray(query.companies))` et que ça alourdit le test pour rien car on l'a déjà testé plus haut

2023-02-28 10:10 UTC, manonpalin commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
Ah oui tu as raison

2023-02-28 10:12 UTC, manonpalin commented on src/helpers/users.js
> +        blendedCourseRegistrations[learner._id] = uniqBy(blendedCourseRegistrations[learner._id], 'course._id');
Non plutot faire qqchose du genre: 
```
if (blendedCourseRegistrations[learner._id]) {
        const learnerRegistration = blendedCourseRegistrations[learner._id].sort(DatesUtilsHelper.descendingSortBy('createdAt'));
        blendedCourseRegistrations[learner._id] = uniqBy(learnerRegistration, 'course._id');
      } else {
        blendedCourseRegistrations[learner._id] = [];
      }
```

2023-02-28 10:56 UTC, ulysseferreira commented on src/helpers/users.js
> +        blendedCourseRegistrations[learner._id] = uniqBy(blendedCourseRegistrations[learner._id], 'course._id');
ah oui bien vu !

2023-02-28 12:50 UTC, manonpalin approved these changes

2023-02-28 14:19 UTC, cmolle commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
Quel est le lien entre la condition et le fait de calculer `blendedCoursesCount` et `eLearningCoursesCount` ? 
Que penses-tu de faire comme sur une pr precedente et de creer une constante pour cette condition vu que tu l'utilises ici et plus bas dans la creation de l'objet ?

2023-02-28 14:19 UTC, cmolle commented on src/helpers/users.js
> +    for (const learner of learnerList) {
Que penses-tu de créer deux methodes pour calculer `blendedCourseRegistrations` et `eLearningCoursesGroupedByTrainee` ? Ca nous obligera a parcourir deux fois learnerList donc a voir si ca augmente trop les performances mais je trouve que ce n'est pas facile de suivre les différents calculs en l'état :/

2023-02-28 14:28 UTC, ulysseferreira commented on src/helpers/users.js
> +const { groupBy } = require('lodash');
c'est une coquille

2023-02-28 14:33 UTC, ulysseferreira commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
en calculant les count pour query.companies quand c'est un tableau ça compliquait les choses pour les areObjectIdsEquals/doesArrayIncludeId de la fin, or query.companies est un tableau quand on veut récupérer les stagiaires potentiels et on n'a pas besoin de blendedCount et eLearningCount dans ce cas là. Donc ça permettait de faire d'une pierre de coup : éviter un calcul compliqué et coûteux et ne pas faire des appels coûteux pour calculer des variables pas utilisées.
Le bémol c'est que sur une formation intra on récupère les stagiaires potentiels avec query.company qui est un ObjectId donc dans ce cas là on rentre quand même dans le if et on fait le calcul alors qu'il ne sert pas mais c'était ça ou passer par une action/booléen et ça me paraissait un peu overkill

2023-02-28 14:33 UTC, ulysseferreira commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
mais du coup y a pas vraiment de cas spécifique où on utilise !Array.isArray(query.companies), tu as une idée de nom de constante du coup ?

2023-02-28 14:38 UTC, ulysseferreira commented on src/helpers/users.js
> +    for (const learner of learnerList) {
je suis pas trop pour faire 2 boucles, on perd déjà légèrement en performance avec cette refacto, si on multiplie à chaque fois par 2 le temps de calcul, plus on aura de stagiaires plus ça risque d'être coûteux en perf. Il y aurait pas une autre manière de faire pour éclaircir la boucle ?

2023-03-01 09:25 UTC, cmolle commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
Je me pose la question quand meme de l'action 🤔 C'est peut etre un peu overkill mais en meme temps je suis un peu perturbee que la condition soit assez décorélé avec pourquoi on calcule ces valeurs 🤔 
Au minimum je creerais une constante `shouldComputeCourseCountForTrainee` pour un peu plus de lisibilité, qu'en penses-tu ?

2023-03-01 09:40 UTC, cmolle commented on src/helpers/users.js
> +    for (const learner of learnerList) {
J'ai fait une proposition sur la branche COM-3358-test, est-ce que tu peux regarder et me dire ce que tu en penses ? On peut peut etre en parler de vive voix et voir comment trouver une orga qui nous paraitrait plus clair en fusionnant nos deux propositions ? :)

2023-03-01 09:46 UTC, cmolle commented on src/helpers/users.js
> +    for (const learner of learnerList) {
(J'ai pas retravaille les tests vu que c'est juste un proposition, il y en a quelques unitaires qui cassent mais ca me parait normal suite a mes changements)

2023-03-01 14:54 UTC, cmolle commented on src/helpers/users.js
> +  if (!Array.isArray(query.companies)) {
vu ensemble : on met une action

2023-03-01 14:57 UTC, cmolle commented on src/helpers/users.js
> +  let eLearningCoursesCountByTrainee = {};
Que penses-tu de faire un retour anticipe si on n'est pas  dans le cas DIRECTORY ? 
```
if (!isDirectory) return learnerList;
....
```

2023-03-01 17:16 UTC, ulysseferreira commented on src/helpers/users.js
> +  let eLearningCoursesCountByTrainee = {};
bien vu ! done

2023-03-02 07:42 UTC, cmolle commented on src/helpers/users.js
> +  if (!isDirectory) return learnerList.map(learner => ({ ...omit(learner, 'activityHistories') }));
Pas besoin de faire le omit du coup vu qu'on ne le popule pas dans le cas !isDirectory

2023-03-02 08:57 UTC, ulysseferreira commented on src/helpers/users.js
> +  if (!isDirectory) return learnerList.map(learner => ({ ...omit(learner, 'activityHistories') }));
done

2023-03-02 09:04 UTC, cmolle approved these changes

2023-03-02 13:36 UTC, manonpalin commented on src/helpers/users.js
> +const computeCoursesCountByTrainees = async (learnerList, company) => {
Sans s plutot non ?

2023-03-02 13:38 UTC, manonpalin commented on src/helpers/users.js
> +        await computeCoursesCountByTrainees(learnerList, query.companies);
on formatte plutot comme suit non: 
```
  const {
    eLearningCoursesCountByTrainee,
    blendedCoursesCountByTrainee,
  } = await computeCoursesCountByTrainees(learnerList, query.companies);
```

2023-03-02 13:50 UTC, manonpalin commented on src/helpers/users.js
> +  const traineesCurrentRegistrationList = blendedCourseRegistrationHistoriesForTrainees
Pourquoi current ?

2023-03-02 13:52 UTC, ulysseferreira commented on src/helpers/users.js
> +const computeCoursesCountByTrainees = async (learnerList, company) => {
done

2023-03-02 13:53 UTC, ulysseferreira commented on src/helpers/users.js
> +        await computeCoursesCountByTrainees(learnerList, query.companies);
done

2023-03-02 13:54 UTC, ulysseferreira commented on src/helpers/users.js
> +  const traineesCurrentRegistrationList = blendedCourseRegistrationHistoriesForTrainees
done

2023-03-03 08:28 UTC, sophiemoustard commented on src/helpers/users.js
> +    .flat();
je pense que la tu peux faire directement `.flatMap(course => course.trainees.map(trainee => ({ trainee, course })));`

2023-03-03 08:36 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +         users[1].activityHistories[0],
sur une ligne

2023-03-03 08:40 UTC, sophiemoustard requested changes

2023-03-03 08:40 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +        },
idem

2023-03-03 08:40 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +         users[1].activityHistories[0],
idem

2023-03-03 09:07 UTC, ulysseferreira commented on src/helpers/users.js
> +    .flat();
done

2023-03-03 09:09 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +         users[1].activityHistories[0],
done

2023-03-03 09:09 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +        },
done

2023-03-03 09:09 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +         users[1].activityHistories[0],
done

2023-03-03 09:42 UTC, sophiemoustard approved these changes

2023-03-03 10:45 UTC, merged