Com 3460
sophiemoustard/compani-api pull request #2232
Opened 2023-05-23 14:28 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-05-23 15:10 UTC, cmolle commented on tests/integration/holdings.test.js
> +        payload: {},
Ici que penses-tu d'ajouter une adresse ? Pour etre sur de bien verifier que c'est le nom qui est manquant et pas un autre champs

2023-05-23 15:43 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +        payload: {},
done

2023-05-24 06:41 UTC, sophiemoustard requested changes

2023-05-24 06:41 UTC, sophiemoustard commented on tests/integration/holdings.test.js
> +      const holdingsBefore = await Holding.find().lean();
tu peux faire un `countDocuments`

2023-05-24 06:41 UTC, sophiemoustard commented on tests/integration/holdings.test.js
> +describe('HOLDINGS ROUTES - GET /holdings', () => {
tu ne fais pas les tests 403 pour cette route ?

2023-05-24 08:55 UTC, ulysseferreira commented on src/models/Holding.js
> +  address: { type: mongoose.Schema(addressSchemaDefinition, { _id: false, id: false }) },
vu avec Sophie, une string

2023-05-24 08:57 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +      const holdingsBefore = await Holding.find().lean();
done

2023-05-24 08:58 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +describe('HOLDINGS ROUTES - GET /holdings', () => {
done

2023-05-24 10:01 UTC, cmolle commented on tests/integration/holdings.test.js
> +const { expect } = require('expect');
A toi de voir ce qui est le mieux. :) 
Mais je pense que si on ne le fait pas dans les tickets de creation de collection il faut prendre l'habitude de creer les ticket de verif de seeds qui vont avec. 
Qu'en penses-tu ?

2023-05-24 10:15 UTC, cmolle commented on tests/integration/seed/holdingsSeed.js
> +};
Sur une ligne

2023-05-24 10:38 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +const { expect } = require('expect');
je les ai rajouté à la liste des modèles dans le projet cohérence, je prendrai Holding et CompanyHolding la semaine prochaine comme strat à faire pour le projet cohérence

2023-05-24 10:40 UTC, ulysseferreira commented on tests/integration/seed/holdingsSeed.js
> +};
done

2023-05-24 12:33 UTC, cmolle approved these changes

2023-05-24 12:39 UTC, cmolle commented
La pagination ne fonctionne pas, il ne se passe rien quand on appuie sur ">" ou "tous"

2023-05-24 12:40 UTC, cmolle approved these changes

2023-05-24 12:52 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +const { expect } = require('expect');
à l'avenir quand le chantier cohérence des seeds sera fini je suis d'accord qu'il faudra l'incorporer dans le chantier courant, après là (et c'est un sentiment purement perso) je m'y retrouve mieux de l'avoir dans le projet cohérence, je trouve ça plus clair + ça évite de se retrouver en parallèle avec ce ticket + un ticket cohérence des seeds ce qui peut être une galère en terme de rebase, au moins en le mettant dans le projet cohérence y a pas ce risque

2023-05-24 13:02 UTC, cmolle commented on tests/integration/holdings.test.js
> +const { expect } = require('expect');
Ok :)

2023-05-24 13:16 UTC, sophiemoustard approved these changes

2023-05-24 13:16 UTC, merged