Com 3468
sophiemoustard/compani-api pull request #2238
Opened 2023-06-01 15:29 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires -np
- [ ] J'ai codé les tests d'intégration -np
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            .populate({ path: 'questionnaireAnswersList.card', select: 'template', transform: doc => (doc || null) })
Que penses-tu de creer une methode pour ce transform en hatu de ce fichier ? Je me dis que si un jour on veut autre chose que ce `doc || null` il va falloir le changer a vraiment beaucoup d'endroit ^^'

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            const steps = stepList.filter(s => UtilsHelper.doesArrayIncludeId(s.activities, ah.activity._id));
Que penses-tu de grouper les étapes par activite ?

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            const subPrograms = subProgramList
Idem ici on pourrait grouper les sous-programmes par etape

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if score is greater or equal to quizz cards count in activity', () => {
score is lower or equal ?

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if score is greater or equal to quizz cards count in activity', () => {
Idem pour le nom de la variable

2023-06-01 15:46 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        });
Que penses-tu de les fusionner en un seul test vu qu'ils sont tres similaire ?

2023-06-02 06:38 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +            const steps = stepList.filter(s => UtilsHelper.doesArrayIncludeId(s.activities, ah.activity._id));
comme `activities` est de type `Array` dans le model `Step` pour grouper il faut d'abord que tu transformes un peu la liste
J'avais fait comme ca pour grouper les formations par stagiaire dans un script `const coursesByTrainee = groupBy(courses.flatMap(c => c.trainees.map(t => ({ ...c, trainees: t }))), 'trainees');` si ca peut t'inspirer

2023-06-02 06:50 UTC, sophiemoustard requested changes

2023-06-02 06:50 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +              return ah.questionnaireAnswersList.some(qal => UtilsHelper.areObjectIdsEquals(c._id, qal.card._id));
tu peux simplifier en `return !c.isMandatory || ah.questionnaireAnswersList.some(..)`

2023-06-02 06:50 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +              return false;
tu peux mettre directement `return (!quizzCardsCount && !has(ah, 'score')) || ah.score <= quizzCardsCount;` qu'en penses tu ?

2023-06-02 06:50 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +              .some(qal => !UtilsHelper.doesArrayIncludeId(ah.activity.cards.map(c => c._id), qal.card._id)));
pour eviter de refaire le `map` pour quand reponse, tu peux faire comme suit qu'en penses tu ?
```
const someCardsAreNotInActivities = activityHistoryList.some((ah) => {
  const cardIds = ah.activity.cards.map(c => c._id);
  return ah.questionnaireAnswersList.some(qal => !UtilsHelper.doesArrayIncludeId(cardIds, qal.card._id));
});
```

2023-06-02 06:50 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every course exists', () => {
`and is blended ` ?

2023-06-02 06:50 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +              CompaniDate(cs.startDate).startOf('day').isSame(CompaniDate(cs.endDate).startOf('day')));
tu peux utiliser le 2eme argument de `isSame` qu'en pense tu ? `CompaniDate(cs.startDate).isSame(CompaniDate(cs.endDate), DAY));`

2023-06-02 08:10 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .populate({ path: 'questionnaireAnswersList.card', select: 'template', transform: doc => (doc || null) })
done

2023-06-02 08:11 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if score is greater or equal to quizz cards count in activity', () => {
done

2023-06-02 08:13 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        });
done

2023-06-02 08:14 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              return ah.questionnaireAnswersList.some(qal => UtilsHelper.areObjectIdsEquals(c._id, qal.card._id));
done

2023-06-02 08:15 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              return false;
done

2023-06-02 08:17 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              .some(qal => !UtilsHelper.doesArrayIncludeId(ah.activity.cards.map(c => c._id), qal.card._id)));
done

2023-06-02 08:17 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every course exists', () => {
done

2023-06-02 08:21 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +              CompaniDate(cs.startDate).startOf('day').isSame(CompaniDate(cs.endDate).startOf('day')));
bien vu

2023-06-02 08:42 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            const steps = stepList.filter(s => UtilsHelper.doesArrayIncludeId(s.activities, ah.activity._id));
done

2023-06-02 08:42 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            const subPrograms = subProgramList
done

2023-06-02 09:11 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if user is registered to a course with the activity #tag', async () => {
tag a supprime

2023-06-02 09:11 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +            );
Il faudrait faire le groupement en dehors de la boucle `activityHistoryList.every`

2023-06-02 09:22 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if user is registered to a course with the activity #tag', async () => {
done

2023-06-02 09:24 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            );
done

2023-06-02 10:23 UTC, cmolle approved these changes

2023-06-02 12:52 UTC, merged