Com 3494
sophiemoustard/compani-api pull request #2255
Opened 2023-06-28 14:34 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires -np
- [ ] J'ai codé les tests d'intégration -np
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-06-29 13:28 UTC, manonpalin commented on tests/integration/seed/courseBillsSeed.js
> +    contact: vendorCompany._id,
Ici il faut que le contact soit le trainer ou le salesRepresentative, d'ailleurs il y a bien un test sur la collection course pour verifier que le contact est le formateur, le referent compani ou le referent structure. Pourquoi ca ne casse pas ici ?

2023-06-29 13:36 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCourseIsBlended = courseBillList.every(bill => bill.course && bill.course.format === BLENDED);
Tu peux simplifier en `get(bill, 'course.format') === BLENDED`

2023-06-29 13:37 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCountIsAPositiveAndGreaterThanZeroInteger = courseBillList
Que penses-tu de raccourcir un peu le nom ? Par ex: everyCountIsAValidInteger ?

2023-06-29 13:40 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCourseIsBlended = courseBillList.every(bill => bill.course && bill.course.format === BLENDED);
Que penses-tu de sauter une ligner entre les 2 ? (idem pour les tests d'apres)

2023-06-29 13:41 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +          const everyPriceIsPositiveAndGreaterThanZero = courseBillList
idem pour le nom, on pourrait juste mettre `everyPriceIsValid` ?

2023-06-29 13:41 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCountIsAPositiveAndGreaterThanZeroInteger = courseBillList
Idem

2023-06-29 13:46 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +            .every(number => number.seq >= 0 && Number.isInteger(number.seq));
Ici c'est superieur strict non ? Seq vaut au minimum 1

2023-06-29 13:51 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        });
Pourquoi inferieur ou egale a 1? Pourquoi l'egalité n'est pas stricte ?

2023-06-29 15:04 UTC, ulysseferreira commented on tests/integration/seed/courseBillsSeed.js
> +    contact: vendorCompany._id,
oups coquille, j'avoue je ne sais pas, quand on console.log le champ n'apparait pas dans l'objet, j'ai l'impression que c'est comme quand on met un champ qui n'existe pas, si le champ qu'on met ne correspond pas au modèle attendu (on attend un User et j'ai mis un VendorCompany) ça zappe le champ

2023-06-29 15:07 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCourseIsBlended = courseBillList.every(bill => bill.course && bill.course.format === BLENDED);
done

2023-06-29 15:08 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCountIsAPositiveAndGreaterThanZeroInteger = courseBillList
done

2023-06-29 15:08 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const everyPriceIsPositiveAndGreaterThanZero = courseBillList
done

2023-06-29 15:09 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCountIsAPositiveAndGreaterThanZeroInteger = courseBillList
done

2023-06-29 15:11 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .every(number => number.seq >= 0 && Number.isInteger(number.seq));
done

2023-06-29 15:13 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        });
parce qu'il y a plein de fichiers de seed où cette collection n'existe pas car il n'y a pas de factures et que ça n'aurait pas de sens de la  créer partout juste pour ce test

2023-06-29 16:08 UTC, manonpalin commented on tests/integration/seed/courseBillsSeed.js
> +    contact: vendorCompany._id,
Ca me semble quand meme embettant que le test ne casse pas dans ce cas :/ 
Quand je `console.log(c.contact._id)` , ca me dis que ca vaut `c.salesRepresentative._id`, je ne comprends pas pq.

Une maniere de faire casser le test est de definir un _id dans `vendorCompany`, ce qui me semble bien de faire puisque tous nos objets ont un id en base.

2023-06-29 16:29 UTC, ulysseferreira commented on tests/integration/seed/courseBillsSeed.js
> +    contact: vendorCompany._id,
bien vu !

2023-06-30 09:10 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every price is positive and greater than 0', () => {
positive suffit

2023-06-30 09:10 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every count is a positive and greater than 0 integer', () => {
idem

2023-06-30 09:10 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every billing purchase price is positive and greater than 0', () => {
idem

2023-06-30 09:10 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every billing purchase count is a positive and greater than 0 integer', () => {
idem

2023-06-30 09:12 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every price is positive and greater than 0', () => {
done

2023-06-30 09:12 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every count is a positive and greater than 0 integer', () => {
done

2023-06-30 09:12 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every billing purchase price is positive and greater than 0', () => {
done

2023-06-30 09:12 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every billing purchase count is a positive and greater than 0 integer', () => {
done

2023-06-30 10:28 UTC, manonpalin approved these changes

2023-06-30 13:34 UTC, sophiemoustard requested changes

2023-06-30 13:34 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +            .populate({ path: 'payer.fundingOrganisation', transform })
pourquoi tu popules ces 3 champs ?

2023-06-30 13:34 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every user with client role has a company #tag', () => {
oups

2023-06-30 13:35 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every user with client role has a company #tag', () => {
oups

2023-06-30 13:38 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +            .populate({ path: 'payer.fundingOrganisation', transform })
t'as besoin de populer pour que le champ pète quand il est faux (test sur company exists et payer exists)

2023-06-30 13:40 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCompanyExists = courseBillList.every(bill => !!bill.company);
ici tu mets `bill.company` et plus bas tu mets `bill.payer._id`. est ce normal ?

2023-06-30 13:54 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCompanyExists = courseBillList.every(bill => !!bill.company);
oui. Tel qu'il est construit payer (avec le posthook) quand il est bien construit on a payer : {object avec toutes les infos du payer} par contre quand il est mal construit on a payer: {company: null} ou payer: {fundingOrganisation: null} donc si on met juste !!payer ça renvoie true alors que c'est faux

2023-06-30 13:58 UTC, sophiemoustard commented on tests/integration/seed/seedsVerification.test.js
> +          const everyCompanyExists = courseBillList.every(bill => !!bill.company);
ah oui bien vu ! merci

2023-06-30 13:58 UTC, sophiemoustard approved these changes

2023-06-30 14:23 UTC, merged