Com 3505
sophiemoustard/compani-api pull request #2262
Opened 2023-07-17 15:13 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [xx] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-07-18 13:34 UTC, sophiemoustard requested changes

2023-07-18 13:34 UTC, sophiemoustard commented on tests/integration/companies.test.js
> +    it('should return 404 if billingRepresentative is from an other company', async () => {
en fait coté front, un ROF ne peut pas mettre a jour ce champ non ? est ce qu'on garde ces 2 tests ?

2023-07-18 15:15 UTC, manonpalin commented on tests/integration/companies.test.js
> +    it('should return 404 if billingRepresentative is from an other company', async () => {
Ca va venir dans un prochain [ticket](https://www.notion.so/compani/ETQ-ROF-sur-la-fiche-d-une-structure-je-peux-d-finir-le-charg-e-de-la-facturation-dans-la-structur-12fc726f52f3454e87a5aac1b452867e). J'ai voulu anticiper ici car normalement il ne devrait pas y avoir de modifs a faire sur cette route pour le cas ou un ROF mettra a jour ce champ, pour eviter u oubli j'ai prefere le mettre ici. Qu'en penses-tu ?

2023-07-18 15:38 UTC, manonpalin commented on src/routes/preHandlers/companies.js
> +      UtilsHelper.areObjectIdsEquals(billingRepresentative.company, params._id) &&
Ici je m'etais trompee dans la condition. On veut que le chargé facturation soit admin client de la structure que l'on edite et non de la structure de la personne connectee.

2023-07-19 08:16 UTC, sophiemoustard commented on tests/integration/companies.test.js
> +    it('should return 404 if billingRepresentative is from an other company', async () => {
ah oui je n'avais plus en tete que ca venait dans un prochain ticket :) tu as bien fait dans ce cas

2023-07-19 08:26 UTC, sophiemoustard commented on src/routes/preHandlers/companies.js
> +      UtilsHelper.areObjectIdsEquals(billingRepresentative.company, params._id) &&
pour eviter tout confusion, tu pourrais renommer `companyId` en `loggedCompanyId` qu'en penses tu ?

2023-07-19 08:31 UTC, sophiemoustard commented on src/routes/preHandlers/companies.js
> +      UtilsHelper.areObjectIdsEquals(billingRepresentative.company, params._id) &&
et du coup peut etre mettre `updatedCompanyId` pour `params._id` pour etre bien au clair sur ce qu'on manipule
et quitte a faire cdes changement, tu peux enlever le `!companyId` de la condition `if (!isVendorAdmin && (!companyId || !UtilsHelper.areObjectIdsEquals(params._id, companyId)))` (ligne 29) car si cet id est manquant alors `areObjectIdsEquals` renverra faux :)

2023-07-19 10:26 UTC, manonpalin commented on src/routes/preHandlers/companies.js
> +      UtilsHelper.areObjectIdsEquals(billingRepresentative.company, params._id) &&
Oui bonne idee :) C'est changé !

2023-07-19 11:58 UTC, sophiemoustard approved these changes

2023-07-19 11:58 UTC, merged