COM-3538: can archive and unarchive course easily
sophiemoustard/compani-api pull request #2278
Opened 2023-08-08 10:33 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-08-23 15:15 UTC, manonpalin commented on src/helpers/courses.js
> +  const params = { $set: omittedPayload, ...unsetFields };
Je trouve etrange de definir dans un cas l'operateur et l'objet puis dans l'autre seulement passer l'objet.

Que penses-tu de : 
```
let setFields = payload;
  let unsetFields = null;

  if (payload.contact === '') {
    setFields = omit(setFields, 'contact');
    unsetFields = { contact: '' };
  }
  if (payload.archivedAt === '') {
    setFields = omit(setFields, 'archivedAt');
    unsetFields = { ...unsetFields, archivedAt: '' };
  }
  const params = { $set: { ...setFields }, $unset: { ...unsetFields } };
```

2023-08-30 09:24 UTC, ulysseferreira commented on src/helpers/courses.js
> +  const params = { $set: omittedPayload, ...unsetFields };
done

2023-08-30 15:27 UTC, manonpalin commented on src/helpers/courses.js
> +  let unsetFields = null;
Pardon c'est etrange de mettre null ici non ? Peut etre mettre {} 

Et que penses-tu d'envoyer $unset et $set uniquement si il y a des champs. J'avais pas anticipé ce point mais en voyant les modifs que t'as fait dans les tests, je trouve dommage de faire appel a l'operateur $unset si il n'y a aucun champ a lui passer.
Qu'en penses-tu ?

2023-08-30 15:40 UTC, ulysseferreira commented on src/helpers/courses.js
> +  let unsetFields = null;
done

2023-08-31 06:57 UTC, manonpalin approved these changes

2023-08-31 09:56 UTC, sophiemoustard approved these changes

2023-08-31 10:13 UTC, sophiemoustard requested changes

2023-08-31 10:13 UTC, sophiemoustard commented on src/helpers/courses.js
> +  const params = {
tu peux nommer cette variable `formattedPayload` ? 
comme c'est l'objet qui contient les infos a enregistrer en base, ce n'est pas `params`

2023-08-31 10:17 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +    if (course.archivedAt && !unarchiveCourse) throw Boom.forbidden();
dans tes tests tu dis que tu renvois un conflit

2023-08-31 12:13 UTC, ulysseferreira commented on src/helpers/courses.js
> +  const params = {
done

2023-08-31 15:49 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +    if (course.archivedAt && !unarchiveCourse) throw Boom.forbidden();
ah oui pardon !

2023-08-31 16:22 UTC, sophiemoustard approved these changes

2023-08-31 16:22 UTC, merged