COM-3513: can see courses table
sophiemoustard/compani-api pull request #2281
Opened 2023-08-11 15:29 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [x] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [x] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] ~~J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)~~
- [ ] ~~J'ai ajouté un modèle spécifique à une structure~~
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] ~~J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile~~
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [x] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-04 15:35 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +      UtilsHelper.hasUserAccessToCompany(credentials, trainee.company._id)
done

2023-09-04 15:37 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +  const isClientRoleFromQuery = [COACH, CLIENT_ADMIN].includes(loggedUserClientRole) && isAllowedToAccessQuery;
done

2023-09-04 16:28 UTC, manonpalin commented on tests/unit/helpers/courses.test.js
> +          subProgram: {
Ah oui pardon, j'avias pas vu la projection !

2023-09-04 16:29 UTC, manonpalin approved these changes

2023-09-05 09:56 UTC, sophiemoustard requested changes

2023-09-05 09:56 UTC, sophiemoustard commented on src/helpers/courses.js
> +          UtilsHelper.doesArrayIncludeId(companies, traineeCompanies[course._id]));
indentation en trop

2023-09-05 09:56 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +  const hasUserAccessToCompany = UtilsHelper.hasUserAccessToCompany(credentials, trainee.company._id);
est ce que ce ne serait pas plutot `hasLoggedUserAccessToTrainee` pour le nom de la variable ? 
pour ne pas confondre avec la `company` dans `query` ?

2023-09-05 09:58 UTC, ulysseferreira commented on src/helpers/courses.js
> +          UtilsHelper.doesArrayIncludeId(companies, traineeCompanies[course._id]));
done

2023-09-05 09:58 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +  const hasUserAccessToCompany = UtilsHelper.hasUserAccessToCompany(credentials, trainee.company._id);
done

2023-09-05 10:00 UTC, sophiemoustard approved these changes

2023-09-05 10:21 UTC, merged