Com 3523
sophiemoustard/compani-api pull request #2284
Opened 2023-08-22 16:09 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-08-28 07:18 UTC, manonpalin commented on src/routes/courses.js
> +            action: Joi.string().required().valid(OPERATIONS, PEDAGOGY, QUESTIONNAIRE),
Au depart on voulait : `si pas de credentials, faire appel a une nouvelle methode du service getCourseMinimalInfos` 

En fait cette condition pose probleme lorsque le formateur veut acceder a la page pour remplir le questionnaire puisqu’il est connecté. Dans ce cas on fait un appel a GET /courses/id sans rien envoyer dans la query ⇒ 400 

Je pense que le mieux est de creer une troisieme action: QUESTIONNAIRE et ainsi conditionner sur cette action plutot que sur les credentials. Qu'en pensez-vous ?

2023-08-28 16:37 UTC, manonpalin commented on src/routes/courses.js
> +            action: Joi.string().required().valid(OPERATIONS, PEDAGOGY, QUESTIONNAIRE),
Face a ce blocage que j'avais, j'ai trouvé pertinent d'ajouter une nouvelle action pour expliciter le fait que l'on recupere les infos de la formation pour repondre au questionnaire

2023-08-29 10:42 UTC, sophiemoustard requested changes

2023-08-29 12:17 UTC, manonpalin commented on src/helpers/courses.js
> +  const fetchedCourse = await Course
corrigé

2023-08-29 12:36 UTC, manonpalin commented on src/routes/preHandlers/courses.js
> +    if (!credentials) return null;
Oui tu as raison j'ai oublié de bloquer ! 
J'ai fait un peu differemment en retournant une 400 si `!credentials` vaut true et que l'action est PEDAGOGY ou OPERATIONS

2023-08-29 13:42 UTC, sophiemoustard approved these changes

2023-08-29 15:19 UTC, ulysseferreira commented on tests/integration/questionnaireHistories.test.js
> +      const payload = {
tu ne mets pas l'origin ?

2023-08-30 13:38 UTC, ulysseferreira approved these changes

2023-08-30 13:38 UTC, merged