Com 3556
sophiemoustard/compani-api pull request #2299
Opened 2023-10-02 15:57 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires -np
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-03 16:23 UTC, manonpalin commented on src/routes/preHandlers/courses.js
> +    const isRofOrAdmin = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN]
Ici tu pourrais deplacer la logique dans le else du dessus et separer en 2 if pour definir toutes les constantes uniquement dans le cas intra_holding: 
```
if (course.type === INTRA_HOLDING) {
  // tu definis isRofOrAdmin, loggedUserCompant etc
}
```

2023-10-04 07:41 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +    const isRofOrAdmin = [TRAINING_ORGANISATION_MANAGER, VENDOR_ADMIN]
done

2023-10-04 10:51 UTC, manonpalin commented on src/routes/preHandlers/courses.js
>        if (!UtilsHelper.doesArrayIncludeId(course.companies, payload.company)) throw Boom.conflict();
En testant : ETQ HoldingAdmin, j'essaie d'ajouter un apprenant dont la structure n'est pas dans la formation intra_holding, je me suis rendu compte qu'on renvoie une erreur 409. C'est etrange non ? On devrait plutot renvoyer une 403 ici

2023-10-04 12:14 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
>        if (!UtilsHelper.doesArrayIncludeId(course.companies, payload.company)) throw Boom.conflict();
done

2023-10-04 14:03 UTC, manonpalin approved these changes

2023-10-04 14:54 UTC, sophiemoustard requested changes

2023-10-04 14:54 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
>      if (course.type === INTRA && !!payload.company) throw Boom.badData();
tu pourrrais le mettre dans le `if (course.type === INTRA) {` que tu as a la ligne 329 non ?

2023-10-04 14:54 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +    if ([INTER_B2B, INTRA_HOLDING].includes(course.type) && !payload.company) throw Boom.badData();
dans le meme sens, tu pourrais mettre ca dans le `else` du coup

2023-10-04 14:54 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +    if ((course.type === INTER_B2B || hasNoClientOrHoldingRoleOnIntraHolding) && isTrainer) throw Boom.forbidden();
et ca aussi :) car ca ne concerne que les formations INTRA_HOLDING ou INTER_B2B

2023-10-04 14:54 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
>      const traineeAlreadyRegistered = course.trainees.some(t => UtilsHelper.areObjectIdsEquals(t, payload.trainee));
pour rapporcher les verifications qui vont dans le meme sens, tu pourrais mettre ca a cote de `traineeIsTrainer` ; comme ca on rapporche les thematiques

(je me fais justela reflexion en lisant ta PR que cette methode devient de plus en plus longue et donc un peu ardue a lire)

2023-10-04 16:13 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +    if ([INTER_B2B, INTRA_HOLDING].includes(course.type) && !payload.company) throw Boom.badData();
done

2023-10-04 16:14 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +    if ((course.type === INTER_B2B || hasNoClientOrHoldingRoleOnIntraHolding) && isTrainer) throw Boom.forbidden();
done

2023-10-04 16:15 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
>      const traineeAlreadyRegistered = course.trainees.some(t => UtilsHelper.areObjectIdsEquals(t, payload.trainee));
done

2023-10-04 16:20 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
>      const traineeAlreadyRegistered = course.trainees.some(t => UtilsHelper.areObjectIdsEquals(t, payload.trainee));
je me dis depuis quelque jour qu'il faudrait peut-être revoir notre manière de gérer ce prehandler courses, checkAuthorization devient un casse-tête y a des exceptions partout et on manque d'en oublier une fois sur deux, ça serait vachement plus simple d'avoir un système qui ressemble au fichier rights où pour chaque rôle on indique dans un tableau ce qu'ils ont droit de modifier

2023-10-05 09:04 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +      !([COACH, CLIENT_ADMIN].includes(clientRole) || holdingRole === HOLDING_ADMIN);
il manque une indentation

2023-10-05 09:21 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +      !([COACH, CLIENT_ADMIN].includes(clientRole) || holdingRole === HOLDING_ADMIN);
done

2023-10-05 09:21 UTC, sophiemoustard approved these changes

2023-10-05 09:42 UTC, merged