Com 3611
sophiemoustard/compani-api pull request #2317
Opened 2023-11-03 11:53 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-03 16:35 UTC, ulysseferreira commented on src/helpers/courses.js
> +  return { file: pdf, name: `Attestation - ${traineeIdentity}.pdf` };
pourquoi ce changement ?

2023-11-03 16:35 UTC, ulysseferreira commented on src/routes/courses.js
> +            format: Joi.string().valid(...FORMAT_OPTIONS), // #TODO - rendre ce champ requis une fois la MEP faite
tu ne mets pas pdf en défaut au final ?

2023-11-06 14:59 UTC, manonpalin commented on src/helpers/courses.js
> +  return { file: pdf, name: `Attestation - ${traineeIdentity}.pdf` };
Suite a la modif que j'ai faite dans le controlleur , on a besoin de `data.file`

2023-11-06 15:29 UTC, ulysseferreira commented on src/helpers/courses.js
> +  return { file: pdf, name: `Attestation - ${traineeIdentity}.pdf` };
là où tu as écris `return h.response(data.file)` ? mais pourquoi justement être passé à ça plutôt qu'avoir laissé `return h.response(data.pdf)` ?

2023-11-06 15:31 UTC, ulysseferreira commented on src/routes/courses.js
> +            format: Joi.string().valid(...FORMAT_OPTIONS), // #TODO - rendre ce champ requis une fois la MEP faite
mais là il est pas requis non ? d'ailleurs je ne comprends pas pourquoi tu attends la MEP ?

2023-11-07 09:53 UTC, sophiemoustard requested changes

2023-11-07 10:09 UTC, manonpalin commented on src/routes/courses.js
> +            format: Joi.string().valid(...FORMAT_OPTIONS), // #TODO - rendre ce champ requis une fois la MEP faite
Il va le devenir mais en fait pour etre compatible avec la anciennes version, il faut le mettre par defaut

2023-11-07 10:22 UTC, manonpalin commented on src/routes/courses.js
> +            format: Joi.string().valid(...FORMAT_OPTIONS), // #TODO - rendre ce champ requis une fois la MEP faite
On a pas trop l'habitude de le faire mais lors de relecture de strat on en avait parlé avec Sophie : 
une bonne pratique est de décoréller les MEP api des MEP mobiles.

Pour eviter de devoir mettre en prod API et mobile en meme temps, Sophie a suggéré d'ajouter le champ format, de laisser origin pour que les anciennes versions mobiles soient compatibles. Ca va nous permettre de mettre en prod l'api sans forcement attendre que les build soient validés par les stores. On pourra ensuite faire la MEP mobile puis retirer le champ 'origin' cote api dans un deuxieme temps.

2023-11-07 10:41 UTC, manonpalin commented on src/helpers/courses.js
> +  return { file: pdf, name: `Attestation - ${traineeIdentity}.pdf` };
En fait pardon c'etait pas la raison exacte. C'est pcq pour generer le zip, il faut que les fichiers que l'on met dans le zip soient au format : `{ file, name }`

2023-11-07 10:42 UTC, manonpalin commented on src/helpers/courses.js
> +    return generateCompletionCertificateAllPdf(courseData, attendances, traineeList);
corrigé

2023-11-07 10:42 UTC, manonpalin commented on src/helpers/courses.js
> +  return generateCompletionCertificatePdf(courseData, attendances, trainee);
corrigé

2023-11-07 10:42 UTC, manonpalin commented on src/helpers/courses.js
> -    .map(trainee => generateCompletionCertificateWord(courseData, attendances, trainee, templatePath));
corrigé

2023-11-07 10:42 UTC, manonpalin commented on src/helpers/courses.js
> -    tmpFilePath: templatePath,
corrigé

2023-11-07 10:42 UTC, manonpalin commented on src/routes/courses.js
> +            format: Joi.string().valid(...FORMAT_OPTIONS), // #TODO - rendre ce champ requis une fois la MEP faite
corrigé

2023-11-07 11:06 UTC, sophiemoustard approved these changes

2023-11-07 14:54 UTC, ulysseferreira approved these changes

2023-11-07 14:54 UTC, merged