COM-3613: can download course bill
sophiemoustard/compani-api pull request #2320
Opened 2023-11-09 15:55 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-10 14:37 UTC, sophiemoustard requested changes

2023-11-10 14:37 UTC, sophiemoustard commented on src/helpers/courseBills.js
> +  const { number, billedAt, companies, payer, course, mainFee, billingPurchaseList } = bill;
que penses tu d'utiliser `pick` ici pour tous ces champs : `['number', 'course', 'mainFee', 'billingPurchaseList', 'company']`

2023-11-10 14:37 UTC, sophiemoustard commented on tests/integration/courseCreditNotes.test.js
> +// describe('COURSE CREDIT NOTES ROUTES - GET /coursecreditnotes/{_id}/pdfs', () => {
il y a un souci entre tes branches la non ?

2023-11-10 15:12 UTC, ulysseferreira commented on tests/integration/courseCreditNotes.test.js
> +// describe('COURSE CREDIT NOTES ROUTES - GET /coursecreditnotes/{_id}/pdfs', () => {
non pourquoi ? on a modifié getHeader qui est utilisé dans le pdf de courseBills et de courseCreditNote donc on est obligé de masquer les tests de course credit note le temps de faire le ticket 3613

2023-11-10 15:19 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +  const { number, billedAt, companies, payer, course, mainFee, billingPurchaseList } = bill;
done

2023-11-10 15:28 UTC, sophiemoustard commented on tests/integration/courseCreditNotes.test.js
> +// describe('COURSE CREDIT NOTES ROUTES - GET /coursecreditnotes/{_id}/pdfs', () => {
ces tests la n'ont pas eu besoin d'etre commenté au moment de la modifications sur les avoirs ? c'est etrange non ?

2023-11-10 15:57 UTC, ulysseferreira commented on tests/integration/courseCreditNotes.test.js
> +// describe('COURSE CREDIT NOTES ROUTES - GET /coursecreditnotes/{_id}/pdfs', () => {
parce qu'on utilise pas les structures dans les avoir et cet objet n'est pas affiché donc il comprenait juste undefined à la place du nom de la structure. Mais comme ici ça devient un tableau avec un map, ça pète s'il n'y a rien

2023-11-13 13:46 UTC, sophiemoustard approved these changes

2023-11-13 19:13 UTC, manonpalin commented on src/data/pdf/courseBilling/utils.js
> +      { text: get(data, 'companies').map(c => c.name).join(', '), bold: true },
Que penses-tu de creer une methode `formatCompaniesNames` ? J'ai l'impression qu'on fait souvent un map puis un join pour formatter les noms

2023-11-14 11:09 UTC, manonpalin approved these changes

2023-11-14 11:09 UTC, merged