Com 3620
sophiemoustard/compani-api pull request #2321
Opened 2023-11-10 09:32 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [ ] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles.
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-10 16:21 UTC, ulysseferreira commented on src/helpers/courses.js
> +  const courseData = type ? exports.formatCourseForDocuments(course, type) : exports.formatCourseForDocuments(course);
tu peux pas juste mettre exports.formatCourseForDocuments(course, type) ? si type est null ça revient au premier cas

2023-11-10 16:21 UTC, ulysseferreira commented on src/helpers/courses.js
> +    ...omit(courseData, 'companies'),
pourquoi tu retires ce champs ?

2023-11-13 08:56 UTC, manonpalin commented on src/helpers/courses.js
> +    ...omit(courseData, 'companies'),
Car je l'ajoute dans formatCourse pour pouvoir avoir le nom des structures dans le cas ou on veut telecharger les certificats, mais on en a pas besoin ici donc il vaut mieux le retirer

2023-11-13 09:01 UTC, manonpalin commented on src/helpers/courses.js
> +  const courseData = type ? exports.formatCourseForDocuments(course, type) : exports.formatCourseForDocuments(course);
hmm ca petait a un moment quand type etait undefined mais j'arrve plus a le reproduire

2023-11-13 11:26 UTC, ulysseferreira commented on src/helpers/courses.js
> +  const courseData = exports.formatCourseForDocuments(course, type || null);
ça ne marchait pas si on mettait juste exports.formatCourseForDocuments(course, type) ici et qu'on laissait type = null dans la définition de formatCourseForDocuments ? ça me semble être plus une manière habituel de l'écrire

2023-11-13 13:17 UTC, manonpalin commented on src/helpers/courses.js
> +  const courseData = exports.formatCourseForDocuments(course, type || null);
En fait je pense que ca ne sert a rien de mettre type = null car on definit une valeur par defaut dans la route donc type est tjs defini. Je pense qu'a un moment j'avais undefined car je n'avais pas relancé mon back.

2023-11-13 13:56 UTC, ulysseferreira commented on src/helpers/courses.js
> +  const courseData = exports.formatCourseForDocuments(course, type || null);
bien vu

2023-11-14 16:31 UTC, ulysseferreira approved these changes

2023-11-15 10:57 UTC, sophiemoustard requested changes

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +    const traineesCompany = mapValues(keyBy(traineesCompanyAtCourseRegistration, 'trainee'), 'company');
tu fais ces appels dans la methode `getTraineeList` ; il n'y a pas moyen de mutualiser ?
je pense que tu peux faire en sort d'avoir l'information de la structure de chaque apprenant a la sortie de la methode `getTraineeList`

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +    const traineesCompanyNames = courseData.companies;
Si tu penses que ce renommage est necessaire c'est que le nom de la clé `companies` dans l'objet `courseData` n'est pas bon ; tu pourrais mettre `companyNamesById` ?

2023-11-15 10:57 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +  it('should format course for docx (official certificate)', () => {
tu peux passer une ligne

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +        return generateCompletionCertificateWord(courseData, attendances, t, tmpFilePath, companyName);
cf mon retour du dessus, le `companyName` doit etre dans l'objet `t`

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +  const docType = companyName ? 'Certificat' : 'Attestation';
je trouve ca etrange de se base sur `companyName` et pas sur `type` pour cette variable la

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +  const { traineeIdentity, attendanceDuration } = getTraineeInformations(trainee, attendances);
dnas la methode `getTraineeInformations` tu pourrais directement retourner un objet de la forme `{ identity, attendanceDuration, companyName }`

2023-11-15 10:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +      trainee: { identity: traineeIdentity, attendanceDuration, ...(companyName && { companyName }) },
et du coup ici tu pourrais directement mettre `trainee: getTraineeInformations(trainee, attendances)`

2023-11-15 14:48 UTC, manonpalin commented on src/helpers/courses.js
> +  const { traineeIdentity, attendanceDuration } = getTraineeInformations(trainee, attendances);
done

2023-11-15 14:49 UTC, manonpalin commented on src/helpers/courses.js
> +      trainee: { identity: traineeIdentity, attendanceDuration, ...(companyName && { companyName }) },
On a besoin de l'identité pour formatter le nom du fichier. J'ai donc laissé l'appel a getTraineeInformations au debut

2023-11-15 14:56 UTC, manonpalin commented on src/helpers/courses.js
> +    const traineesCompany = mapValues(keyBy(traineesCompanyAtCourseRegistration, 'trainee'), 'company');
C'est corrigé

2023-11-15 14:56 UTC, manonpalin commented on src/helpers/courses.js
> +    const traineesCompanyNames = courseData.companies;
Corrigé

2023-11-15 14:56 UTC, manonpalin commented on src/helpers/courses.js
> +        return generateCompletionCertificateWord(courseData, attendances, t, tmpFilePath, companyName);
corrigé

2023-11-15 14:56 UTC, manonpalin commented on tests/unit/helpers/courses.test.js
> +  it('should format course for docx (official certificate)', () => {
corrigé

2023-11-15 15:02 UTC, manonpalin commented on src/helpers/courses.js
> +  const docType = companyName ? 'Certificat' : 'Attestation';
corrigé

2023-11-16 09:03 UTC, sophiemoustard requested changes

2023-11-16 09:03 UTC, sophiemoustard commented on src/helpers/courses.js
> +    .populate({ path: 'trainees', select: 'identity', populate: { path: 'company' } })
en faisant ca tu recupères la structure a date de l'apprenant et non la structure avec laquelle il a ete inscrit
pour moi il faut que tu ajoutes un `map` dans `getTraineeList` ajouter le champ `company` dans chaque apprenant

2023-11-16 09:09 UTC, sophiemoustard commented on src/helpers/courses.js
> +    .populate({ path: 'trainees', select: 'identity', populate: { path: 'company' } })
tu peux faire la test : 
- creation d'une formation pour l'eps
- ajout d'un apprenant 
- modification en base des champs `createdAt` et `updatedAt` de l'objet coursehistories associé
- detachement de l'eps dans le passé
- sur ta branche on voit ca "salarié(e) de l’entreprise undefined" sur le word

2023-11-16 11:26 UTC, manonpalin commented on src/helpers/courses.js
> +    .populate({ path: 'trainees', select: 'identity', populate: { path: 'company' } })
Ah mais oui bien vu. C"est corrigé

2023-11-16 15:28 UTC, sophiemoustard approved these changes

2023-11-16 15:28 UTC, merged