COM-3617: can export bills and credit notes
sophiemoustard/compani-api pull request #2323
Opened 2023-11-13 15:25 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-16 09:38 UTC, sophiemoustard requested changes

2023-11-16 09:38 UTC, sophiemoustard commented on src/helpers/vendorHistoryExport.js
> +    };
ta methode peut ressembler a ca 
```
const formatCommonInfos = (bill, netInclTaxes) => {
  const companyName = bill.course.type === INTRA ? `${bill.companies[0].name} - ` : '';
  const misc = bill.course.misc ? ` - ${bill.course.misc}` : '';
  const courseName = `${companyName}${bill.course.subProgram.program.name}${misc}`;

  return {
    'Id formation': bill.course._id,
    Formation: courseName,
    Structure: bill.companies.map(c => c.name).join(', '),
    Payeur: bill.payer.name,
    'Montant TTC': UtilsHelper.formatFloatForExport(netInclTaxes),
  };
};
```

2023-11-16 09:40 UTC, sophiemoustard commented on tests/integration/exports.test.js
> +      `"Avoir";"AV-00001";"09/03/2022";${coursesList[3]._id};"Test SAS - Program 1 - group 4";"Test SAS";"APA Paris";"1200,00";;"FACT-00002";;;;;;`,
ce serait bien que tu changes ton test en coherence avec le changement qu'on a fait dans le code : on ne prend plus les avior relie aux factures mais les avoirs de la période

dans tes Seed c'est donc bien si tu as :
- un avoir sur la periode non rattaché a une facture
- un avoir pas dans la periode rattaché a une facture

2023-11-16 11:35 UTC, ulysseferreira commented on src/helpers/vendorHistoryExport.js
> +    };
done

2023-11-16 11:36 UTC, ulysseferreira commented on tests/integration/exports.test.js
> +      `"Avoir";"AV-00001";"09/03/2022";${coursesList[3]._id};"Test SAS - Program 1 - group 4";"Test SAS";"APA Paris";"1200,00";;"FACT-00002";;;;;;`,
done

2023-11-16 15:32 UTC, sophiemoustard approved these changes

2023-11-17 11:14 UTC, manonpalin commented on src/helpers/vendorHistoryExport.js
> +    rows.push(formattedCreditNote);
Avant si il y avait un avoir, il apparaissait juste apres la facture concernée. Aujourd'hui ce n'est plus le cas, on considere que c'est suffisant de remplacer cet ordre par l'ajout d'infos dans la colonne "Document lié" ?

2023-11-17 13:39 UTC, ulysseferreira commented on src/helpers/vendorHistoryExport.js
> +    rows.push(formattedCreditNote);
oui, parce qu'on ne peut pas le mettre en dessous de la facture concernée vu que potentiellement elle n'est pas dans le fichier, les deux sont décorrellés maintenant

2023-11-17 15:20 UTC, manonpalin approved these changes

2023-11-17 15:21 UTC, merged