Com 3632
sophiemoustard/compani-api pull request #2339
Opened 2023-12-12 16:16 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-12-14 08:35 UTC, manonpalin commented on src/helpers/translate.js
> +    trainerMissionCreated: 'Trainer mission created',
Il manque un point a la fin non ?

2023-12-14 08:36 UTC, manonpalin commented on src/helpers/translate.js
> +    trainerMissionCreated: 'Ordre de mission créé',
Idem

2023-12-14 08:58 UTC, manonpalin commented on src/routes/trainerMissions.js
> +            date: requiredDateToISOString,
Pourquoi passer la date dans la route si on la définis toujours a la date du jour ?

2023-12-14 08:58 UTC, manonpalin commented on src/routes/preHandlers/trainerMissions.js
> +  const { trainer } = req.payload;
Tu pourrais ajouter `courses` dans la decomposition ici

2023-12-14 09:48 UTC, manonpalin commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if none course is in both trainer mission #tag', () => {
+ je ne comprends pas l'intitulé, both est en trop non ?

2023-12-14 10:07 UTC, manonpalin commented on tests/integration/seed/trainerMissionsSeed.js
> +    salesRepresentative: vendorAdmin._id,
Selon si ta PR ou la mienne est fusionnée avant, il faudra qu'on soit vigilant sur le changement `salesRepresentative` / `operationsRepresentative`

2023-12-14 13:26 UTC, ulysseferreira commented on src/helpers/translate.js
> +    trainerMissionCreated: 'Trainer mission created',
en général on met un point pour les messages qui vont en front, là c'est juste un message back

2023-12-14 13:42 UTC, ulysseferreira commented on src/routes/trainerMissions.js
> +            date: requiredDateToISOString,
done

2023-12-14 13:45 UTC, ulysseferreira commented on src/routes/preHandlers/trainerMissions.js
> +  const { trainer } = req.payload;
done

2023-12-14 13:46 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if none course is in both trainer mission #tag', () => {
done

2023-12-14 13:46 UTC, ulysseferreira commented on tests/integration/seed/trainerMissionsSeed.js
> +    salesRepresentative: vendorAdmin._id,
yes bien vu

2023-12-14 15:22 UTC, manonpalin commented on tests/integration/seed/trainerMissionsSeed.js
> +    date: '2023-01-03T14:00:00.000Z',
Ici pour etre coherent, il faudrait mettre au debut de la journee plutot

2023-12-14 15:24 UTC, manonpalin commented on src/models/TrainerMission.js
> +  date: { type: Date, default: CompaniDate().startOf(DAY).toISO() },
Ici je me demnade si c'est pas un peu étrange de mettre une valeur par defaut qui est la valeur toujours utilisée... Est-ce qu'on ne devrait pas plutot definir la date au moment de la création de l'ordre de mission dans le service ?

2023-12-14 15:49 UTC, ulysseferreira commented on tests/integration/seed/trainerMissionsSeed.js
> +    date: '2023-01-03T14:00:00.000Z',
done

2023-12-14 15:50 UTC, ulysseferreira commented on src/models/TrainerMission.js
> +  date: { type: Date, default: CompaniDate().startOf(DAY).toISO() },
on fait comme ça pour les userCompany où c'est un peu le même principe, pourquoi tu trouve ça mieux de le faire dans le service ? ça rajoute du code qui n'est pas nécessaire

2023-12-14 16:51 UTC, sophiemoustard commented on src/controllers/trainerMissionController.js
> +const create = async (req) => {
comment comptes tu nommer les methodes (controlleur / service / messages / ...) que tu vas utiliser pour l'action de generation + enregistrement de l'ordre de mission ?

2023-12-15 11:50 UTC, ulysseferreira commented on src/controllers/trainerMissionController.js
> +const create = async (req) => {
à la base j'avais prévu de suivre le même schéma que pour les conventions de formations où la génération se trouve dans les routes courses (ici trainer) et de faire /trainers/{_id}/missions?courses={id} avec courses en query. Après vu qu'au final on ne fait pas que générer à la volée et on enregistre l'ordre de mission, peut-être que ce n'est pas la meilleure façon de faire ?

2023-12-18 13:15 UTC, sophiemoustard requested changes

2023-12-18 13:15 UTC, sophiemoustard commented on src/routes/trainerMissions.js
> +        pre: [{ method: authorizeTrainerMissionUpload }],
Creation plutot que upload non ?

2023-12-18 13:15 UTC, sophiemoustard commented on tests/integration/trainerMissions.test.js
> +    it('should return 400 if course is empty array', async () => {
je ne comprends pas pouquoi dans ton test tu as en meme temps 
- `courses: '12345'` dans le payload
- `const courses = [];` defini en dehors du payload
- `courses.forEach(course => form.append('courses', course));1 qui du coup ne sert a rien car `courses` est un tableau vide
- et je ne vois pas le comportement du titre du test mis en pratique ici

2023-12-18 15:47 UTC, manonpalin commented on src/controllers/trainerMissionController.js
> +    await TrainerMissionsHelper.uploadTrainerMission(req.payload, req.auth.credentials);
upload ne suffit pas ? Comme on est dans le controller trainerMission, je pense que c'est suffisant

2023-12-19 08:05 UTC, manonpalin commented on src/models/TrainerMission.js
> +  date: { type: Date, default: CompaniDate().startOf(DAY).toISO() },
Ah oui exacte, j'avais plus en tete qu'on faisait ca. On le fait aussi pour la plupart de nos historiques

2023-12-19 08:06 UTC, manonpalin commented on src/routes/preHandlers/trainerMissions.js
> +  const coursesCount = await Course.countDocuments({ _id: { $in: coursesId }, trainer });
Que penses-tu d'aerer un peu ici en sautant une ligne avant?

2023-12-19 08:12 UTC, manonpalin commented on tests/integration/trainerMissions.test.js
> +      const trainerMission = await TrainerMission.countDocuments({
trainerMissionCount ?

2023-12-19 08:24 UTC, manonpalin commented on tests/integration/seed/trainerMissionsSeed.js
> +const steps = [{ _id: new ObjectId(), type: 'on_site', name: 'étape', status: PUBLISHED, theoreticalDuration: 60 }];
Ici je pense que tu pourrais uniformiser les ecritures : soit mettre stepList soit step en retirant le tableau comme il n'y en a qu'un

2023-12-19 09:19 UTC, ulysseferreira commented on src/routes/trainerMissions.js
> +        pre: [{ method: authorizeTrainerMissionUpload }],
done

2023-12-19 09:23 UTC, ulysseferreira commented on tests/integration/trainerMissions.test.js
> +    it('should return 400 if course is empty array', async () => {
le courses: 12345 est en trop en effet.
j'ai laisse le append sur le tableau vide pour imiter au plus proche ce qu'il se passait si en front la modale renvoyait un tableau vide, car je ne sais pas concrètement comment c'est interprété par le append (est-ce-que ça équivaut à courses: '' ou bien le champ n'existe juste pas dans le formData)

2023-12-19 09:24 UTC, ulysseferreira commented on src/controllers/trainerMissionController.js
> +    await TrainerMissionsHelper.uploadTrainerMission(req.payload, req.auth.credentials);
done

2023-12-19 09:24 UTC, ulysseferreira commented on src/routes/preHandlers/trainerMissions.js
> +  const coursesCount = await Course.countDocuments({ _id: { $in: coursesId }, trainer });
done

2023-12-19 09:25 UTC, ulysseferreira commented on tests/integration/trainerMissions.test.js
> +      const trainerMission = await TrainerMission.countDocuments({
done

2023-12-19 09:26 UTC, ulysseferreira commented on tests/integration/seed/trainerMissionsSeed.js
> +const steps = [{ _id: new ObjectId(), type: 'on_site', name: 'étape', status: PUBLISHED, theoreticalDuration: 60 }];
done

2023-12-19 09:31 UTC, sophiemoustard commented on tests/integration/trainerMissions.test.js
> +    it('should return 400 if course is empty array', async () => {
je ne suis pas sur de comprendre ce que tu dis sur "pour imiter au plus proche ce qu'il se passait si en front la modale renvoyait un tableau vide, car je ne sais pas concrètement comment c'est interprété par le append"
car pour moi comme `courses` est un tableau vide, on ne passe pas dnas le `forEach` donc on arrrive pas au `append` ; cette ligne n'est pas executée

2023-12-19 09:47 UTC, sophiemoustard approved these changes

2023-12-19 10:13 UTC, manonpalin approved these changes

2023-12-19 15:10 UTC, merged