Com 3634
sophiemoustard/compani-api pull request #2348
Opened 2024-01-17 11:43 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2024-01-22 17:58 UTC, manonpalin commented on src/helpers/trainerMissions.js
> +  const infos = {
On utilise plutot data que infos non ?

2024-01-22 18:04 UTC, manonpalin commented on src/helpers/trainerMissions.js
> +    identity: courses[0].trainer.identity,
que penses-tu de `trainerIdentity` ?

2024-01-22 18:05 UTC, manonpalin commented on src/data/pdf/trainerMission.js
> +    [{ text: 'NOM et Prénom' }, { text: UtilsHelper.formatIdentity(data.identity, 'FL'), style: 'cell' }],
formatIdentity renvoie d'abord le prenom puis le nom , il faudrait plutot mettre `Prénom et NOM`

2024-01-22 18:21 UTC, manonpalin commented on src/data/pdf/trainerMission.js
> +        { text: 'Fait à Paris,', alignment: 'right' },
J'ai l'impression que si on met les infos "fait a ... le... par ..." a gauche et la signature a droite on gagne de la place et que ca evite d'avoir l'ordre de mission sur plusieurs pages (si il y a beaucoup de creneaux ce sera inevitablemenet sur 2 pages...)

2024-01-22 18:23 UTC, manonpalin commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
pourquoi as-tu ajouté cette partie ?

2024-01-22 18:29 UTC, manonpalin commented on src/data/pdf/trainerMission.js
> +const composeCourseName = (course) => {
Tu pourrais utiliser composeCourseName deja existant non ?

2024-01-22 18:31 UTC, manonpalin commented on src/data/pdf/trainerMission.js
> +    [{ text: 'Lieu(x) de la formation' }, { text: data.addressList.join(', '), style: 'cell' }],
J'uniformiserai soit tout au pluriel soit tout au singulier mais c'est etrange d'avoir uniquement ce champ avec (x), qu'en penses-tu ?

2024-01-23 09:25 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  const infos = {
done

2024-01-23 09:27 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +    identity: courses[0].trainer.identity,
done

2024-01-23 09:27 UTC, ulysseferreira commented on src/data/pdf/trainerMission.js
> +    [{ text: 'NOM et Prénom' }, { text: UtilsHelper.formatIdentity(data.identity, 'FL'), style: 'cell' }],
done

2024-01-23 09:29 UTC, ulysseferreira commented on src/data/pdf/trainerMission.js
> +    [{ text: 'Lieu(x) de la formation' }, { text: data.addressList.join(', '), style: 'cell' }],
done

2024-01-23 09:31 UTC, ulysseferreira commented on src/data/pdf/trainerMission.js
> +const composeCourseName = (course) => {
done

2024-01-23 09:32 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
parce que le format que renvoie pdfmake ne contient pas cette partie et elle permet de définir le type dans uploadMedia

2024-01-23 10:51 UTC, ulysseferreira commented on src/data/pdf/trainerMission.js
> +        { text: 'Fait à Paris,', alignment: 'right' },
j'ai repris le modèle que les ops m'ont transmis + geoffroy a dit que c'était pas grave si c'était sur 2 pages, c'est juste un doc technique

2024-01-23 13:37 UTC, manonpalin commented on src/helpers/utils.js
> +exports.getDates = (slots) => {
Que penses-tu de renommer cette methode ? je trouve que le nom est trop genérique car on ne recupere pas seulemetn les dates, on les formatte et on retire les doublons

2024-01-23 13:37 UTC, manonpalin commented on src/helpers/utils.js
> +exports.getDates = (slots) => {
On pourrait la renommer `formatSlotDates` ou `formatDates` si on ne veut pas rendre le nom trop spécifique

2024-01-23 13:41 UTC, manonpalin commented on src/helpers/trainerMissions.js
> +  const datas = {
Pour alléger un peu, que penses-tu d'extraire les données de courses[0] : `  const { trainer, subProgram, slots, slotsToPlan } = courses[0];` ?

2024-01-23 13:48 UTC, manonpalin commented on src/data/pdf/trainerMission.js
> +    [{ text: 'Lieu(x) de la formation' }, { text: data.addressList.join(', '), style: 'cell' }],
Tu pourrais mettre un s a groupe aussi non?

2024-01-23 13:48 UTC, manonpalin commented on src/helpers/trainerMissions.js
> +  const infos = {
On ne met pas de s a datas si ?

2024-01-23 14:22 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  const infos = {
les 2 se disent il me semble mais je peux retirer

2024-01-23 14:24 UTC, ulysseferreira commented on src/data/pdf/trainerMission.js
> +    [{ text: 'Lieu(x) de la formation' }, { text: data.addressList.join(', '), style: 'cell' }],
done

2024-01-23 14:25 UTC, ulysseferreira commented on src/helpers/utils.js
> +exports.getDates = (slots) => {
done

2024-01-23 14:27 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  const datas = {
done

2024-01-24 15:08 UTC, manonpalin approved these changes

2024-01-24 16:37 UTC, sophiemoustard commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
tu es sur que c'est une bonne pratique de rajouter la clé comme ca dans le PDF ?

2024-01-24 17:04 UTC, sophiemoustard requested changes

2024-01-25 11:07 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
au départ j'envoyais le pdf tel quel mais quand je le téléchargais j'avais un fichier vide donc je suis allé sur gcs pour regarder ce qui n'allait pas et la différence avec les autres pdf c'est que le type n'était pas renseigné car dans l'objet PDFDocument y a pas cette partie hapi qu'on retrouve quand on upload un document et qui est utilisé dans uploadMedia

2024-01-25 11:10 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  const fileName = `ordre mission ${data.program} ${UtilsHelper.formatIdentity(data.trainerIdentity, 'FL')}`;
done

2024-01-25 11:14 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  };
done

2024-01-25 11:15 UTC, ulysseferreira commented on src/repositories/CourseRepository.js
> +      ? 'misc type archivedAt estimatedStartDate createdAt maxTrainees trainees hasCertifyingTest'
parce qu'on a besoin de hasCertifyingTest en front pour affichier si la formation est certifiante ou non

2024-01-25 11:24 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  });
done

2024-01-25 14:34 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
j'ai pas trouvé d'autres moyens dans la doc de pdfmake/pdfkit, j'ai fait quelques tentatives avec pipe et createWriteStream ou en faisant une copie {...pdf, hapi: {}} mais sans succès

2024-01-25 16:01 UTC, sophiemoustard commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
pour les documents qu'on envoie du front, il passe par notre systeme de routing API et donc par HAPI, d'ou l la presence de cette clé sur ces documents
Je suis perplexe d'utiliser la meme cle pour ca ; je ne suis pas sure que ce soit une bonne pratique et si on utilisait pas `hapi` mais autre chose pour notre routing back ce serait une cle differente.
Il manque peut etre des elements dans le header de l'appel qui envoie le document a GCP ; tu pourrais creuser cette piste

2024-01-25 16:13 UTC, sophiemoustard commented on src/helpers/trainerMissions.js
> +  const courses = await Course
le requete ne vas pas dans la methode `format` qui par definition formatte des données ^^

2024-01-25 16:13 UTC, sophiemoustard commented on src/helpers/trainerMissions.js
> +  pdf.hapi = {
autre piste, dans ce que tu ajoutes il y a noté `form-data; name="file"; filename="${fileName}"` > est ce qu'il ne faudrait pas que tu envoies du coup sous la forme d'un `FormData` justement avec 2 clés `file` et `fileName` ?

2024-01-26 09:09 UTC, sophiemoustard reviewed
je pense que tu peux architecturer ton code comme suit :
- une methode `generate` qui appelle `Course.find` / `formatData` / `getPdf` / `uploadDocument`
- la methode `formatData` prend en argument `courses` / `fee`/ `credentials` et fait le formattage de l'objet
- la methode `uploadDocument` 
    - prend en argument `file` / `payload` / `course` ou `courses[0] / `method` / `credentials`  
    - elle appelle `getFileName`
    - elle definit contentType si method === GENERATION
    - elle apelle `uploadCourseFile` et `create`

2024-01-26 09:09 UTC, sophiemoustard commented on src/helpers/utils.js
> +} = require('./constants');
a remettre sur une ligne

2024-01-26 09:10 UTC, sophiemoustard commented on src/helpers/trainerMissions.js
> +  const data = {
ut peux retourner directement l'objet

2024-01-26 09:25 UTC, ulysseferreira commented on src/helpers/utils.js
> +} = require('./constants');
done

2024-01-26 09:26 UTC, ulysseferreira commented on src/helpers/trainerMissions.js
> +  const data = {
done

2024-01-26 11:15 UTC, sophiemoustard approved these changes

2024-01-26 11:15 UTC, merged