Com 3671
sophiemoustard/compani-api pull request #2374
Opened 2024-03-19 10:11 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2024-03-19 14:17 UTC, manonpalin commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToCompanies = !!bill.companies
Pourquoi `!!` ?

2024-03-19 14:17 UTC, manonpalin commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToPayer = !!UtilsHelper.hasUserAccessToCompany(credentials, bill.payer);
Idem

2024-03-19 14:17 UTC, manonpalin commented on src/routes/preHandlers/courseCreditNotes.js
> +    const hasAccessToCompany = !!creditNote.companies
Idem

2024-03-19 14:31 UTC, ulysseferreira commented on src/routes/preHandlers/companies.js
> +  if (!UtilsHelper.hasUserAccessToCompany(credentials, req.params._id)) {
done

2024-03-19 14:32 UTC, ulysseferreira commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToCompanies = !!bill.companies
pour que ça renvoie un booléen et pas une valeur, tu penses que osef on peut laisser une valeur vu que c'est pareil pour le if ?

2024-03-20 08:34 UTC, manonpalin commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToCompanies = !!bill.companies
Je pense que si tu le laisse il faut mettre des parentheses pour montrer que le !! est autour de l'ensemble

2024-03-20 08:36 UTC, manonpalin commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToPayer = !!UtilsHelper.hasUserAccessToCompany(credentials, bill.payer);
ici hasUserAccessToCompany renvoie deja un booleen donc tu peux supprimer le `!!`

2024-03-20 08:37 UTC, manonpalin commented on src/routes/preHandlers/courseCreditNotes.js
> +    const hasAccessToCompany = !!creditNote.companies
Ici tu peux aussi ajouter les parentheses

2024-03-20 10:12 UTC, ulysseferreira commented on src/routes/preHandlers/courseBills.js
> +    const hasAccessToCompanies = !!bill.companies
done

2024-03-20 10:13 UTC, ulysseferreira commented on src/routes/preHandlers/courseCreditNotes.js
> +    const hasAccessToCompany = !!creditNote.companies
done

2024-03-20 17:49 UTC, sophiemoustard requested changes

2024-03-21 08:21 UTC, sophiemoustard commented on tests/integration/companies.test.js
> +    it('should return 404 if billingRepresentative is from other company', async () => {
from other company not in holding ?

2024-03-21 08:58 UTC, ulysseferreira commented on src/data/rights.js
> +  { permission: 'companies:read', rolesConcerned: [VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER, CLIENT_ADMIN, HOLDING_ADMIN], description: 'Consulter les données des organisations' },
actuellement on l'appelle pas au final mais ça me semblait pas illogique qu'un admin_client ait accès à sa propre structure, tu penses que ça sert à rien de le mettre tant qu'on l'utilise pas ?

2024-03-21 08:58 UTC, ulysseferreira commented on src/helpers/courseBills.js
> +  const requestingOwnInfos = !!companies.find(company => UtilsHelper.hasUserAccessToCompany(credentials, company));
bien vu

2024-03-21 08:58 UTC, ulysseferreira commented on src/routes/preHandlers/companies.js
> +  if (!isVendorAdmin && (!UtilsHelper.hasUserAccessToCompany(credentials, updatedCompanyId))) throw Boom.forbidden();
done

2024-03-21 08:59 UTC, ulysseferreira commented on src/routes/preHandlers/courseBills.js
> +      .find(company => UtilsHelper.hasUserAccessToCompany(credentials, company)));
done

2024-03-21 08:59 UTC, ulysseferreira commented on src/routes/preHandlers/courseCreditNotes.js
> +      .find(company => UtilsHelper.hasUserAccessToCompany(credentials, company)));
done

2024-03-21 09:00 UTC, ulysseferreira commented on tests/integration/companies.test.js
> +    it('should return 404 if billingRepresentative is from other company', async () => {
done

2024-03-21 13:13 UTC, sophiemoustard commented on src/data/rights.js
> +  { permission: 'companies:read', rolesConcerned: [VENDOR_ADMIN, TRAINING_ORGANISATION_MANAGER, CLIENT_ADMIN, HOLDING_ADMIN], description: 'Consulter les données des organisations' },
au debut ca m'a surpris mais je me dis que ca pourrait simplifier le rafraichissement en front de la structure du store ; on ne passerai plus par la structure dans loggedUser (sauf peut etre au moment du created pour récupérer l'id) mais on pourrait appeler `fetchCompany` a chaque fois

2024-03-21 14:27 UTC, manonpalin approved these changes

2024-03-22 09:58 UTC, sophiemoustard approved these changes

2024-03-22 09:58 UTC, merged