Com 3719
sophiemoustard/compani-api pull request #2395
Opened 2024-06-13 12:03 UTC by manonpalin

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [ ] C'est une ancienne route utilisée par les apps mobiles. -np
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details closed><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details closed><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2024-06-13 14:26 UTC, ulysseferreira commented on src/helpers/questionnaireHistories.js
> +      const qa = questionnaireHistory.questionnaireAnswersList
est-ce-qu'on créerait pas une variable questionnaireAnswersListByCard avec un keyBy pour éviter d'avoir à faire un find à chaque fois ?

2024-06-13 14:26 UTC, ulysseferreira commented on src/routes/preHandlers/questionnaireHistories.js
> +  const everyAnswerIsAuthorized = trainerAnswers.every((a) => {
idem on fait un cardById avec un keyBy et ensuite dans le every : 
```
return !a.answer || Object.keys(get(card, 'labels')).includes(a.answer)
```

2024-06-13 15:08 UTC, manonpalin commented on src/helpers/questionnaireHistories.js
> +      const qa = questionnaireHistory.questionnaireAnswersList
Ah oui bonne idee !

2024-06-13 15:21 UTC, manonpalin commented on src/routes/preHandlers/questionnaireHistories.js
> +  const everyAnswerIsAuthorized = trainerAnswers.every((a) => {
corrigé

2024-06-13 15:51 UTC, ulysseferreira commented on src/models/QuestionnaireHistory.js
> +    trainerAnswerList: { type: [String] },
il est créé par défaut à la création de l'historique et du coup quand on ajuste pas la note on a un champ vide en base trainerAsnwersList, c'est voulu ?

2024-06-14 07:52 UTC, manonpalin commented on src/models/QuestionnaireHistory.js
> +    trainerAnswerList: { type: [String] },
Hmm non en effet, on peut ajouter undefined dans le modele pour eviter d'avoir des elements vides

2024-06-14 08:29 UTC, ulysseferreira approved these changes

2024-06-17 08:09 UTC, sophiemoustard commented on src/routes/preHandlers/questionnaireHistories.js
> +  const everyAnswerIsAuthorized = trainerAnswers.every((a) => {
on risque d'avoir un souci si pour une carte on n'a pas detaillé tous les labels non ? en base il n'y aura que les labels 1 et 5

2024-06-17 08:09 UTC, sophiemoustard commented on src/helpers/questionnaireHistories.js
> +    for (const trainerAnswer of trainerAnswers) {
je me demande s'il ne faudrait pas plutot boucler sur `questionnaireHistory.questionnaireAnswersList` pour etre sur de ne pas perdre de reponses de l'apprenant 🤔

2024-06-17 12:24 UTC, manonpalin commented on src/helpers/questionnaireHistories.js
> +    for (const trainerAnswer of trainerAnswers) {
La condition `answersHasGoodLength` dans le prehandler permet d'eviter ce probleme non ?

2024-06-17 12:28 UTC, manonpalin commented on src/routes/preHandlers/questionnaireHistories.js
> +  const everyAnswerIsAuthorized = trainerAnswers.every((a) => {
Hmm oui bien vu. Il faut donc supprimer cette condition

A priori les 5 labels doivent etre definis dans le cas des questionnaires d'auto-positionnement et je me demande si on ne devrait pas cocher automatiquement "Définir les légendes de chaque niveau" et rendre ce champ non editable quand on selectionne une carte Sondage dans un questionnaire d'auto-positionnement. Qu'en penses-tu ?

2024-06-18 06:55 UTC, sophiemoustard commented on src/routes/preHandlers/questionnaireHistories.js
> +  const everyAnswerIsAuthorized = trainerAnswers.every((a) => {
hum bonne question ; je ne me rends pas trop compte de comment les questionnaires vont evoluer 🤔 
est ce qu'on ne pourrait pas se dire que les reponses doivent toutes etre entre 1 et 5 comme condition ? ca prend en compte les 2 cas : si on a 5 labels et si on n'en a que 2

2024-06-18 06:57 UTC, sophiemoustard commented on src/helpers/questionnaireHistories.js
> +    for (const trainerAnswer of trainerAnswers) {
hum je ne suis pas sure que ce soit suffisant ; on ne verifie pas que toutes les cartes ont une reponse : s'il y a 2 fois la reponse pour une meme carte et pas de reponse pour une autre carte

et de manière general, je me dis que en bouclant sur `questionnaireHistory.questionnaireAnswersList` on est sur de ne pas modifier la liste autrement qu'en ajoutant ce qu'on precise ; en bouclant sur `trainerAnswers` on a beaucoup moins de garantie que l'objet final soit proche de l'initial

2024-06-18 10:15 UTC, manonpalin commented on src/helpers/questionnaireHistories.js
> +    for (const trainerAnswer of trainerAnswers) {
Ok c'est modifié

2024-06-18 13:32 UTC, sophiemoustard requested changes

2024-06-18 13:32 UTC, sophiemoustard commented on src/routes/preHandlers/questionnaireHistories.js
> +    .populate({ path: 'cards', select: 'labels' })
je pense qu'on n'a plus besoin de ce `populate` du coup

2024-06-18 14:29 UTC, manonpalin commented on src/routes/preHandlers/questionnaireHistories.js
> +    .populate({ path: 'cards', select: 'labels' })
oui et j'ai transformé le findOne en countDocuments

2024-06-19 07:01 UTC, sophiemoustard approved these changes

2024-06-19 07:02 UTC, merged